import { ArrowLeft, ArrowRight, Bug, CheckCircle2, Gauge, Image as ImageIcon, Layers3, X, XCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import type { BenchmarkStep, DebugImageRef, ScopeRunResult, VisionRunResult } from '../../api/visionAppApi';
import { VisionViewport } from './VisionViewport';

type TraceStage={id:string;scope:string;label:string;phase:string;kind:'image'|'logic';imageKey?:string;elapsedMs?:number;service?:any};
type Props={open:boolean;runId:string|null;items:DebugImageRef[];benchmarks:BenchmarkStep[];runResult?:VisionRunResult|null;title?:string;onClose:()=>void;load:(runId:string,key:string)=>Promise<string>};

const scopeResults=(run?:VisionRunResult|null):Record<string,ScopeRunResult>=>{const out:Record<string,ScopeRunResult>={};if(run?.global_scope)out.global=run.global_scope;for(const station of run?.stations??[]){if(station.scope)out[station.station_id]=station.scope;}return out;};
const summarize=(value:any):string=>{if(value==null)return 'null';if(typeof value==='number')return Number.isFinite(value)?value.toFixed(5):String(value);if(typeof value==='string'||typeof value==='boolean')return String(value);if(Array.isArray(value))return `Array[${value.length}]`;if(typeof value==='object')return `{ ${Object.keys(value).slice(0,5).join(', ')}${Object.keys(value).length>5?', …':''} }`;return String(value);};

export const DebugWorkspace=({open,runId,items,benchmarks,runResult,title='Working Debug Stack',onClose,load}:Props)=>{
  const [selected,setSelected]=useState<string>('');
  const [busy,setBusy]=useState(false);
  const [cache,setCache]=useState<Record<string,string>>({});
  const scopes=useMemo(()=>scopeResults(runResult),[runResult]);
  const stages=useMemo(()=>{
    const result:TraceStage[]=items.map((item,index)=>({id:`img:${item.key}`,scope:item.scope,label:item.label,phase:item.phase,kind:'image',imageKey:item.key,elapsedMs:benchmarks.find(b=>b.scope===item.scope&&b.phase==='filter'&&item.label.includes(b.name))?.elapsed_ms}));
    for(const [scopeId,scope] of Object.entries(scopes))for(const service of scope.logic_services??[])result.push({id:`logic:${scopeId}:${service.binding_id}`,scope:scopeId,label:`Logic · ${service.alias||service.service_id}`,phase:'logic',kind:'logic',elapsedMs:service.elapsed_ms,service});
    return result;
  },[items,benchmarks,scopes]);
  const groups=useMemo(()=>{const order:string[]=[];const map:Record<string,TraceStage[]>={};for(const stage of stages){if(!map[stage.scope]){map[stage.scope]=[];order.push(stage.scope);}map[stage.scope].push(stage);}return order.map(scope=>({scope,stages:map[scope]}));},[stages]);
  const currentIndex=stages.findIndex(s=>s.id===selected);
  const current=stages[currentIndex]??null;
  const currentUrl=current?.kind==='image'&&current.imageKey?cache[current.imageKey]??null:null;

  useEffect(()=>{if(!open){for(const url of Object.values(cache))URL.revokeObjectURL(url);setCache({});setSelected('');}},[open]);
  useEffect(()=>{if(open&&stages.length&&!selected)void choose(stages[0]);},[open,stages.length]);
  if(!open)return null;
  async function choose(stage:TraceStage){setSelected(stage.id);if(stage.kind!=='image'||!stage.imageKey||cache[stage.imageKey]||!runId)return;setBusy(true);try{const url=await load(runId,stage.imageKey);setCache(old=>({...old,[stage.imageKey!]:url}));}finally{setBusy(false);}}
  const move=(delta:number)=>{const next=stages[currentIndex+delta];if(next)void choose(next);};
  return <div className="fixed inset-0 z-[90] flex flex-col bg-[#17181a]">
    <header className="flex h-12 items-center gap-2 border-b border-[#3c4043] bg-[#292a2d] px-3"><Bug size={14} className="text-[#c58af9]"/><b className="text-[11px] tracking-[.15em]">DEBUG STACK WORKSPACE</b><span className="text-[8px] text-[#80868b]">{title} · images lazy-load on selection</span><div className="ml-auto flex items-center gap-1"><button className="cv-btn" disabled={currentIndex<=0} onClick={()=>move(-1)}><ArrowLeft size={10}/>Prev</button><button className="cv-btn" disabled={currentIndex<0||currentIndex>=stages.length-1} onClick={()=>move(1)}>Next<ArrowRight size={10}/></button><button className="cv-btn" onClick={onClose}><X size={11}/>Close</button></div></header>
    <div className="grid min-h-0 flex-1 grid-cols-[300px_minmax(0,1fr)_300px]">
      <aside className="overflow-y-auto border-r border-[#3c4043] bg-[#242528] p-2"><div className="mb-2 flex items-center gap-2 px-1 text-[8px] font-black text-[#9aa0a6]"><Layers3 size={11}/>PIPELINE STACK</div>{groups.map(group=><div key={group.scope} className="mb-3"><div className="mb-1 rounded bg-[#202124] px-2 py-1.5 text-[7px] font-black uppercase tracking-[.12em] text-[#8ab4f8]">{group.scope}</div><div className="space-y-1">{group.stages.map((stage,index)=><button key={stage.id} className={`w-full rounded border p-2 text-left ${selected===stage.id?'border-[#c58af9] bg-[#3b3150]':'border-[#3c4043] bg-[#202124]'}`} onClick={()=>void choose(stage)}><div className="flex items-center gap-1.5"><span className="flex h-4 w-4 items-center justify-center rounded-full bg-[#35363a] text-[6px] font-black">{index+1}</span>{stage.kind==='image'?<ImageIcon size={10} className="text-[#8ab4f8]"/>:<Gauge size={10} className="text-[#81c995]"/>}<b className="min-w-0 flex-1 truncate text-[8px]">{stage.label}</b></div><div className="mt-1 flex items-center gap-2 pl-6 text-[6px] text-[#80868b]"><span>{stage.phase}</span>{stage.elapsedMs!=null?<span className="text-[#fdd663]">{stage.elapsedMs.toFixed(2)} ms</span>:null}</div></button>)}</div></div>)}</aside>
      <section className="relative min-w-0 bg-[#101113]">{current?.kind==='image'?<VisionViewport imageUrl={currentUrl}/>:current?.kind==='logic'?<div className="h-full overflow-auto p-5"><div className="mx-auto max-w-4xl"><div className="mb-3 text-[10px] font-black text-[#81c995]">LOGIC OUTPUT INSPECTOR</div><div className="rounded-lg border border-[#3c4043] bg-[#202124] p-4"><div className="flex items-center gap-2">{current.service?.ok?<CheckCircle2 size={15} className="text-[#81c995]"/>:<XCircle size={15} className="text-[#f28b82]"/>}<b>{current.label}</b><span className="ml-auto text-[8px] text-[#fdd663]">{Number(current.service?.elapsed_ms??0).toFixed(2)} ms</span></div><div className="mt-1 text-[7px] text-[#80868b]">{current.service?.service_id}</div><div className="mt-4 grid grid-cols-2 gap-2">{Object.entries(current.service?.outputs??{}).map(([name,value])=><div key={name} className="rounded border border-[#3c4043] bg-[#242528] p-3"><div className="text-[7px] font-black text-[#8ab4f8]">{name}</div><div className="mt-1 font-mono text-[9px]">{summarize(value)}</div><pre className="mt-2 max-h-36 overflow-auto whitespace-pre-wrap text-[6px] text-[#80868b]">{JSON.stringify(value,null,2)}</pre></div>)}</div></div></div></div>:<div className="flex h-full items-center justify-center text-[9px] text-[#80868b]">Select a stage from the pipeline stack.</div>}{busy?<div className="absolute left-3 top-3 rounded bg-black/75 px-3 py-2 text-[8px]">Lazy-loading selected artifact…</div>:null}</section>
      <aside className="overflow-y-auto border-l border-[#3c4043] bg-[#242528] p-3"><div className="mb-3 text-[8px] font-black text-[#9aa0a6]">STAGE INSPECTOR</div>{current?<><div className="rounded border border-[#3c4043] bg-[#202124] p-3"><div className="text-[10px] font-black">{current.label}</div><div className="mt-2 grid grid-cols-2 gap-2 text-[7px]"><div><span className="text-[#80868b]">Scope</span><div>{current.scope}</div></div><div><span className="text-[#80868b]">Phase</span><div>{current.phase}</div></div><div><span className="text-[#80868b]">Artifact</span><div>{current.kind}</div></div><div><span className="text-[#80868b]">Timing</span><div>{current.elapsedMs!=null?`${current.elapsedMs.toFixed(2)} ms`:'—'}</div></div></div></div><div className="mt-3 rounded border border-[#3c4043] bg-[#202124] p-3 text-[7px] leading-4 text-[#9aa0a6]">Use Prev/Next like an Image Processing LAB pipeline to walk stage-by-stage. Image bytes stay out of browser memory until the stage is selected; selected images are cached for the current debug session.</div></>:<div className="text-[8px] text-[#80868b]">No stage selected.</div>}<div className="mt-3 text-[8px] font-black text-[#9aa0a6]">BENCHMARK TRACE</div><div className="mt-2 space-y-1">{benchmarks.map((b,i)=><div key={`${b.scope}-${b.phase}-${i}`} className="rounded border border-[#3c4043] bg-[#202124] p-2"><div className="flex gap-2"><b className="min-w-0 flex-1 truncate text-[7px]">{b.scope} · {b.name}</b><span className="text-[7px] text-[#fdd663]">{b.elapsed_ms.toFixed(2)} ms</span></div><div className="mt-1 truncate text-[6px] text-[#80868b]">{b.phase} · {b.detail}</div></div>)}</div></aside>
    </div>
  </div>;
};
