import { FlaskConical, Upload } from 'lucide-react';
import type { VisionProgramDefinition } from '../../api/visionAppApi';

type Props={program:VisionProgramDefinition;onSetPoint:(device:string,point:string,value:any)=>Promise<void>;onCameraFrame:(camera:string,file:Blob)=>Promise<void>};
const safe=(v:string)=>v.trim().replace(/[^A-Za-z0-9_]+/g,'_').replace(/^([0-9])/,'_$1')||'object';
export const DeveloperSimulatorWorkspace=({program,onSetPoint,onCameraFrame}:Props)=> <div className="h-full overflow-y-auto bg-[#17191d] p-4 text-[#e8eaed]"><div className="mx-auto max-w-[1050px]"><div className="mb-4 flex items-center gap-2"><FlaskConical size={16} className="text-[#fdd663]"/><div><b className="text-[11px] tracking-[.12em]">DEVELOPER SIMULATOR</b><div className="text-[7px] text-[#8b949e]">Same endpoint objects, simulated drivers. Replace driver later without rewriting Automation scripts.</div></div></div>
 <div className="grid grid-cols-2 gap-4"><section className="rounded-xl border border-[#34363a] bg-[#22252a] p-3"><b className="text-[9px] text-[#65d1ff]">SIMULATED IOT</b>{program.iot.devices.filter(d=>d.driver==='simulated').map(d=><div key={d.declaration_id} className="mt-3 rounded border border-[#34363a] bg-[#1b1e23] p-2"><div className="font-mono text-[8px] text-[#65d1ff]">device.{safe(d.alias)}</div>{d.points.map(p=><div key={p.point_id} className="mt-2 flex items-center gap-2 text-[8px]"><span className="w-[120px] truncate">{p.alias}</span>{p.kind==='coil'||p.kind==='discrete_input'?<><button className="cv-mini" onClick={()=>void onSetPoint(safe(d.alias),safe(p.alias),false)}>OFF</button><button className="cv-mini text-[#81c995]" onClick={()=>void onSetPoint(safe(d.alias),safe(p.alias),true)}>ON</button></>:<input className="cv-field !mt-0 w-[110px]" type="number" defaultValue={0} onBlur={e=>void onSetPoint(safe(d.alias),safe(p.alias),Number(e.target.value))}/>}<span className="ml-auto font-mono text-[6px] text-[#6f7882]">{p.kind}</span></div>)}</div>)}{!program.iot.devices.some(d=>d.driver==='simulated')?<div className="mt-4 text-[8px] text-[#70777f]">Set an IOT declaration driver to Simulated.</div>:null}</section>
 <section className="rounded-xl border border-[#34363a] bg-[#22252a] p-3"><b className="text-[9px] text-[#81c995]">SIMULATED CAMERAS</b>{program.cameras.devices.filter(c=>c.driver==='simulated').map(c=><div key={c.declaration_id} className="mt-3 rounded border border-[#34363a] bg-[#1b1e23] p-3"><div className="font-mono text-[8px] text-[#81c995]">camera.{safe(c.alias)}</div><div className="mt-1 text-[7px] text-[#777f88]">Upload a frame into both {c.image_slot} and {c.stream_slot}.</div><label className="cv-btn mt-2 cursor-pointer"><Upload size={9}/>Load image<input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void onCameraFrame(safe(c.alias),f);}}/></label></div>)}{!program.cameras.devices.some(c=>c.driver==='simulated')?<div className="mt-4 text-[8px] text-[#70777f]">Declare a Simulated camera to replay images without hardware.</div>:null}</section></div>
 <div className="mt-4 rounded-xl border border-[#5a4d25] bg-[#2b2618] p-3 text-[8px] leading-5 text-[#fdd663]">Simulator values flow through the real Endpoint Registry and Safe DSL. A script such as <span className="font-mono">if device.sim_plc.X1 == ON:</span> behaves the same after changing the declaration to a real Modbus TCP driver.</div></div></div>;
