import { useMemo, useState } from 'react';
import { ChevronDown, ChevronRight, CirclePlay, Code2, Cpu, Database, Sparkles } from 'lucide-react';
import type { AutomationEndpoint } from '../../api/visionAppApi';

type Node={name:string;path:string;spec?:AutomationEndpoint;children:Map<string,Node>};
type Props={endpoints:AutomationEndpoint[];query:string;onInsert:(endpoint:AutomationEndpoint)=>void};
const color=(path:string)=>path.startsWith('device.')?'#fdd663':path.startsWith('vision.roi.')?'#ff8ab4':path.startsWith('vision.')?'#c58af9':path.startsWith('system.')?'#65d1ff':path.startsWith('camera.')?'#81c995':path.startsWith('workspace.')?'#ffb86c':path.startsWith('keyboard.')?'#ff8ab4':'#9aa0a6';
const icon=(s?:AutomationEndpoint)=>s?.kind==='action'?CirclePlay:s?.kind==='event'?Sparkles:s?.kind==='state'?Code2:s?.data_type==='object'||s?.data_type==='namespace'||s?.data_type==='roi'||s?.data_type==='logic_service'||s?.data_type==='modbus_tcp_device'?Cpu:Database;
const build=(eps:AutomationEndpoint[])=>{const root:Node={name:'root',path:'',children:new Map()};for(const spec of eps){let node=root;let current='';for(const part of spec.path.split('.')){current=current?`${current}.${part}`:part;if(!node.children.has(part))node.children.set(part,{name:part,path:current,children:new Map()});node=node.children.get(part)!;}node.spec=spec;}return root;};

const Branch=({node,level,query,onInsert}:{node:Node;level:number;query:string;onInsert:(e:AutomationEndpoint)=>void})=>{const [open,setOpen]=useState(level<2);const children=[...node.children.values()];const q=query.toLowerCase();const matches=!q||node.path.toLowerCase().includes(q)||children.some(c=>c.path.toLowerCase().includes(q));if(!matches)return null;const hasChildren=children.length>0;const Icon=icon(node.spec);const c=color(node.path);return <div>{<div className="group flex items-center gap-1 py-[3px] pr-1 hover:bg-[#29313a]" style={{paddingLeft:6+level*12}}><button className="flex h-4 w-4 items-center justify-center text-[#65707b]" onClick={()=>setOpen(v=>!v)}>{hasChildren?(open?<ChevronDown size={10}/>:<ChevronRight size={10}/>):null}</button><Icon size={9} style={{color:c}}/><button onClick={()=>node.spec&&onInsert(node.spec)} className="min-w-0 flex-1 truncate text-left font-mono text-[8px]" style={{color:node.spec?c:'#9da7b1'}}>{node.name}</button>{node.spec?<span title={node.spec.allowed_values?.length?`Allowed: ${node.spec.allowed_values.join(', ')}`:node.spec.description} className="opacity-0 group-hover:opacity-100 rounded bg-[#31363d] px-1 text-[6px] text-[#88929d]">{node.spec.data_type}{node.spec.allowed_values?.length?` · ${node.spec.allowed_values.join('|')}`:''}</span>:null}</div>}{open?children.map(child=><Branch key={child.path} node={child} level={level+1} query={query} onInsert={onInsert}/>):null}</div>};
export const EndpointObjectTree=({endpoints,query,onInsert}:Props)=>{const root=useMemo(()=>build(endpoints),[endpoints]);return <div className="py-1">{[...root.children.values()].map(n=><Branch key={n.path} node={n} level={0} query={query} onInsert={onInsert}/>)}</div>};
