import { Activity, CheckCircle2, Keyboard, Plus, Trash2, XCircle } from 'lucide-react';
import type { ControlMapperConfig, ModbusIOConfig } from '../../api/visionAppApi';

type Props={config:ModbusIOConfig;control:ControlMapperConfig;onChange:(next:ModbusIOConfig)=>void;onControl:(next:ControlMapperConfig)=>void;onRead:()=>void;onPulse:(result:'ok'|'ng')=>void;triggerState:boolean|null;busy:boolean};
export const IotModulePanel=({config,control,onChange,onControl,onRead,onPulse,triggerState,busy}:Props)=>{
 const patch=(p:Partial<ModbusIOConfig>)=>onChange({...config,...p});
 const num=(name:keyof ModbusIOConfig,value:string)=>patch({[name]:Number(value)} as any);
 const patchBinding=(id:string,p:any)=>onControl({...control,bindings:control.bindings.map(b=>b.binding_id===id?{...b,...p}:b)});
 return <div className="space-y-3 p-3 text-[9px]">
  <div className="rounded-lg border border-[#3c4043] bg-[#242528] p-3"><div className="flex items-center gap-2 text-[10px] font-black"><Activity size={13} className="text-[#8ab4f8]"/>MODBUS TCP I/O</div><div className="mt-1 text-[8px] leading-4 text-[#9aa0a6]">Hardware stays an adapter. Control Mapper below converts keyboard or Modbus events into primitive Vision actions. The center IDE viewport is reserved for the future sandbox/glue system.</div></div>
  <label className="flex items-center gap-2"><input type="checkbox" checked={config.enabled} onChange={e=>patch({enabled:e.target.checked})}/>Enable I/O</label>
  <div className="grid grid-cols-2 gap-2"><label>Host<input value={config.host} onChange={e=>patch({host:e.target.value})} className="cv-field"/></label><label>Port<input type="number" value={config.port} onChange={e=>num('port',e.target.value)} className="cv-field"/></label><label>Device ID<input type="number" value={config.device_id} onChange={e=>num('device_id',e.target.value)} className="cv-field"/></label><label>Trigger type<select value={config.trigger_kind} onChange={e=>patch({trigger_kind:e.target.value as any})} className="cv-field"><option value="discrete_input">Discrete input</option><option value="coil">Coil</option></select></label><label>Trigger address<input type="number" value={config.trigger_address} onChange={e=>num('trigger_address',e.target.value)} className="cv-field"/></label><label>Poll ms<input type="number" value={config.poll_interval_ms} onChange={e=>num('poll_interval_ms',e.target.value)} className="cv-field"/></label><label>OK coil<input type="number" value={config.ok_coil} onChange={e=>num('ok_coil',e.target.value)} className="cv-field"/></label><label>NG coil<input type="number" value={config.ng_coil} onChange={e=>num('ng_coil',e.target.value)} className="cv-field"/></label><label>Pulse seconds<input type="number" step="0.1" value={config.pulse_seconds} onChange={e=>num('pulse_seconds',e.target.value)} className="cv-field"/></label><label className="flex items-end gap-2 pb-1"><input type="checkbox" checked={config.trigger_active_high} onChange={e=>patch({trigger_active_high:e.target.checked})}/>Active HIGH</label></div>
  <div className="grid grid-cols-3 gap-2"><button disabled={busy} onClick={onRead} className="cv-btn">Read Trigger</button><button disabled={busy} onClick={()=>onPulse('ok')} className="cv-btn border-[#81c995] text-[#81c995]"><CheckCircle2 size={11}/>Pulse OK</button><button disabled={busy} onClick={()=>onPulse('ng')} className="cv-btn border-[#f28b82] text-[#f28b82]"><XCircle size={11}/>Pulse NG</button></div>
  <div className="rounded border border-[#3c4043] bg-[#202124] p-2">Trigger state: <b className={triggerState?'text-[#81c995]':'text-[#9aa0a6]'}>{triggerState==null?'not read':triggerState?'ACTIVE':'inactive'}</b></div>
  <div className="rounded-lg border border-[#5f6368] bg-[#242528] p-3"><div className="mb-2 flex items-center gap-2 text-[9px] font-black text-[#c58af9]"><Keyboard size={12}/>CONTROL MAPPER</div><div className="mb-2 text-[7px] leading-4 text-[#80868b]">Primitive actions are deliberately small: Trigger Camera, Run Inspection, Out OK, Out NG, Clear Working Screen. Keyboard works now; future IDE/sandbox can emit the same actions.</div>{control.bindings.map(b=><div key={b.binding_id} className="mb-2 grid grid-cols-[24px_90px_82px_1fr_24px] items-center gap-1 rounded border border-[#3c4043] bg-[#202124] p-1"><input type="checkbox" checked={b.enabled} onChange={e=>patchBinding(b.binding_id,{enabled:e.target.checked})}/><select className="cv-field !mt-0" value={b.source} onChange={e=>patchBinding(b.binding_id,{source:e.target.value})}><option value="keyboard">Keyboard</option><option value="modbus_trigger">Modbus trigger</option></select><input disabled={b.source!=='keyboard'} className="cv-field !mt-0" value={b.key} onChange={e=>patchBinding(b.binding_id,{key:e.target.value})}/><select className="cv-field !mt-0" value={b.action} onChange={e=>patchBinding(b.binding_id,{action:e.target.value})}><option value="trigger_camera">Trigger Camera</option><option value="run_inspection">Run Inspection</option><option value="out_ok">Out OK</option><option value="out_ng">Out NG</option><option value="clear_working_screen">Clear Working Screen</option></select><button className="cv-icon" onClick={()=>onControl({...control,bindings:control.bindings.filter(x=>x.binding_id!==b.binding_id)})}><Trash2 size={10}/></button></div>)}<button className="cv-btn w-full" onClick={()=>onControl({...control,bindings:[...control.bindings,{binding_id:`map_${Date.now()}`,enabled:true,source:'keyboard',key:'F11',action:'trigger_camera'}]})}><Plus size={10}/>Add mapping</button></div>
 </div>;
};
