import { Crosshair, Eye, Trash2, Upload } from 'lucide-react';
import type { MasterRoi, RoiLocatorConfig } from '../../api/visionAppApi';

type Props={rois:MasterRoi[];locator:RoiLocatorConfig;selectedId:string|null;drawMode:boolean;onDrawMode:(v:boolean)=>void;onSelect:(id:string)=>void;onChange:(roi:MasterRoi)=>void;onRemove:(id:string)=>void;onLocator:(next:RoiLocatorConfig)=>void;onUpload:(file:File)=>void;onBlurPreview:()=>void;onShowOriginal:()=>void};
export const MasterSamplePanel=({rois,locator,selectedId,drawMode,onDrawMode,onSelect,onChange,onRemove,onLocator,onUpload,onBlurPreview,onShowOriginal}:Props)=>{
 const selected=rois.find(r=>r.roi_id===selectedId)??null;const patch=(p:Partial<MasterRoi>)=>selected&&onChange({...selected,...p});const patchLoc=(p:Partial<RoiLocatorConfig>)=>onLocator({...locator,...p});const patchGeo=(p:any)=>onLocator({...locator,geometry:{...locator.geometry,...p}});
 return <div className="space-y-3 p-3 text-[9px]">
  <label className="cv-btn cursor-pointer"><Upload size={11}/>Upload / Replace Master<input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(f);}}/></label>
  <div className="space-y-2 rounded-lg border border-[#5f6368] bg-[#242528] p-3"><div className="text-[9px] font-black text-[#c58af9]">AUTO ROI FAMILY · ALL STATIONS</div><label>Locator family<select value={locator.method} onChange={e=>patchLoc({method:e.target.value as any})} className="cv-field"><option value="manual">Manual coordinates</option><option value="blur_template">Blur + Template Matching</option><option value="fourier">Fourier Phase Search</option></select></label>{locator.method==='blur_template'?<><div className="grid grid-cols-2 gap-2"><label>Blur kernel<input type="number" value={locator.blur_kernel} onChange={e=>patchLoc({blur_kernel:Number(e.target.value)})} className="cv-field"/></label><label>Match threshold<input type="number" step=".01" value={locator.template_threshold} onChange={e=>patchLoc({template_threshold:Number(e.target.value)})} className="cv-field"/></label></div><div className="grid grid-cols-2 gap-2"><button className="cv-btn" onClick={onBlurPreview}><Eye size={11}/>Blur preview</button><button className="cv-btn" onClick={onShowOriginal}>Original Master</button></div></>:null}<label className="flex items-center gap-2"><input type="checkbox" checked={locator.geometry.enabled} onChange={e=>patchGeo({enabled:e.target.checked})}/>Geometry constraint</label><div className="grid grid-cols-2 gap-2"><label>Search margin px<input type="number" value={locator.geometry.search_margin_px} onChange={e=>patchGeo({search_margin_px:Number(e.target.value)})} className="cv-field"/></label><label>Max shift px<input type="number" value={locator.geometry.max_shift_px} onChange={e=>patchGeo({max_shift_px:Number(e.target.value)})} className="cv-field"/></label></div><div className="text-[7px] leading-4 text-[#80868b]">One locator family is applied to every ROI. Geometry constraints remain per-program performance/sanity guards.</div></div>
  <button onClick={()=>onDrawMode(!drawMode)} className={`cv-btn w-full ${drawMode?'border-[#8ab4f8] bg-[#174ea6]':''}`}><Crosshair size={11}/>{drawMode?'Draw ROI on image…':'Add ROI by drawing'}</button>
  <div className="rounded-lg border border-[#3c4043] bg-[#242528]"><div className="border-b border-[#3c4043] px-2 py-1.5 text-[8px] font-black">MASTER ROIs / STATIONS</div>{rois.length===0?<div className="p-4 text-center text-[#80868b]">Draw ROIs on the Master Sample.</div>:rois.map(r=><button key={r.roi_id} onClick={()=>onSelect(r.roi_id)} className={`flex w-full items-center gap-2 border-b border-[#3c4043] px-2 py-2 text-left ${selectedId===r.roi_id?'bg-[#3c4043]':''}`}><span className="h-2 w-2 rounded-full bg-[#81c995]"/><span className="flex-1 truncate">{r.name}</span></button>)}</div>
  {selected?<div className="space-y-2 rounded-lg border border-[#5f6368] bg-[#242528] p-3"><div className="flex items-center gap-2"><b className="flex-1">STATION</b><button onClick={()=>onRemove(selected.roi_id)} className="text-[#f28b82]"><Trash2 size={12}/></button></div><label>Name<input value={selected.name} onChange={e=>patch({name:e.target.value})} className="cv-field"/></label><label className="flex items-center gap-2"><input type="checkbox" checked={selected.enabled} onChange={e=>patch({enabled:e.target.checked})}/>Enabled</label><div className="text-[7px] leading-4 text-[#80868b]">ROI search method is intentionally not configured here; all stations use the program-level locator family above.</div></div>:null}
 </div>;
};
