import { ArrowDown, ArrowUp, Bug, Plus, Trash2, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { LabServiceDefinition } from '../../api/labServiceApi';
import type { ScopePipelineConfig, WorkingServiceBinding } from '../../api/visionAppApi';

type Phase='filter'|'logic';
type Props={open:boolean;phase:Phase;scopeName:string;scope:ScopePipelineConfig;services:LabServiceDefinition[];onChange:(s:ScopePipelineConfig)=>void;onClose:()=>void;onDebugPreview?:()=>Promise<void>};
const binding=(serviceId:string,index:number):WorkingServiceBinding=>({binding_id:`bind_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,service_id:serviceId,version:null,enabled:true,label:'',alias:`logic_${index+1}`});
export const ScopeEditorModal=({open,phase,scopeName,scope,services,onChange,onClose,onDebugPreview}:Props)=>{
  const [choice,setChoice]=useState('');
  const [busy,setBusy]=useState(false);
  const list=phase==='filter'?scope.filter_services:scope.logic_services;
  const candidates=useMemo(()=>phase==='filter'?services.filter(s=>s.lab_type==='image_processing'):services.filter(s=>s.lab_type!=='image_processing'),[services,phase]);
  if(!open)return null;
  const setList=(next:WorkingServiceBinding[])=>onChange(phase==='filter'?{...scope,filter_services:next}:{...scope,logic_services:next});
  const add=()=>{if(!choice)return;setList([...list,binding(choice,list.length)]);setChoice('');};
  const patch=(i:number,p:Partial<WorkingServiceBinding>)=>{const n=[...list];n[i]={...n[i],...p};setList(n);};
  const move=(i:number,d:number)=>{const j=i+d;if(j<0||j>=list.length)return;const n=[...list];[n[i],n[j]]=[n[j],n[i]];setList(n);};
  const openDebug=async()=>{if(!onDebugPreview)return;setBusy(true);try{await onDebugPreview();}finally{setBusy(false);}};
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-8"><div className="flex h-[78vh] w-[min(1050px,94vw)] flex-col overflow-hidden rounded-xl border border-[#5f6368] bg-[#202124] shadow-2xl">
    <div className="flex items-center gap-3 border-b border-[#3c4043] bg-[#292a2d] px-4 py-3"><b className="text-xs">{scopeName} · {phase==='filter'?'FILTER & PROCESSING STACK':'LOGIC SERVICE STACK'}</b><span className="text-[8px] text-[#80868b]">{phase==='filter'?'Sequential Image Processing Service chain':'Information extraction service chain'}</span><button className="cv-icon ml-auto" onClick={onClose}><X size={13}/></button></div>
    <div className="grid min-h-0 flex-1 grid-cols-[430px_1fr]">
      <div className="overflow-y-auto border-r border-[#3c4043] p-4"><div className="flex gap-2"><select className="cv-field flex-1" value={choice} onChange={e=>setChoice(e.target.value)}><option value="">Choose service…</option>{candidates.map(s=><option key={s.service_id} value={s.service_id}>{s.name} · {s.lab_type}</option>)}</select><button className="cv-btn" onClick={add} disabled={!choice}><Plus size={11}/>Add</button></div><div className="mt-3 space-y-2">{list.map((b,i)=>{const svc=services.find(s=>s.service_id===b.service_id);return <div key={b.binding_id} className="rounded border border-[#3c4043] bg-[#242528] p-2"><div className="flex items-center gap-2"><input type="checkbox" checked={b.enabled} onChange={e=>patch(i,{enabled:e.target.checked})}/><div className="min-w-0 flex-1"><b className="block truncate">{svc?.name??b.service_id}</b><div className="truncate text-[7px] text-[#80868b]">{b.service_id}</div></div><button onClick={()=>move(i,-1)}><ArrowUp size={10}/></button><button onClick={()=>move(i,1)}><ArrowDown size={10}/></button><button className="text-[#f28b82]" onClick={()=>setList(list.filter((_,x)=>x!==i))}><Trash2 size={10}/></button></div>{phase==='logic'?<label className="mt-2 block">Alias<input className="cv-field" value={b.alias} onChange={e=>patch(i,{alias:e.target.value})}/></label>:null}</div>})}</div>{phase==='filter'?<button className="cv-btn mt-4 w-full border-[#c58af9] text-[#c58af9]" onClick={()=>void openDebug()} disabled={!onDebugPreview||busy}><Bug size={11}/>{busy?'Preparing debug…':'Preview Stack in Debug Workspace'}</button>:null}</div>
      <div className="min-h-0 overflow-y-auto p-4"><div className="mb-3 text-[9px] font-black text-[#9aa0a6]">{phase==='filter'?'STACK CONTRACT':'LOGIC CONTRACT'}</div>{phase==='filter'?<div className="space-y-3 text-[8px] leading-5 text-[#9aa0a6]"><div className="rounded border border-[#3c4043] bg-[#242528] p-3">Services execute from top to bottom. Each stage receives the previous stage image and must expose an image-compatible output.</div><div className="rounded border border-[#3c4043] bg-[#242528] p-3">The old embedded Filter Debug View has been removed. <b className="text-[#c58af9]">Debug Workspace</b> is now the single place for stage-by-stage image inspection, timing, before/after navigation and lazy artifact loading.</div><div className="rounded border border-dashed border-[#5f6368] p-3">Tip: configure the stack here, then use <b>Preview Stack in Debug Workspace</b>. The preview does not require a full inspection cycle.</div></div>:<div className="space-y-3">{list.map((b,i)=>{const svc=services.find(s=>s.service_id===b.service_id);return <div key={b.binding_id} className="rounded border border-[#3c4043] bg-[#242528] p-3"><b>{b.alias||`logic_${i+1}`} · {svc?.name}</b><div className="mt-2 flex flex-wrap gap-1">{Object.entries(svc?.outputs??{}).map(([name,p]:any)=><span key={name} className="rounded bg-[#35363a] px-2 py-1 text-[7px] text-[#8ab4f8]">{name}:{p.type}</span>)}</div></div>})}</div>}</div>
    </div>
  </div></div>;
};
