import { useEffect, useState } from 'react';
import { ListTree, X } from 'lucide-react';
import type { DataBlockArtifact, SamplingArtifact } from './types';
import { ArtifactDataView, FeatureBars, LineChart } from './SamplingVisuals';

const explanations:Record<string,string>={
  mean:'Mean is the average value. It describes the center/overall brightness of the sampled distribution.',
  std:'Standard deviation describes spread. Small STD means values are similar; large STD means strong variation.',
  min:'Minimum is the smallest observed sample value.',max:'Maximum is the largest observed sample value.',
  p05:'5th percentile: 5% of values are below this level.',p50:'Median: half of values are below and half above.',p95:'95th percentile: only 5% of values are above.',
  entropy_norm:'Normalized entropy describes distribution complexity/unpredictability.',
};

const BlockCard=({block,onClick}:{block:DataBlockArtifact;onClick?:()=>void})=><button onClick={onClick} className="rounded border border-[#5f6368] bg-[#292a2d] p-2 text-left hover:border-[#8ab4f8]"><div className="text-[9px] font-black text-[#d2e3fc]">{block.label}</div><div className="mt-1 text-[8px] text-[#9aa0a6]">{block.kind} · [{block.shape.join('×')}] · {block.channel}</div><div className="mt-1 text-[8px] text-[#80868b]">{block.description}</div></button>;

export const ArtifactInspectorModal=({title,artifact,previewUrl,sourceUrl,onClose,onFFTReconstruct}:{title:string;artifact:SamplingArtifact|null;previewUrl:string|null;sourceUrl:string|null;onClose:()=>void;onFFTReconstruct?:(params:Record<string,any>)=>Promise<string|null>})=>{
  const [selectedBlock,setSelectedBlock]=useState<DataBlockArtifact|null>(null); const [reconUrl,setReconUrl]=useState<string|null>(null); const [mode,setMode]=useState<'radial'|'angular'|'single'>('radial'); const [center,setCenter]=useState(0.25); const [width,setWidth]=useState(0.08); const [angle,setAngle]=useState(45);
  useEffect(()=>()=>{if(reconUrl)URL.revokeObjectURL(reconUrl);},[reconUrl]);
  const blocks=(artifact as any)?.type==='data_block_set'?((artifact as any).blocks??[]) as DataBlockArtifact[]:[];
  const spectrum=(artifact as any)?.type==='spectrum_2d'?artifact as any:null;
  const histogram=(artifact as any)?.type==='histogram_1d'?artifact as any:null;
  const feature=(artifact as any)?.type==='feature_vector'?artifact as any:null;
  const runRecon=async()=>{if(!onFFTReconstruct)return;const next=await onFFTReconstruct(mode==='radial'?{mode,center,width}:mode==='angular'?{mode,angle_deg:angle,angle_width_deg:15}:{mode,fx:0.2,fy:0.15});if(next){if(reconUrl)URL.revokeObjectURL(reconUrl);setReconUrl(next);}};
  return <div className="fixed inset-0 z-[160] flex items-center justify-center bg-black/80 p-4"><div className="flex h-[91vh] w-[96vw] max-w-[1800px] flex-col overflow-hidden rounded-xl border border-[#5f6368] bg-[#202124]"><header className="flex h-13 items-center gap-3 border-b border-[#3c4043] bg-[#292a2d] px-4"><ListTree size={15} className="text-[#8ab4f8]"/><div><div className="text-[8px] font-black uppercase tracking-[.2em] text-[#8ab4f8]">Typed Artifact Inspector</div><div className="text-xs font-bold">{title} · <span className="font-mono text-[#9aa0a6]">{(artifact as any)?.type}</span></div></div><button onClick={onClose} className="ml-auto p-2"><X size={17}/></button></header>
    <main className="min-h-0 flex-1 overflow-auto p-3">
      {blocks.length?<div className="grid h-full grid-cols-[360px_minmax(0,1fr)] gap-3"><div className="overflow-auto"><div className="mb-2 text-[9px] font-black text-[#8ab4f8]">SEMANTIC DATA BLOCKS · {blocks.length}</div><div className="space-y-1">{blocks.map((b)=><BlockCard key={b.block_id} block={b} onClick={()=>setSelectedBlock(b)}/>)}</div></div><div className="rounded border border-[#3c4043] bg-[#171717] p-3">{selectedBlock?<><div className="text-sm font-black">{selectedBlock.label}</div><div className="mt-1 text-[9px] text-[#9aa0a6]">shape [{selectedBlock.shape.join('×')}] · source {selectedBlock.source_element} · {selectedBlock.channel}</div><div className="mt-3 h-[70%]"><LineChart series={[selectedBlock.values]} labels={[selectedBlock.kind]}/></div><pre className="mt-2 text-[8px] text-[#80868b]">{JSON.stringify(selectedBlock.metadata??{},null,2)}</pre></>:<div className="flex h-full items-center justify-center text-[#5f6368]">Choose a Data Block to inspect its values and meaning.</div>}</div></div>:null}
      {spectrum?<div className="grid h-full grid-cols-3 grid-rows-[minmax(0,1fr)_230px] gap-2"><div className="rounded border border-[#3c4043] bg-black p-2"><div className="text-[8px] font-black text-[#9aa0a6]">ORIGINAL / SOURCE</div>{sourceUrl?<img src={sourceUrl} className="h-[calc(100%-18px)] w-full object-contain"/>:null}</div><div className="rounded border border-[#3c4043] bg-black p-2"><div className="text-[8px] font-black text-[#9aa0a6]">FOURIER MAP</div>{previewUrl?<img src={previewUrl} className="h-[calc(100%-18px)] w-full object-contain"/>:null}</div><div className="rounded border border-[#3c4043] bg-black p-2"><div className="text-[8px] font-black text-[#9aa0a6]">SELECTED FREQUENCY RECONSTRUCTION</div>{reconUrl?<img src={reconUrl} className="h-[calc(100%-18px)] w-full object-contain"/>:<div className="flex h-full items-center justify-center px-5 text-center text-[10px] text-[#5f6368]">Select a band/sector then reconstruct. Each global FFT coefficient is a sinusoidal wave spanning the whole image.</div>}</div><div className="rounded border border-[#3c4043] bg-[#292a2d] p-2"><LineChart series={[spectrum.metadata?.radial_energy??[]]} labels={['radial energy']}/></div><div className="rounded border border-[#3c4043] bg-[#292a2d] p-2"><LineChart series={[spectrum.metadata?.angular_energy??[]]} labels={['angular energy']}/></div><div className="rounded border border-[#3c4043] bg-[#292a2d] p-3"><div className="flex gap-1">{(['radial','angular','single'] as const).map((m)=><button key={m} onClick={()=>setMode(m)} className={`rounded px-2 py-1 text-[8px] ${mode===m?'bg-[#174ea6]':'bg-[#202124]'}`}>{m}</button>)}</div>{mode==='radial'?<><label className="mt-2 block text-[8px]">Frequency radius {center.toFixed(2)}<input type="range" min="0" max="1" step="0.01" value={center} onChange={(e)=>setCenter(Number(e.target.value))} className="w-full"/></label><label className="block text-[8px]">Band width {width.toFixed(2)}<input type="range" min="0.01" max="0.5" step="0.01" value={width} onChange={(e)=>setWidth(Number(e.target.value))} className="w-full"/></label></>:mode==='angular'?<label className="mt-2 block text-[8px]">Orientation sector {angle.toFixed(0)}°<input type="range" min="0" max="180" step="1" value={angle} onChange={(e)=>setAngle(Number(e.target.value))} className="w-full"/></label>:<div className="mt-2 text-[8px] text-[#9aa0a6]">Single mode reconstructs one conjugate frequency pair to show the sinusoidal wave it contributes.</div>}<button onClick={()=>void runRecon()} className="mt-2 rounded border border-[#8ab4f8] bg-[#174ea6] px-2 py-1 text-[8px] font-black">Inverse FFT visualization</button><div className="mt-2 text-[8px] text-[#80868b]">For WHERE-frequency localization, use future Local FFT / STFT / Gabor tools; global FFT mainly answers WHAT frequencies exist.</div></div></div>:null}
      {histogram?<div className="grid h-full grid-cols-[minmax(0,1fr)_330px] gap-3"><LineChart series={[histogram.values??[]]} labels={[`${histogram.channel} histogram`]}/><div className="rounded border border-[#3c4043] bg-[#292a2d] p-3 text-[9px]"><div className="font-black text-[#8ab4f8]">Histogram</div><p className="mt-2 text-[#bdc1c6]">A histogram counts how many samples fall into each value range. More bins give more detail but also a larger/noisier representation.</p><div className="mt-3">Bins: <b>{histogram.values?.length}</b></div><div>Normalized: <b>{String(histogram.normalized)}</b></div></div></div>:null}
      {feature&&!spectrum?<div className="grid h-full grid-cols-[minmax(0,1fr)_360px] gap-3"><FeatureBars values={feature.values??[]} names={feature.names??[]}/><div className="overflow-auto rounded border border-[#3c4043] bg-[#292a2d] p-3"><div className="font-black text-[9px] text-[#8ab4f8]">WHAT DO THESE NUMBERS MEAN?</div>{(feature.names??[]).map((name:string,i:number)=><div key={name} className="mt-2 border-t border-[#3c4043] pt-2 text-[8px]"><div className="font-mono text-[#d2e3fc]">{name} = {Number(feature.values?.[i]??0).toPrecision(5)}</div><div className="mt-1 text-[#9aa0a6]">{explanations[name]??'Named numerical descriptor. Inspect the operator guide for its exact construction.'}</div></div>)}</div></div>:null}
      {!blocks.length&&!spectrum&&!histogram&&!feature&&['image','binary_mask'].includes((artifact as any)?.type) && previewUrl ? <div className="flex h-full items-center justify-center bg-black"><img src={previewUrl} className="max-h-full max-w-full object-contain"/></div> : null}
      {!blocks.length&&!spectrum&&!histogram&&!feature&&!['image','binary_mask'].includes((artifact as any)?.type)?<div className="h-full"><ArtifactDataView artifact={artifact}/></div>:null}
    </main>
  </div></div>;
};
