import { HelpCircle, X } from 'lucide-react';
import type { SamplingParameterManifest } from './types';

const examples:Record<string,{title:string;body:string}>={
  histogram_bins:{title:'Histogram bins',body:'Bins divide the value range into buckets. 4 bins are coarse; 32 bins preserve more distribution detail but create more dimensions and can be noisier.'},
  include_std:{title:'Standard deviation',body:'STD measures spread. [50,50,50] has STD≈0; [10,50,90] has a much larger STD even though the mean can be similar.'},
  sample_step:{title:'Sampling step',body:'Step=1 reads every available sample; Step=4 keeps roughly one sample every four pixels. Larger steps reduce dimension and computation.'},
  sample_count:{title:'Fixed sample count',body:'Every ray/ring/patch is resampled to the same number of values. This is useful when AI input shape must stay constant.'},
  layout:{title:'Data Layout Composer',body:'Data Blocks stay named and inspectable. You can concatenate them into one vector or stack them into a matrix. Ordering can be element-major, channel-major, or a custom order.'},
};
export const SamplingParameterHelpModal=({title,spec,topic,onClose}:{title:string;spec?:SamplingParameterManifest;topic?:string;onClose:()=>void})=>{const key=topic??'';const preset=examples[key]??examples[Object.keys(examples).find((k)=>title.toLowerCase().includes(k.replace('_',' ')))??''];return <div className="fixed inset-0 z-[180] flex items-center justify-center bg-black/75 p-4"><div className="w-full max-w-2xl rounded-xl border border-[#5f6368] bg-[#292a2d] p-4"><div className="flex items-center gap-2"><HelpCircle size={16} className="text-[#8ab4f8]"/><div className="text-sm font-black">{preset?.title??title}</div><button onClick={onClose} className="ml-auto"><X size={16}/></button></div><p className="mt-3 text-[11px] leading-5 text-[#bdc1c6]">{preset?.body??spec?.description??'This parameter controls how data is sampled or represented.'}</p>{spec?<div className="mt-3 rounded border border-[#3c4043] bg-[#202124] p-3 text-[9px] text-[#9aa0a6]"><div>Type: <b>{spec.type}</b></div><div>Default: <b>{String(spec.default)}</b></div>{spec.min!=null||spec.max!=null?<div>Range: {String(spec.min??'−∞')} .. {String(spec.max??'∞')}</div>:null}{spec.choices?.length?<div>Choices: {spec.choices.map(String).join(', ')}</div>:null}</div>:null}</div></div>;};
