import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Box, Cpu, Image as ImageIcon, Loader2, Play, Save, Sparkles } from 'lucide-react';
import { LabServiceAPI, type LabServiceDefinition } from '../api/labServiceApi';
import { VisionAppAPI, type LocatedRoi, type MasterRoi, type NormalizedRect, type VisionProgramDefinition, type VisionRunResult } from '../api/visionAppApi';
import { VisionViewport } from '../components/ComputerVision/VisionViewport';
import { IotModulePanel } from '../components/ComputerVision/IotModulePanel';
import { MasterSamplePanel } from '../components/ComputerVision/MasterSamplePanel';
import { WorkingModulePanel } from '../components/ComputerVision/WorkingModulePanel';
import '../components/ComputerVision/ComputerVision.css';

type ModuleKey='iot'|'master'|'working';
const roiDefault=(rect:NormalizedRect,index:number):MasterRoi=>({roi_id:`roi_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,name:`Station ${index+1}`,rect,enabled:true,search:{method:'manual',blur_kernel:9,template_threshold:.65,geometry:{enabled:true,search_margin_px:80,max_shift_px:120}}});

export const ComputerVisionPage=()=>{
 const navigate=useNavigate();const [module,setModule]=useState<ModuleKey>('master');const [programs,setPrograms]=useState<(VisionProgramDefinition&{master_exists?:boolean})[]>([]);const [program,setProgram]=useState<VisionProgramDefinition|null>(null);const [services,setServices]=useState<LabServiceDefinition[]>([]);const [masterUrl,setMasterUrl]=useState<string|null>(null);const [testFile,setTestFile]=useState<File|null>(null);const [testUrl,setTestUrl]=useState<string|null>(null);const [located,setLocated]=useState<LocatedRoi[]>([]);const [run,setRun]=useState<VisionRunResult|null>(null);const [selectedRoi,setSelectedRoi]=useState<string|null>(null);const [drawMode,setDrawMode]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [triggerState,setTriggerState]=useState<boolean|null>(null);
 const refreshList=async(selectId?:string)=>{const list=await VisionAppAPI.listPrograms();setPrograms(list);const id=selectId??program?.program_id??list[0]?.program_id;if(id){const loaded=await VisionAppAPI.getProgram(id);setProgram(loaded.program);if(loaded.master_exists){const blob=await VisionAppAPI.masterPreview(id);const url=URL.createObjectURL(blob);setMasterUrl(old=>{if(old)URL.revokeObjectURL(old);return url;});}else setMasterUrl(old=>{if(old)URL.revokeObjectURL(old);return null;});}};
 useEffect(()=>{void(async()=>{try{setBusy(true);const [list,svc]=await Promise.all([VisionAppAPI.listPrograms(),LabServiceAPI.list()]);setServices(svc);if(list.length){setPrograms(list);const loaded=await VisionAppAPI.getProgram(list[0].program_id);setProgram(loaded.program);if(loaded.master_exists){const blob=await VisionAppAPI.masterPreview(list[0].program_id);setMasterUrl(URL.createObjectURL(blob));}}else{const created=await VisionAppAPI.newProgram('Vision Program');setProgram(created.program);setPrograms([{...created.program,master_exists:false}]);}}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Computer Vision init failed');}finally{setBusy(false);}})();return()=>{if(masterUrl)URL.revokeObjectURL(masterUrl);if(testUrl)URL.revokeObjectURL(testUrl);};},[]);
 const patch=(next:VisionProgramDefinition)=>setProgram(next);
 const save=async()=>{if(!program)return;try{setBusy(true);const saved=await VisionAppAPI.saveProgram(program);setProgram(saved);await refreshList(saved.program_id);}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Save failed');}finally{setBusy(false);}};
 const create=async()=>{const name=window.prompt('New Vision Program name','Vision Program');if(!name)return;try{setBusy(true);const created=await VisionAppAPI.newProgram(name);await refreshList(created.program.program_id);}catch(e:any){setError(e?.message||'Create failed');}finally{setBusy(false);}};
 const switchProgram=async(id:string)=>{try{setBusy(true);const loaded=await VisionAppAPI.getProgram(id);setProgram(loaded.program);setLocated([]);setRun(null);setSelectedRoi(null);if(loaded.master_exists){const blob=await VisionAppAPI.masterPreview(id);const url=URL.createObjectURL(blob);setMasterUrl(old=>{if(old)URL.revokeObjectURL(old);return url;});}else setMasterUrl(old=>{if(old)URL.revokeObjectURL(old);return null;});}catch(e:any){setError(e?.message||'Load failed');}finally{setBusy(false);}};
 const uploadMaster=async(file:File)=>{if(!program)return;try{setBusy(true);await VisionAppAPI.uploadMaster(program.program_id,file);const loaded=await VisionAppAPI.getProgram(program.program_id);setProgram(loaded.program);const blob=await VisionAppAPI.masterPreview(program.program_id);const url=URL.createObjectURL(blob);setMasterUrl(old=>{if(old)URL.revokeObjectURL(old);return url;});}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Master upload failed');}finally{setBusy(false);}};
 const addRoi=(rect:NormalizedRect)=>{if(!program)return;const roi=roiDefault(rect,program.master.rois.length);patch({...program,master:{...program.master,rois:[...program.master.rois,roi]}});setSelectedRoi(roi.roi_id);setDrawMode(false);};
 const updateRoi=(roi:MasterRoi)=>{if(!program)return;patch({...program,master:{...program.master,rois:program.master.rois.map(r=>r.roi_id===roi.roi_id?roi:r)}});};
 const removeRoi=(id:string)=>{if(!program)return;const station={...program.working.station_services};delete station[id];patch({...program,master:{...program.master,rois:program.master.rois.filter(r=>r.roi_id!==id)},working:{...program.working,station_services:station}});if(selectedRoi===id)setSelectedRoi(null);};
 const chooseTest=(file:File|null)=>{setTestFile(file);setLocated([]);setRun(null);setTestUrl(old=>{if(old)URL.revokeObjectURL(old);return file?URL.createObjectURL(file):null;});};
 const locate=async()=>{if(!program||!testFile)return;try{setBusy(true);setLocated(await VisionAppAPI.locateRois(program.program_id,testFile));}catch(e:any){setError(e?.response?.data?.detail||e?.message||'ROI locate failed');}finally{setBusy(false);}};
 const runTest=async()=>{if(!program||!testFile)return;try{setBusy(true);await VisionAppAPI.saveProgram(program);const result=await VisionAppAPI.runTest(program.program_id,testFile);setRun(result);setLocated(result.located_rois);}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Working test failed');}finally{setBusy(false);}};
 const readTrigger=async()=>{if(!program)return;try{setBusy(true);setTriggerState(await VisionAppAPI.readTrigger(program.program_id));}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Trigger read failed');}finally{setBusy(false);}};
 const pulse=async(result:'ok'|'ng')=>{if(!program)return;try{setBusy(true);await VisionAppAPI.pulse(program.program_id,result,program.io.pulse_seconds);}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Output pulse failed');}finally{setBusy(false);}};
 const viewportUrl=module==='working'?(testUrl??masterUrl):masterUrl;const viewportRois=module==='working'?[]:(program?.master.rois??[]);const locatedForView=module==='working'?located:[];
 if(!program)return <div className="flex h-screen items-center justify-center bg-[#202124] text-[#e8eaed]">{busy?<Loader2 className="animate-spin"/>:'No program'}</div>;
 return <div className="flex h-screen w-screen flex-col overflow-hidden bg-[#202124] text-[#e8eaed]">
  <header className="flex h-14 shrink-0 items-center gap-3 border-b border-[#3c4043] bg-[#292a2d] px-3"><button onClick={()=>navigate('/')} className="cv-btn"><ArrowLeft size={12}/></button><Sparkles size={17} className="text-[#c58af9]"/><div><div className="text-xs font-black tracking-[.15em]">COMPUTER VISION</div><div className="text-[8px] text-[#80868b]">I/O trigger → Master Sample / ROI location → Global + Station working services → OK / NG</div></div><select value={program.program_id} onChange={e=>void switchProgram(e.target.value)} className="ml-4 w-[220px] rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[9px]">{programs.map(p=><option key={p.program_id} value={p.program_id}>{p.name}</option>)}</select><button onClick={()=>void create()} className="cv-btn">New</button><input value={program.name} onChange={e=>patch({...program,name:e.target.value})} className="w-[220px] rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[9px]"/><button onClick={()=>void save()} className="cv-btn border-[#81c995] text-[#81c995]"><Save size={11}/>Save Program</button><div className="ml-auto flex items-center gap-2"><label className="cv-btn cursor-pointer"><ImageIcon size={11}/>{testFile?.name??'Test image'}<input type="file" accept="image/*" className="hidden" onChange={e=>chooseTest(e.target.files?.[0]??null)}/></label><button disabled={!testFile||busy} onClick={()=>void locate()} className="cv-btn">Locate ROIs</button><button disabled={!testFile||busy} onClick={()=>void runTest()} className="cv-btn border-[#8ab4f8] bg-[#174ea6]"><Play size={11}/>{busy?'Working…':'Run Test'}</button></div></header>
  {error?<div className="shrink-0 bg-[#5f2120] px-3 py-1 text-[9px] text-[#f28b82]">{error}<button onClick={()=>setError('')} className="ml-3 font-black">dismiss</button></div>:null}
  <main className="flex min-h-0 flex-1"><aside className="w-[150px] shrink-0 border-r border-[#3c4043] bg-[#292a2d] p-2"><div className="mb-2 text-[8px] font-black text-[#80868b]">PROGRAM MODULES</div>{([{key:'iot',label:'IOT',icon:Cpu},{key:'master',label:'Master Sample',icon:ImageIcon},{key:'working',label:'Working',icon:Box}] as any[]).map(item=>{const Icon=item.icon;return <button key={item.key} onClick={()=>setModule(item.key)} className={`mb-2 flex w-full flex-col items-center gap-2 rounded-lg border px-2 py-4 text-[9px] font-black ${module===item.key?'border-[#c58af9] bg-[#3b3150] text-white':'border-[#3c4043] bg-[#242528] text-[#9aa0a6]'}`}><Icon size={18}/>{item.label}</button>;})}<div className="mt-4 rounded border border-[#3c4043] bg-[#202124] p-2 text-[7px] leading-4 text-[#80868b]">Frame v1 keeps LABs frozen. Computer Vision orchestrates deployed services rather than duplicating their internal algorithms.</div></aside>
   <section className="min-w-0 flex-1"><VisionViewport imageUrl={viewportUrl} rois={viewportRois} located={locatedForView} selectedId={selectedRoi} drawMode={module==='master'&&drawMode} onSelect={setSelectedRoi} onDraw={addRoi}/>{run?<div className={`absolute bottom-4 left-[180px] rounded-lg border px-3 py-2 text-[9px] font-black shadow-xl ${run.overall_ok?'border-[#81c995] bg-[#1e3828] text-[#81c995]':'border-[#f28b82] bg-[#5f2120] text-[#f28b82]'}`}>TEST RESULT: {run.overall_ok?'OK':'NG'} · {run.stations.length} station(s) · {run.total_ms.toFixed(1)} ms</div>:null}</section>
   <aside className="w-[460px] shrink-0 overflow-hidden border-l border-[#3c4043] bg-[#292a2d]"><div className="border-b border-[#3c4043] px-3 py-2 text-[9px] font-black uppercase text-[#c58af9]">{module==='iot'?'IOT / Trigger & Result':module==='master'?'Master Sample / ROI Search':'Working / Services & Decision'}</div><div className="h-[calc(100%-32px)] overflow-y-auto">{module==='iot'?<IotModulePanel config={program.io} onChange={io=>patch({...program,io})} onRead={()=>void readTrigger()} onPulse={result=>void pulse(result)} triggerState={triggerState} busy={busy}/>:module==='master'?<MasterSamplePanel rois={program.master.rois} selectedId={selectedRoi} drawMode={drawMode} onDrawMode={setDrawMode} onSelect={setSelectedRoi} onChange={updateRoi} onRemove={removeRoi} onUpload={file=>void uploadMaster(file)}/>:<WorkingModulePanel services={services} rois={program.master.rois} globalBindings={program.working.global_services} stationBindings={program.working.station_services} onGlobal={global_services=>patch({...program,working:{...program.working,global_services}})} onStations={station_services=>patch({...program,working:{...program.working,station_services}})} onSelectStation={setSelectedRoi}/>}</div></aside>
  </main><footer className="flex h-7 shrink-0 items-center gap-4 border-t border-[#3c4043] bg-[#242528] px-3 text-[8px] text-[#80868b]"><span>Vision App frame v1</span><span>Master ROIs: {program.master.rois.length}</span><span>Global services: {program.working.global_services.length}</span><span>Station bindings: {Object.values(program.working.station_services).reduce((n,a)=>n+a.length,0)}</span><span className="ml-auto">Program ID: {program.program_id}</span></footer>
 </div>;
};
