import { useEffect, useMemo, useState } from 'react';
import { ListTree, X } from 'lucide-react';
import type { DataBlockArtifact, SamplingArtifact } from './types';
import { ArtifactDataView, FeatureBars, LineChart } from './SamplingVisuals';

const explanations:Record<string,string>={mean:'Average / center of the distribution.',std:'Spread around the mean. Larger STD means stronger variation.',min:'Smallest observed value.',max:'Largest observed value.',p05:'5th percentile.',p50:'Median / 50th percentile.',p95:'95th percentile.',entropy_norm:'Normalized distribution complexity / unpredictability.'};
const BlockCard=({block,onClick}:{block:DataBlockArtifact;onClick?:()=>void})=><button onClick={onClick} className="rounded border border-[#5f6368] bg-[#292a2d] p-2 text-left hover:border-[#8ab4f8]"><div className="text-[9px] font-black text-[#d2e3fc]">{block.label}</div><div className="mt-1 text-[8px] text-[#9aa0a6]">{block.kind} · [{block.shape.join('×')}] · {block.channel}</div><div className="mt-1 text-[8px] text-[#80868b]">{block.description}</div></button>;

export const ArtifactInspectorModal=({title,artifact,previewUrl,sourceUrl,onClose,onFFTReconstruct}:{title:string;artifact:SamplingArtifact|null;previewUrl:string|null;sourceUrl:string|null;onClose:()=>void;onFFTReconstruct?:(params:Record<string,any>)=>Promise<string|null>})=>{
 const [selectedBlock,setSelectedBlock]=useState<DataBlockArtifact|null>(null);const [reconUrl,setReconUrl]=useState<string|null>(null);const [mode,setMode]=useState<'radial'|'angular'|'single'>('radial');const [center,setCenter]=useState(.25);const [width,setWidth]=useState(.08);const [angle,setAngle]=useState(45);
 useEffect(()=>()=>{if(reconUrl)URL.revokeObjectURL(reconUrl);},[reconUrl]);
 const a:any=artifact;const blocks=a?.type==='data_block_set'?(a.blocks??[]) as DataBlockArtifact[]:[];const spectrum=a?.type==='spectrum_2d'?a:null;const histogram=a?.type==='histogram_1d'?a:null;const feature=a?.type==='feature_vector'?a:null;const matrix=a?.type==='feature_matrix'?a:null;const radial=useMemo(()=>Boolean(feature?.names?.length)&&feature.names.every((n:string)=>n.startsWith('radial_band_')),[feature]);const angular=useMemo(()=>Boolean(feature?.names?.length)&&feature.names.every((n:string)=>n.startsWith('angle_')),[feature]);
 const runRecon=async()=>{if(!onFFTReconstruct)return;const next=await onFFTReconstruct(mode==='radial'?{mode,center,width}:mode==='angular'?{mode,angle_deg:angle,angle_width_deg:15}:{mode,fx:.2,fy:.15});if(next){if(reconUrl)URL.revokeObjectURL(reconUrl);setReconUrl(next);}};
 return <div className="fixed inset-0 z-[160] flex items-center justify-center bg-black/80 p-4"><div className="flex h-[91vh] w-[96vw] max-w-[1800px] flex-col overflow-hidden rounded-xl border border-[#5f6368] bg-[#202124]"><header className="flex h-13 items-center gap-3 border-b border-[#3c4043] bg-[#292a2d] px-4"><ListTree size={15} className="text-[#8ab4f8]"/><div><div className="text-[8px] font-black uppercase tracking-[.2em] text-[#8ab4f8]">Typed Artifact Inspector</div><div className="text-xs font-bold">{title} · <span className="font-mono text-[#9aa0a6]">{a?.type}</span></div></div><button onClick={onClose} className="ml-auto p-2"><X size={17}/></button></header><main className="min-h-0 flex-1 overflow-auto p-3">
  {blocks.length?<div className="grid h-full grid-cols-[360px_minmax(0,1fr)] gap-3"><div className="overflow-auto"><div className="mb-2 text-[9px] font-black text-[#8ab4f8]">SEMANTIC DATA BLOCKS · {blocks.length}</div><div className="space-y-1">{blocks.map((b)=><BlockCard key={b.block_id} block={b} onClick={()=>setSelectedBlock(b)}/>)}</div></div><div className="rounded border border-[#3c4043] bg-[#171717] p-3">{selectedBlock?<><div className="text-sm font-black">{selectedBlock.label}</div><div className="mt-1 text-[9px] text-[#9aa0a6]">shape [{selectedBlock.shape.join('×')}] · source {selectedBlock.source_element} · {selectedBlock.channel}</div><div className="mt-3 h-[70%]"><LineChart series={[selectedBlock.values]} labels={[selectedBlock.kind]}/></div><pre className="mt-2 text-[8px] text-[#80868b]">{JSON.stringify(selectedBlock.metadata??{},null,2)}</pre></>:<div className="flex h-full items-center justify-center text-[#5f6368]">Choose a Data Block to inspect real values and meaning.</div>}</div></div>:null}
  {spectrum?<div className="grid h-full grid-cols-3 grid-rows-[minmax(0,1fr)_230px] gap-2"><div className="rounded border border-[#3c4043] bg-black p-2"><div className="text-[8px] font-black text-[#9aa0a6]">ORIGINAL / SOURCE CONTEXT</div>{sourceUrl?<img src={sourceUrl} className="h-[calc(100%-18px)] w-full object-contain"/>:null}</div><div className="rounded border border-[#3c4043] bg-black p-2"><div className="text-[8px] font-black text-[#9aa0a6]">FOURIER ENERGY MAP</div>{previewUrl?<img src={previewUrl} className="h-[calc(100%-18px)] w-full object-contain"/>:null}</div><div className="rounded border border-[#3c4043] bg-black p-2"><div className="text-[8px] font-black text-[#9aa0a6]">SELECTED WAVES → INVERSE FFT</div>{reconUrl?<img src={reconUrl} className="h-[calc(100%-18px)] w-full object-contain"/>:<div className="flex h-full items-center justify-center px-5 text-center text-[10px] text-[#5f6368]">Select a radial band / orientation sector / frequency pair and reconstruct only those waves.</div>}</div><div className="rounded border border-[#3c4043] bg-[#292a2d] p-2"><LineChart series={[spectrum.metadata?.radial_energy??[]]} labels={['radial energy · low → high']}/></div><div className="rounded border border-[#3c4043] bg-[#292a2d] p-2"><LineChart series={[spectrum.metadata?.angular_energy??[]]} labels={['angular energy · 0 → 180°']}/></div><div className="rounded border border-[#3c4043] bg-[#292a2d] p-3"><div className="flex gap-1">{(['radial','angular','single'] as const).map((m)=><button key={m} onClick={()=>setMode(m)} className={`rounded px-2 py-1 text-[8px] ${mode===m?'bg-[#174ea6]':'bg-[#202124]'}`}>{m}</button>)}</div>{mode==='radial'?<><label className="mt-2 block text-[8px]">Frequency radius {center.toFixed(2)}<input type="range" min="0" max="1" step=".01" value={center} onChange={(e)=>setCenter(Number(e.target.value))} className="w-full"/></label><label className="block text-[8px]">Band width {width.toFixed(2)}<input type="range" min=".01" max=".5" step=".01" value={width} onChange={(e)=>setWidth(Number(e.target.value))} className="w-full"/></label></>:mode==='angular'?<label className="mt-2 block text-[8px]">Orientation sector {angle.toFixed(0)}°<input type="range" min="0" max="180" step="1" value={angle} onChange={(e)=>setAngle(Number(e.target.value))} className="w-full"/></label>:<div className="mt-2 text-[8px] text-[#9aa0a6]">One conjugate frequency pair reconstructs a single sinusoidal component spanning the whole image.</div>}<button onClick={()=>void runRecon()} className="mt-2 rounded border border-[#8ab4f8] bg-[#174ea6] px-2 py-1 text-[8px] font-black">Reconstruct selected waves</button><div className="mt-2 text-[8px] leading-4 text-[#80868b]">Global FFT tells WHAT frequencies exist, not WHERE. Use <b>Local FFT Band Energy Map</b> when you need a spatial heatmap of frequency energy.</div></div></div>:null}
  {histogram?<div className="grid h-full grid-cols-[minmax(0,1fr)_360px] gap-3"><LineChart series={[histogram.values??[]]} labels={[`${histogram.channel} histogram`]}/><div className="rounded border border-[#3c4043] bg-[#292a2d] p-4 text-[10px] leading-5"><div className="font-black text-[#8ab4f8]">HISTOGRAM = VALUE DISTRIBUTION</div><div className="mt-3 rounded bg-[#171717] p-3 text-center font-mono text-[#fdd663]">h[b] = count(xᵢ ∈ bin b)</div><p className="mt-3 text-[#bdc1c6]">More bins preserve finer value structure; fewer bins create a smaller, smoother descriptor. Histograms do not preserve pixel location.</p><div className="mt-3">Bins <b>{histogram.values?.length}</b> · normalized <b>{String(histogram.normalized)}</b></div></div></div>:null}
  {feature&&!spectrum?<div className="grid h-full grid-cols-[minmax(0,1fr)_380px] gap-3"><div className="min-h-0">{radial||angular?<LineChart series={[feature.values??[]]} labels={[radial?'radial frequency energy':'angular frequency energy']}/>:feature.metadata?.distribution_histogram?<div className="grid h-full grid-rows-2 gap-2"><FeatureBars values={feature.values??[]} names={feature.names??[]}/><LineChart series={[feature.metadata.distribution_histogram]} labels={['source value distribution']}/></div>:<FeatureBars values={feature.values??[]} names={feature.names??[]}/>}</div><div className="overflow-auto rounded border border-[#3c4043] bg-[#292a2d] p-3"><div className="font-black text-[9px] text-[#8ab4f8]">WHAT DO THESE NUMBERS MEAN?</div>{radial?<p className="mt-2 text-[9px] leading-4 text-[#bdc1c6]">Left bands are coarse/low spatial frequencies; right bands are fine/high frequencies.</p>:null}{angular?<p className="mt-2 text-[9px] leading-4 text-[#bdc1c6]">Peaks indicate dominant frequency orientations. Image-space lines are perpendicular to their strongest Fourier orientation.</p>:null}{(feature.names??[]).map((name:string,i:number)=><div key={name} className="mt-2 border-t border-[#3c4043] pt-2 text-[8px]"><div className="font-mono text-[#d2e3fc]">{name} = {Number(feature.values?.[i]??0).toPrecision(5)}</div><div className="mt-1 text-[#9aa0a6]">{feature.metadata?.formulae?.[name]??explanations[name]??'Named numerical descriptor. Inspect the operator guide for its construction.'}</div></div>)}</div></div>:null}
  {matrix?<div className="grid h-full grid-cols-[minmax(0,1fr)_330px] gap-3"><div className="min-h-0"><ArtifactDataView artifact={artifact}/></div><div className="rounded border border-[#3c4043] bg-[#292a2d] p-4 text-[9px] leading-5"><div className="font-black text-[#c58af9]">MATRIX / HEATMAP</div><p className="mt-2 text-[#bdc1c6]">For Local FFT Band Energy each cell corresponds to one source-image patch. High values tell WHERE the chosen frequency band is strongest.</p><pre className="mt-3 whitespace-pre-wrap text-[8px] text-[#80868b]">{JSON.stringify(matrix.metadata??{},null,2)}</pre></div></div>:null}
  {!blocks.length&&!spectrum&&!histogram&&!feature&&!matrix&&['image','binary_mask'].includes(a?.type)&&previewUrl?<div className="flex h-full items-center justify-center bg-black"><img src={previewUrl} className="max-h-full max-w-full object-contain"/></div>:null}
  {!blocks.length&&!spectrum&&!histogram&&!feature&&!matrix&&!['image','binary_mask'].includes(a?.type)?<div className="h-full"><ArtifactDataView artifact={artifact}/></div>:null}
 </main></div></div>;
};
