import { useEffect, useMemo, useRef, useState } from 'react';
import { Maximize2, Minus, Plus, RotateCcw } from 'lucide-react';
import type { SamplingArtifact } from './types';

const artifactGeometry = (artifact: SamplingArtifact | null): any => {
  if (!artifact) return null;
  if ((artifact as any).type === 'sampling_housing') return (artifact as any).geometry;
  if ((artifact as any).type === 'profile_set' || (artifact as any).type === 'feature_matrix') return (artifact as any).geometry;
  return null;
};
const previewParams=(artifact:any)=>artifact?.metadata?._extractorPreview??artifact?._extractorPreview??{};
const pointCount=(params:any,approxLength=200)=>{const mode=String(params.sample_mode??'count');if(mode==='step')return Math.max(2,Math.min(80,Math.floor(approxLength/Math.max(1,Number(params.sample_step??4)))+1));if(mode==='full')return Math.max(2,Math.min(80,Math.round(approxLength)));return Math.max(2,Math.min(80,Number(params.sample_count??32)));};

export const SamplingCanvas = ({sourceUrl,artifact,artifacts,masterContours,selectedContourId,onSelectContour}:{sourceUrl:string|null;artifact:SamplingArtifact|null;artifacts?:SamplingArtifact[];masterContours?:SamplingArtifact|null;selectedContourId?:number|null;onSelectContour?:(id:number)=>void;}) => {
  const hostRef=useRef<HTMLDivElement|null>(null);const [imageSize,setImageSize]=useState({w:1,h:1});const [fitScale,setFitScale]=useState(1);const [zoom,setZoom]=useState(1);const [pan,setPan]=useState({x:0,y:0});const dragRef=useRef<{x:number;y:number;px:number;py:number}|null>(null);
  const reset=()=>{setZoom(1);setPan({x:0,y:0});};
  useEffect(()=>{const recompute=()=>{const host=hostRef.current;if(!host||imageSize.w<=1||imageSize.h<=1)return;const rect=host.getBoundingClientRect();setFitScale(Math.max(.01,Math.min((rect.width-24)/imageSize.w,(rect.height-24)/imageSize.h)));};recompute();const observer=new ResizeObserver(recompute);if(hostRef.current)observer.observe(hostRef.current);return()=>observer.disconnect();},[imageSize.w,imageSize.h]);
  useEffect(()=>{reset();},[sourceUrl]);
  const contourArtifact=artifact?.type==='contour_set'?artifact as any:null;const master=masterContours?.type==='contour_set'?masterContours as any:null;const resultIds=useMemo(()=>new Set<number>((contourArtifact?.contour_ids??[]).map(Number)),[contourArtifact]);const overlayArtifacts=artifacts?.length?artifacts:(artifact?[artifact]:[]);
  const overlay=<svg viewBox={`0 0 ${imageSize.w} ${imageSize.h}`} className="absolute inset-0 h-full w-full overflow-visible">
    {master?.contours?.map((contour:number[][],index:number)=>{const id=Number(master.contour_ids?.[index]??index),kept=resultIds.has(id),selected=selectedContourId===id;return <polyline key={`master:${id}`} points={contour.map((p)=>`${p[0]},${p[1]}`).join(' ')} fill="none" stroke={selected?'#fdd663':kept?'#81c995':'#80868b'} strokeOpacity={selected?1:kept?.95:.18} strokeWidth={selected?4:kept?2:1} vectorEffect="non-scaling-stroke" pointerEvents="stroke" onClick={(e)=>{e.stopPropagation();onSelectContour?.(id);}}/>;})}
    {!master&&contourArtifact?.contours?.map((contour:number[][],index:number)=>{const id=Number(contourArtifact.contour_ids?.[index]??index),selected=selectedContourId===id;return <polyline key={id} points={contour.map((p)=>`${p[0]},${p[1]}`).join(' ')} fill="none" stroke={selected?'#fdd663':'#81c995'} strokeWidth={selected?4:2} vectorEffect="non-scaling-stroke" pointerEvents="stroke" onClick={(e)=>{e.stopPropagation();onSelectContour?.(id);}}/>;})}
    {artifact?.type==='polyline'?<polyline points={(artifact as any).points.map((p:number[])=>`${p[0]},${p[1]}`).join(' ')} fill="none" stroke="#fdd663" strokeWidth="3" vectorEffect="non-scaling-stroke"/>:null}
    {overlayArtifacts.map((a:any,gi:number)=>{const g=artifactGeometry(a);if(!g)return null;const color=gi%2?'#81c995':'#8ab4f8';const params=previewParams(a);return <g key={`g:${gi}`}>
      {g.kind==='rays'?(g.rays??[]).map((ray:number[],index:number)=>{const x1=ray[0]*imageSize.w,y1=ray[1]*imageSize.h,x2=ray[2]*imageSize.w,y2=ray[3]*imageSize.h;const n=pointCount(params,Math.hypot(x2-x1,y2-y1));return <g key={`r:${index}`}><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={color} strokeWidth="2" vectorEffect="non-scaling-stroke"/>{Array.from({length:n},(_,i)=>{const t=n===1?0:i/(n-1);return <circle key={i} cx={x1+(x2-x1)*t} cy={y1+(y2-y1)*t} r="2.4" fill="#fdd663" vectorEffect="non-scaling-stroke"/>;})}</g>; }):null}
      {g.kind==='rings'?(g.radii??[]).map((radius:number,index:number)=>{const scale=Math.min(imageSize.w,imageSize.h),cx=(g.center?.[0]??.5)*imageSize.w,cy=(g.center?.[1]??.5)*imageSize.h,r=radius*scale,n=pointCount(params,2*Math.PI*r);return <g key={`c:${index}`}><circle cx={cx} cy={cy} r={r} fill="none" stroke={color} strokeWidth="2" vectorEffect="non-scaling-stroke"/>{Array.from({length:n},(_,i)=>{const a=2*Math.PI*i/n;return <circle key={i} cx={cx+Math.cos(a)*r} cy={cy+Math.sin(a)*r} r="2" fill="#fdd663"/>;})}</g>; }):null}
      {g.kind==='ring_grid'?(g.rings??[]).map((ring:any,index:number)=>{const scale=Math.min(imageSize.w,imageSize.h),cx=ring.center[0]*imageSize.w,cy=ring.center[1]*imageSize.h,r=ring.radius*scale,n=pointCount(params,2*Math.PI*r);return <g key={`rg:${index}`}><circle cx={cx} cy={cy} r={r} fill="none" stroke={color} strokeWidth="1.5" vectorEffect="non-scaling-stroke"/>{Array.from({length:Math.min(n,24)},(_,i)=>{const a=2*Math.PI*i/Math.min(n,24);return <circle key={i} cx={cx+Math.cos(a)*r} cy={cy+Math.sin(a)*r} r="1.8" fill="#fdd663"/>;})}</g>; }):null}
      {g.kind==='boxes'?(g.boxes??[]).map((box:number[],index:number)=>{const x=box[0]*imageSize.w,y=box[1]*imageSize.h,w=(box[2]-box[0])*imageSize.w,h=(box[3]-box[1])*imageSize.h;const n=Math.min(7,Math.max(2,Math.round(Math.sqrt(pointCount(params,w*h/Math.max(1,Math.sqrt(w*h)))))));return <g key={`b:${index}`}><rect x={x} y={y} width={w} height={h} fill="none" stroke={color} strokeWidth="1.5" vectorEffect="non-scaling-stroke"/>{Array.from({length:n*n},(_,i)=>{const row=Math.floor(i/n),col=i%n;return <circle key={i} cx={x+(col+.5)*w/n} cy={y+(row+.5)*h/n} r="1.7" fill="#fdd663"/>;})}</g>; }):null}
    </g>;})}
  </svg>;
  return <div ref={hostRef} className="relative h-full w-full overflow-hidden bg-[#111] select-none" onWheel={(e)=>{e.preventDefault();setZoom((v)=>Math.min(20,Math.max(.08,v*(e.deltaY<0?1.12:.89))));}} onMouseDown={(e)=>{if(e.button===0)dragRef.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};}} onMouseMove={(e)=>{const d=dragRef.current;if(d)setPan({x:d.px+e.clientX-d.x,y:d.py+e.clientY-d.y});}} onMouseUp={()=>{dragRef.current=null;}} onMouseLeave={()=>{dragRef.current=null;}} onDoubleClick={reset}>
    {sourceUrl?<div className="absolute left-1/2 top-1/2 origin-center" style={{width:imageSize.w,height:imageSize.h,transform:`translate(-50%, -50%) translate(${pan.x}px, ${pan.y}px) scale(${fitScale*zoom})`}}><img src={sourceUrl} draggable={false} className="absolute inset-0 h-full w-full" onLoad={(e)=>setImageSize({w:Math.max(1,e.currentTarget.naturalWidth),h:Math.max(1,e.currentTarget.naturalHeight)})}/>{overlay}</div>:<div className="absolute inset-0 flex items-center justify-center text-sm text-[#5f6368]">Build the shared Source Board first.</div>}
    <div className="absolute right-3 top-3 flex items-center gap-1 rounded border border-[#3c4043] bg-[#202124]/90 p-1"><button onClick={()=>setZoom((v)=>Math.max(.08,v/1.2))} className="p-1"><Minus size={12}/></button><span className="min-w-[54px] text-center font-mono text-[9px] text-[#8ab4f8]">{Math.round(zoom*100)}%</span><button onClick={()=>setZoom((v)=>Math.min(20,v*1.2))} className="p-1"><Plus size={12}/></button><button onClick={reset} className="p-1"><RotateCcw size={12}/></button><Maximize2 size={11} className="mx-1 text-[#5f6368]"/></div><div className="absolute bottom-2 left-2 rounded bg-[#202124]/85 px-2 py-1 text-[8px] text-[#80868b]">Yellow dots = actual sampling density preview · wheel zoom · drag pan · double-click fit</div>
  </div>;
};
