import { Eye, EyeOff, HelpCircle, ScanLine, Trash2 } from 'lucide-react';
import type { SpatialSamplingUnit, SamplingParameterManifest, DataBlockArtifact } from './types';
import { DataLayoutComposer } from './DataLayoutComposer';

const Param = ({name,spec,value,onChange,onHelp}:{name:string;spec:SamplingParameterManifest;value:any;onChange:(v:any)=>void;onHelp:()=>void}) => <div className="mb-1.5"><div className="flex items-center gap-1 text-[7px] text-[#9aa0a6]"><span>{spec.label??name}</span><button onClick={onHelp} className="text-[#8ab4f8]"><HelpCircle size={9}/></button></div>{spec.type==='boolean'?<input type="checkbox" checked={Boolean(value)} onChange={(e)=>onChange(e.target.checked)}/>:spec.type==='enum'?<select value={String(value)} onChange={(e)=>{const choices=spec.choices??[];const found=choices.find((v)=>String(v)===e.target.value);onChange(found??e.target.value);}} className="w-full rounded border border-[#5f6368] bg-[#202124] px-1 py-1 text-[8px]">{(spec.choices??[]).map((v)=><option key={String(v)} value={String(v)}>{String(v)}</option>)}</select>:spec.type==='string'?<input value={String(value??'')} onChange={(e)=>onChange(e.target.value)} className="w-full rounded border border-[#5f6368] bg-[#202124] px-1 py-1 text-[8px]"/>:<input type="number" value={Number(value)} min={spec.min??undefined} max={spec.max??undefined} step={spec.type==='integer'?1:'any'} onChange={(e)=>onChange(spec.type==='integer'?Number.parseInt(e.target.value||'0',10):Number.parseFloat(e.target.value||'0'))} className="w-full rounded border border-[#5f6368] bg-[#202124] px-1 py-1 text-[8px]"/>}</div>;

const topicFor=(name:string)=>{
  const channels:Record<string,string>={sample_gray:'channel:gray',sample_r:'channel:r',sample_g:'channel:g',sample_b:'channel:b',sample_h:'channel:h',sample_s:'channel:s',sample_v:'channel:v',sample_lab_l:'channel:lab_l',sample_lab_a:'channel:lab_a',sample_lab_b:'channel:lab_b'};
  if(channels[name])return channels[name];
  if(name==='include_mean')return 'mean'; if(name==='include_std')return 'std'; if(name==='include_minmax')return 'minmax'; if(name==='include_histogram')return 'histogram';
  return name;
};

export const SamplingUnitsPanel = ({units,onHousingParam,onExtractorParam,onRemove,onToggleVisible,onInspect,onToggleExpose,onExposeName,onHelp,onInspectBlock}:{units:SpatialSamplingUnit[];onHousingParam:(id:string,n:string,v:any)=>void;onExtractorParam:(id:string,n:string,v:any)=>void;onRemove:(id:string)=>void;onToggleVisible:(id:string)=>void;onInspect:(id:string,kind:'housing'|'blocks'|'data')=>void;onToggleExpose:(id:string)=>void;onExposeName:(id:string,n:string)=>void;onHelp:(topic:string,spec?:SamplingParameterManifest)=>void;onInspectBlock:(block:DataBlockArtifact)=>void}) => <aside className="w-[430px] shrink-0 overflow-y-auto border-l border-[#3c4043] bg-[#292a2d] p-2">
  <div className="mb-2 flex items-center gap-2"><ScanLine size={13} className="text-[#8ab4f8]"/><span className="text-[9px] font-black">ACTIVE SAMPLING UNITS</span><span className="ml-auto text-[7px] text-[#80868b]">{units.length} units</span></div>
  {units.length===0?<div className="rounded border border-dashed border-[#5f6368] p-5 text-center text-[9px] text-[#80868b]">Choose a housing from the left library. Data Extractor is attached automatically.</div>:null}
  <div className="space-y-2">{units.map((unit)=><section key={unit.id} className="rounded border border-[#3c4043] bg-[#242528] p-2">
    <div className="flex items-center gap-1"><button onClick={()=>onToggleVisible(unit.id)} className="rounded p-1 text-[#8ab4f8]" title="Show/hide visualization only">{unit.visible?<Eye size={12}/>:<EyeOff size={12}/>}</button><div className="min-w-0 flex-1"><div className="truncate text-[9px] font-black">{unit.name}</div><div className="text-[7px] text-[#80868b]">WHERE + WHAT/HOW + composed output</div></div><button onClick={()=>onInspect(unit.id,'housing')} className="rounded border border-[#5f6368] px-1.5 py-1 text-[7px]">Inspect housing</button><button onClick={()=>onRemove(unit.id)} className="p-1 text-[#f28b82]"><Trash2 size={11}/></button></div>
    <details className="mt-2" open><summary className="cursor-pointer text-[8px] font-black text-[#fdd663]">1 · WHERE — {unit.housing.label}</summary><div className="mt-1 grid grid-cols-2 gap-x-2">{Object.entries(unit.housing.parameters).map(([name,spec])=><Param key={name} name={name} spec={spec} value={unit.housingParameters[name]} onChange={(v)=>onHousingParam(unit.id,name,v)} onHelp={()=>onHelp(name,spec)}/>)}</div></details>
    <details className="mt-2"><summary className="cursor-pointer text-[8px] font-black text-[#81c995]">2 · WHAT / HOW — Data Extractor</summary><div className="mt-1 grid grid-cols-2 gap-x-2">{Object.entries(unit.extractor.parameters).filter(([name])=>!['layout_mode','order_mode','block_order'].includes(name)).map(([name,spec])=><Param key={name} name={name} spec={spec} value={unit.extractorParameters[name]} onChange={(v)=>onExtractorParam(unit.id,name,v)} onHelp={()=>onHelp(topicFor(name),spec)}/>)}</div><div className="mt-1 flex gap-1"><button onClick={()=>onInspect(unit.id,'blocks')} className="rounded border border-[#5f6368] px-2 py-1 text-[7px]">Inspect Data Blocks</button><button onClick={()=>onInspect(unit.id,'data')} className="rounded border border-[#5f6368] px-2 py-1 text-[7px]">Inspect composed data</button></div></details>
    <div className="mt-2"><DataLayoutComposer artifact={unit.blocksArtifact} parameters={unit.extractorParameters} onParameter={(n,v)=>onExtractorParam(unit.id,n,v)} onInspectBlock={onInspectBlock} onHelp={(topic)=>onHelp(topic)}/></div>
    <div className="mt-2 flex items-center gap-1 border-t border-[#3c4043] pt-2"><button onClick={()=>onToggleExpose(unit.id)} className={`rounded border px-2 py-1 text-[7px] font-black ${unit.exposedAlias?'border-[#81c995] text-[#81c995]':'border-[#5f6368] text-[#9aa0a6]'}`}>{unit.exposedAlias?'EXPOSED':'Expose composed data'}</button>{unit.exposedAlias?<input value={unit.exposedAlias} onChange={(e)=>onExposeName(unit.id,e.target.value)} className="min-w-0 flex-1 rounded border border-[#5f6368] bg-[#202124] px-1 py-1 text-[7px]"/>:null}</div>
  </section>)}</div>
</aside>;
