import { ArrowDown, ArrowUp, Eye, EyeOff, Share2, Trash2 } from 'lucide-react';
import type { SamplingParameterManifest, SamplingStackItem } from './types';

const ParameterControl = ({ name, spec, value, onChange }: { name: string; spec: SamplingParameterManifest; value: any; onChange: (value: any) => void }) => {
  const label = spec.label || name.replaceAll('_', ' ');
  if (spec.type === 'boolean') return <div className="grid grid-cols-[1fr_auto] items-center gap-2"><div className="text-[9px] text-[#bdc1c6]">{label}</div><button onClick={()=>onChange(!Boolean(value))} className={`rounded px-2 py-1 text-[9px] font-bold ${value?'bg-[#174ea6] text-[#d2e3fc]':'bg-[#202124] text-[#9aa0a6]'}`}>{value?'ON':'OFF'}</button></div>;
  if (spec.type === 'enum') { const choices=spec.choices??[]; let index=choices.findIndex((choice)=>Object.is(choice,value)); if(index<0) index=choices.findIndex((choice)=>String(choice)===String(value)); return <div><div className="mb-1 text-[9px] text-[#bdc1c6]">{label}</div><select value={Math.max(0,index)} onChange={(e)=>onChange(choices[Number(e.target.value)])} className="w-full rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[10px] text-[#e8eaed]">{choices.map((choice,i)=><option key={`${i}:${String(choice)}`} value={i}>{String(choice)}</option>)}</select></div>; }
  if (spec.type === 'integer' || spec.type === 'float') { const min=spec.min??0; const max=spec.max??(spec.type==='integer'?255:1); const step=spec.odd?2:spec.type==='integer'?1:Math.max(0.001,(Number(max)-Number(min))/200); return <div><div className="mb-1 flex items-center justify-between text-[9px] text-[#bdc1c6]"><span>{label}</span><span className="font-mono text-[#8ab4f8]">{String(value)}</span></div><div className="grid grid-cols-[1fr_64px] gap-2"><input type="range" min={min??undefined} max={max??undefined} step={step} value={Number(value)} onChange={(e)=>onChange(Number(e.target.value))} className="accent-[#8ab4f8]"/><input type="number" min={min??undefined} max={max??undefined} step={step} value={Number(value)} onChange={(e)=>onChange(Number(e.target.value))} className="rounded border border-[#5f6368] bg-[#202124] px-1 py-0.5 text-[9px] text-[#e8eaed]"/></div></div>; }
  return null;
};

export const SamplingStack = ({ stack, selectedNodeId, timings, onSelect, onParameter, onMove, onRemove, onToggleExpose, onExposeName }: { stack: SamplingStackItem[]; selectedNodeId: string | null; timings: Record<string, number>; onSelect: (id: string) => void; onParameter: (id: string, name: string, value: any) => void; onMove: (id: string, delta: number) => void; onRemove: (id: string) => void; onToggleExpose: (id: string) => void; onExposeName: (id: string, name: string) => void }) => (
  <aside className="flex w-[350px] min-w-[300px] flex-col overflow-hidden border-l border-[#3c4043] bg-[#202124]">
    <div className="border-b border-[#3c4043] bg-[#292a2d] px-3 py-2"><div className="text-[11px] font-black tracking-[0.18em] text-[#e8eaed]">PIPELINE STACK</div><div className="text-[9px] text-[#80868b]">Linear UX · typed pipeline contract</div></div>
    <div className="flex-1 overflow-y-auto p-2">{stack.length===0?<div className="rounded border border-dashed border-[#5f6368] p-5 text-center text-xs text-[#80868b]">Add an operator from the left panel.</div>:stack.map((item,index)=><div key={item.id} onClick={()=>onSelect(item.id)} className={`mb-2 rounded border p-2.5 ${selectedNodeId===item.id?'border-[#8ab4f8] bg-[#303134]':'border-[#3c4043] bg-[#292a2d]'}`}>
      <div className="flex items-start gap-2"><div className="mt-0.5 flex h-5 w-5 items-center justify-center rounded bg-[#3c4043] text-[9px] font-black text-[#8ab4f8]">{index+1}</div><div className="min-w-0 flex-1"><div className="truncate text-[11px] font-bold text-[#e8eaed]">{item.operator.label}</div><div className="font-mono text-[8px] text-[#80868b]">{Object.values(item.operator.inputs)[0]?.type} → {Object.values(item.operator.outputs)[0]?.type}{timings[item.id]!==undefined?` · ${timings[item.id].toFixed(2)} ms`:''}</div></div><div className="flex gap-1"><button onClick={(e)=>{e.stopPropagation();onMove(item.id,-1)}} className="rounded p-1 text-[#9aa0a6] hover:bg-[#3c4043]"><ArrowUp size={11}/></button><button onClick={(e)=>{e.stopPropagation();onMove(item.id,1)}} className="rounded p-1 text-[#9aa0a6] hover:bg-[#3c4043]"><ArrowDown size={11}/></button><button onClick={(e)=>{e.stopPropagation();onRemove(item.id)}} className="rounded p-1 text-[#9aa0a6] hover:bg-[#5f2120] hover:text-[#f28b82]"><Trash2 size={11}/></button></div></div>
      <div className="mt-2 space-y-2" onClick={(e)=>e.stopPropagation()}>{Object.entries(item.operator.parameters).map(([name,spec])=><ParameterControl key={name} name={name} spec={spec} value={item.parameters[name]} onChange={(value)=>onParameter(item.id,name,value)}/>)}</div>
      <div className="mt-2 border-t border-[#3c4043] pt-2" onClick={(e)=>e.stopPropagation()}><div className="flex items-center gap-2"><button onClick={()=>onToggleExpose(item.id)} className={`flex items-center gap-1 rounded border px-2 py-1 text-[9px] font-bold ${item.exposedName?'border-[#81c995] bg-[#1e3828] text-[#81c995]':'border-[#5f6368] bg-[#202124] text-[#9aa0a6]'}`}><Share2 size={10}/>{item.exposedName?'SERVICE OUTPUT':'Expose'}</button>{item.exposedName?<input value={item.exposedName} onChange={(e)=>onExposeName(item.id,e.target.value)} className="min-w-0 flex-1 rounded border border-[#5f6368] bg-[#202124] px-2 py-1 font-mono text-[9px] text-[#e8eaed]"/>:null}</div></div>
    </div>)}</div>
  </aside>
);
