import { useEffect, useState } from 'react';
import { HelpCircle, Image as ImageIcon, X } from 'lucide-react';
import type { SamplingParameterManifest } from './types';

const formulas:Record<string,{title:string;formula:string;body:string;values:number[]}>= {
 mean:{title:'Mean / Average',formula:'μ = (1/N) Σ xᵢ',body:'Mean is the center of the sampled values. Two signals can share the same mean even when one is flat and the other varies strongly.',values:[20,40,60,80,100,120]},
 std:{title:'Standard deviation',formula:'σ = √[(1/N) Σ (xᵢ − μ)²]',body:'STD measures spread around the mean. Flat samples produce small STD; strongly varying samples produce large STD.',values:[15,110,30,140,25,125]},
 minmax:{title:'Minimum / Maximum',formula:'min(xᵢ), max(xᵢ)',body:'Min and max capture the observed range. They are easy to understand but sensitive to a single extreme pixel.',values:[25,42,60,210,85,120]},
 histogram:{title:'Histogram',formula:'h[b] = count{xᵢ in bin b}',body:'A histogram forgets pixel order and keeps the value distribution. More bins preserve finer detail but increase dimensionality and noise.',values:[2,4,10,18,30,22,9,3]},
 sample_step:{title:'Sampling step',formula:'x₀, x₀+s, x₀+2s, …',body:'Step controls density along a housing path. Step=1 samples every pixel-equivalent position; Step=4 keeps roughly one in every four.',values:[1,0,0,0,1,0,0,0,1,0,0,0,1]},
 sample_count:{title:'Fixed sample count',formula:'N samples after interpolation',body:'Every ray/ring/patch is resampled to the same length. This makes downstream model shape deterministic even when geometric path lengths differ.',values:[1,1,1,1,1,1,1,1]},
};

const MiniGraph=({values}:{values:number[]})=>{const max=Math.max(...values,1),min=Math.min(...values,0),range=Math.max(1e-9,max-min);const pts=values.map((v,i)=>`${10+i*180/Math.max(1,values.length-1)},${90-(v-min)/range*70}`).join(' ');return <svg viewBox="0 0 200 100" className="h-32 w-full rounded border border-[#3c4043] bg-[#171717]"><line x1="10" y1="90" x2="190" y2="90" stroke="#5f6368"/><polyline points={pts} fill="none" stroke="#8ab4f8" strokeWidth="2"/>{values.map((v,i)=>{const x=10+i*180/Math.max(1,values.length-1),y=90-(v-min)/range*70;return <circle key={i} cx={x} cy={y} r="2.5" fill="#fdd663"/>;})}</svg>;};

export const SamplingParameterHelpModal=({title,spec,topic,onClose,onChannelPreview}:{title:string;spec?:SamplingParameterManifest;topic?:string;onClose:()=>void;onChannelPreview?:(channel:string)=>Promise<string|null>})=>{
  const [channelUrl,setChannelUrl]=useState<string|null>(null);const [loading,setLoading]=useState(false);
  const channel=topic?.startsWith('channel:')?topic.split(':')[1]:null;const item=formulas[topic??''];
  useEffect(()=>()=>{if(channelUrl)URL.revokeObjectURL(channelUrl);},[channelUrl]);
  const load=async()=>{if(!channel||!onChannelPreview)return;setLoading(true);try{const url=await onChannelPreview(channel);if(channelUrl)URL.revokeObjectURL(channelUrl);setChannelUrl(url);}finally{setLoading(false);}};
  const channelLabel:Record<string,string>={gray:'Grayscale',r:'RGB · Red',g:'RGB · Green',b:'RGB · Blue',h:'HSV · Hue',s:'HSV · Saturation',v:'HSV · Value',lab_l:'LAB · L*',lab_a:'LAB · a*',lab_b:'LAB · b*'};
  return <div className="fixed inset-0 z-[180] flex items-center justify-center bg-black/75 p-4"><div className="w-full max-w-4xl rounded-xl border border-[#5f6368] bg-[#292a2d] p-4"><div className="flex items-center gap-2"><HelpCircle size={16} className="text-[#8ab4f8]"/><div><div className="text-sm font-black">{channel?channelLabel[channel]??channel:item?.title??title}</div><div className="text-[8px] text-[#80868b]">Parameter guide · actual data when possible, mathematical model otherwise</div></div><button onClick={onClose} className="ml-auto"><X size={16}/></button></div>
    {channel?<div className="mt-4 grid grid-cols-[1fr_300px] gap-4"><div className="min-h-[300px] rounded border border-[#3c4043] bg-[#111] p-2">{channelUrl?<img src={channelUrl} className="h-full max-h-[430px] w-full object-contain"/>:<div className="flex h-full min-h-[300px] items-center justify-center text-[9px] text-[#5f6368]">Preview the selected channel from the actual inspected image.</div>}</div><div><p className="text-[10px] leading-5 text-[#bdc1c6]">This is the real channel that Data Extractor will read. The preview is normalized for display, while numeric sampling keeps the channel's native values.</p><button onClick={()=>void load()} className="mt-3 flex items-center gap-1 rounded border border-[#8ab4f8] bg-[#174ea6] px-2 py-1.5 text-[8px] font-black"><ImageIcon size={10}/>{loading?'Loading…':'Render actual channel'}</button><div className="mt-4 rounded border border-[#3c4043] bg-[#202124] p-3 text-[8px] leading-4 text-[#9aa0a6]">RGB separates additive color components. HSV separates hue/saturation/value. LAB separates perceptual lightness from opponent color axes, which can be useful when illumination and color should be treated differently.</div></div></div>:item?<div className="mt-4 grid grid-cols-[1fr_330px] gap-4"><div><MiniGraph values={item.values}/><p className="mt-3 text-[10px] leading-5 text-[#bdc1c6]">{item.body}</p></div><div className="rounded border border-[#3c4043] bg-[#202124] p-4"><div className="text-[9px] font-black text-[#fdd663]">FORMULA / MODEL</div><div className="mt-3 rounded bg-[#171717] p-3 text-center font-mono text-sm text-[#d2e3fc]">{item.formula}</div>{topic==='sample_step'?<div className="mt-4"><div className="text-[8px] text-[#9aa0a6]">Step = 1</div><div className="font-mono text-[#fdd663]">●●●●●●●●●●●●</div><div className="mt-2 text-[8px] text-[#9aa0a6]">Step = 4</div><div className="font-mono text-[#fdd663]">●···●···●···●</div></div>:null}</div></div>:<p className="mt-4 text-[10px] leading-5 text-[#bdc1c6]">{spec?.description??'This parameter controls how data is sampled or represented.'}</p>}
    {spec?<div className="mt-4 rounded border border-[#3c4043] bg-[#202124] p-3 text-[9px] text-[#9aa0a6]"><span>Type <b>{spec.type}</b></span><span className="ml-4">Default <b>{String(spec.default)}</b></span>{spec.min!=null||spec.max!=null?<span className="ml-4">Range {String(spec.min??'−∞')} .. {String(spec.max??'∞')}</span>:null}</div>:null}
  </div></div>;
};
