import { Eye, HelpCircle } from 'lucide-react';
import type { SamplingMethodDefinition } from './types';

const CHANNELS=[['gray','Gray'],['r','R'],['g','G'],['b','B'],['h','H'],['s','S'],['v','V'],['l','L*'],['a','a*'],['lab_b','b*']] as const;
const STATS=['mean','std','min','max','median'] as const;

const Num=({label,value,min,max,step=1,onChange,help}:{label:string;value:number;min:number;max:number;step?:number;onChange:(v:number)=>void;help?:()=>void})=><label className="block"><span className="mb-1 flex items-center gap-1 text-[8px] font-black uppercase text-[#9aa0a6]">{label}{help?<button type="button" onClick={help}><HelpCircle size={10}/></button>:null}</span><input type="number" value={value} min={min} max={max} step={step} onChange={(e)=>onChange(Number(e.target.value))} className="w-full rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[9px]"/></label>;

export const SamplingMethodEditor=({method,onChange,onHelp,onChannelPreview}:{method:SamplingMethodDefinition;onChange:(patch:Partial<SamplingMethodDefinition>)=>void;onHelp:(topic:string)=>void;onChannelPreview:(channel:string)=>void;})=>{
 const shape=['rays','cross','rings'].includes(method.kind);
 const toggleChannel=(ch:string)=>onChange({channels:method.channels.includes(ch)?method.channels.filter((x)=>x!==ch):[...method.channels,ch]});
 const toggleMeasure=(name:string)=>onChange({measures:method.measures.includes(name)?method.measures.filter((x)=>x!==name):[...method.measures,name]});
 const parameters={...method.parameters};
 return <div className="border-t border-[#3c4043] p-3">
  <div className="mb-3"><div className="text-[10px] font-black">{method.label??method.kind}</div><div className="text-[8px] text-[#80868b]">Configure what this method sees and what numbers it produces.</div></div>
  {method.kind==='rays'?<div className="mb-3 grid grid-cols-2 gap-2"><label><span className="mb-1 block text-[8px] font-black uppercase text-[#9aa0a6]">Direction</span><select value={parameters.axis??'x'} onChange={(e)=>onChange({parameters:{...parameters,axis:e.target.value}})} className="w-full rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[9px]"><option value="x">Horizontal</option><option value="y">Vertical</option><option value="both">Both</option></select></label><Num label="Ray count" value={Number(parameters.ray_count??5)} min={1} max={32} onChange={(v)=>onChange({parameters:{...parameters,ray_count:v}})}/></div>:null}
  {method.kind==='cross'||method.kind==='rings'?<div className="mb-3 rounded border border-[#3c4043] p-2"><div className="mb-2 text-[8px] font-black uppercase text-[#9aa0a6]">Placement</div><div className="mb-2 flex gap-1">{(['center','auto_grid'] as const).map((mode)=><button key={mode} onClick={()=>onChange({placement:{...method.placement,mode}})} className={`flex-1 rounded border px-2 py-1 text-[8px] ${method.placement.mode===mode?'border-[#8ab4f8] bg-[#174ea6]':'border-[#5f6368]'}`}>{mode==='center'?'Center / patch base':'Auto arrange grid'}</button>)}</div>{method.placement.mode==='center'?<div className="grid grid-cols-2 gap-2"><Num label="Center X" value={method.placement.center_x} min={0} max={1} step={.05} onChange={(v)=>onChange({placement:{...method.placement,center_x:v}})}/><Num label="Center Y" value={method.placement.center_y} min={0} max={1} step={.05} onChange={(v)=>onChange({placement:{...method.placement,center_y:v}})}/></div>:<div className="grid grid-cols-2 gap-2"><Num label="Centers Y" value={method.placement.rows} min={1} max={12} onChange={(v)=>onChange({placement:{...method.placement,rows:v}})}/><Num label="Centers X" value={method.placement.cols} min={1} max={12} onChange={(v)=>onChange({placement:{...method.placement,cols:v}})}/></div>}</div>:null}
  {method.kind==='cross'?<div className="mb-3"><Num label="Cross length ratio" value={Number(parameters.length_ratio??.8)} min={.05} max={1.5} step={.05} onChange={(v)=>onChange({parameters:{...parameters,length_ratio:v}})}/></div>:null}
  {method.kind==='rings'?<div className="mb-3 grid grid-cols-2 gap-2"><Num label="Ring count" value={Number(parameters.ring_count??3)} min={1} max={12} onChange={(v)=>onChange({parameters:{...parameters,ring_count:v}})}/><Num label="Max radius" value={Number(parameters.max_radius_ratio??.4)} min={.05} max={.7} step={.05} onChange={(v)=>onChange({parameters:{...parameters,max_radius_ratio:v}})}/></div>:null}
  <div className="mb-3"><div className="mb-1 flex items-center gap-1 text-[8px] font-black uppercase text-[#9aa0a6]">Channels <button onClick={()=>onHelp('channels')}><HelpCircle size={10}/></button></div><div className="grid grid-cols-5 gap-1">{CHANNELS.map(([ch,label])=><div key={ch} className={`rounded border ${method.channels.includes(ch)?'border-[#81c995] bg-[#1e3828]':'border-[#3c4043] bg-[#202124]'}`}><button onClick={()=>toggleChannel(ch)} className="w-full px-1 py-1 text-[8px] font-black">{label}</button><button onClick={()=>onChannelPreview(ch)} title="Show this real channel" className="flex w-full justify-center border-t border-[#3c4043] py-1 text-[#8ab4f8]"><Eye size={10}/></button></div>)}</div></div>
  {shape?<div className="mb-3 rounded border border-[#3c4043] p-2"><div className="mb-2 flex items-center gap-1 text-[8px] font-black uppercase text-[#9aa0a6]">Sampling density <button onClick={()=>onHelp('sampling_density')}><HelpCircle size={10}/></button></div><select value={method.sampling_mode} onChange={(e)=>onChange({sampling_mode:e.target.value as any})} className="mb-2 w-full rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[9px]"><option value="count">Fixed sample count</option><option value="step">Fixed spatial step</option><option value="full">Full pixel density</option></select>{method.sampling_mode==='count'?<Num label="Samples / path" value={method.sample_count} min={2} max={4096} onChange={(v)=>onChange({sample_count:v})}/>:method.sampling_mode==='step'?<Num label="Step (px)" value={method.sample_step} min={.25} max={128} step={.25} onChange={(v)=>onChange({sample_step:v})} help={()=>onHelp('sampling_step')}/>:<div className="text-[8px] text-[#80868b]">One sample approximately per source pixel along the path.</div>}</div>:null}
  <div className="mb-3"><div className="mb-1 text-[8px] font-black uppercase text-[#9aa0a6]">Output measures</div><div className="flex flex-wrap gap-1">{shape?<button onClick={()=>toggleMeasure('profile')} className={`rounded border px-2 py-1 text-[8px] ${method.measures.includes('profile')?'border-[#8ab4f8] bg-[#174ea6]':'border-[#5f6368]'}`}>Raw profile</button>:null}{(method.kind==='statistics'||shape)?STATS.map((name)=><button key={name} onClick={()=>toggleMeasure(name)} className={`flex items-center gap-1 rounded border px-2 py-1 text-[8px] ${method.measures.includes(name)?'border-[#8ab4f8] bg-[#174ea6]':'border-[#5f6368]'}`}>{name.toUpperCase()}<span onClick={(e)=>{e.stopPropagation();onHelp(name);}}><HelpCircle size={9}/></span></button>):null}{(method.kind==='histogram'||shape)?<button onClick={()=>toggleMeasure('histogram')} className={`flex items-center gap-1 rounded border px-2 py-1 text-[8px] ${method.kind==='histogram'||method.measures.includes('histogram')?'border-[#8ab4f8] bg-[#174ea6]':'border-[#5f6368]'}`}>Histogram<span onClick={(e)=>{e.stopPropagation();onHelp('histogram');}}><HelpCircle size={9}/></span></button>:null}</div></div>
  {(method.kind==='histogram'||method.measures.includes('histogram'))?<Num label="Histogram bins" value={method.histogram_bins} min={2} max={256} onChange={(v)=>onChange({histogram_bins:v})} help={()=>onHelp('histogram_bins')}/>:null}
 </div>;
};
