import { ChevronDown, ChevronUp, Grid3X3, Layers3, Trash2 } from 'lucide-react';
import type { SamplingDomain, SamplingMethodDefinition, SamplingProgramDefinition } from './types';
import { SamplingMethodEditor } from './SamplingMethodEditor';

export const SamplingStructurePanel=({domain,onDomain,program,selectedMethodId,onSelectMethod,onRemoveMethod,onMoveMethod,onMethodChange,onGridChange,onOpenShape,onHelp,onChannelPreview}:{
  domain:SamplingDomain;onDomain:(d:SamplingDomain)=>void;program:SamplingProgramDefinition;selectedMethodId:string|null;onSelectMethod:(id:string|null)=>void;onRemoveMethod:(id:string)=>void;onMoveMethod:(id:string,delta:number)=>void;onMethodChange:(id:string,patch:Partial<SamplingMethodDefinition>)=>void;onGridChange:(patch:Partial<SamplingProgramDefinition['local_domain']['grid']>)=>void;onOpenShape:()=>void;onHelp:(topic:string)=>void;onChannelPreview:(channel:string)=>void;
})=>{
 const methods=domain==='global'?program.global_domain.methods:program.local_domain.methods;
 const selected=methods.find((m)=>m.id===selectedMethodId)??null;
 return <aside className="flex w-[360px] shrink-0 flex-col border-l border-[#3c4043] bg-[#242528]">
  <div className="grid grid-cols-2 border-b border-[#3c4043] p-2">{(['global','local'] as const).map((d)=><button key={d} onClick={()=>{onDomain(d);onSelectMethod(null);}} className={`flex items-center justify-center gap-2 rounded px-3 py-2 text-[9px] font-black ${domain===d?'bg-[#174ea6] text-white':'text-[#9aa0a6]'}`}>{d==='global'?<Layers3 size={13}/>:<Grid3X3 size={13}/>} {d.toUpperCase()}</button>)}</div>
  <div className="min-h-0 flex-1 overflow-y-auto">
   <button onClick={()=>onSelectMethod(null)} className={`w-full border-b border-[#3c4043] p-3 text-left ${!selected?'bg-[#303134]':''}`}><div className="text-[9px] font-black">{domain==='global'?'GLOBAL DOMAIN':'LOCAL PATCH GRID'}</div><div className="mt-1 text-[8px] leading-4 text-[#80868b]">{domain==='global'?'Whole inspected image is one sampling domain.':`${program.local_domain.grid.rows} × ${program.local_domain.grid.cols} patches. Every child method is repeated on each patch.`}</div></button>
   {domain==='local'&&!selected?<div className="grid grid-cols-2 gap-2 border-b border-[#3c4043] p-3"><label><span className="mb-1 block text-[8px] font-black uppercase text-[#9aa0a6]">Patch rows (Y)</span><input type="number" min={1} max={64} value={program.local_domain.grid.rows} onChange={(e)=>onGridChange({rows:Number(e.target.value)})} className="w-full rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[9px]"/></label><label><span className="mb-1 block text-[8px] font-black uppercase text-[#9aa0a6]">Patch cols (X)</span><input type="number" min={1} max={64} value={program.local_domain.grid.cols} onChange={(e)=>onGridChange({cols:Number(e.target.value)})} className="w-full rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[9px]"/></label></div>:null}
   <div className="p-2"><div className="mb-2 text-[8px] font-black uppercase tracking-[.12em] text-[#80868b]">{domain==='global'?'Global sampling blocks':'Children of Patch Grid'}</div>{methods.length?methods.map((m,i)=><div key={m.id} className={`mb-1 rounded border ${selectedMethodId===m.id?'border-[#8ab4f8] bg-[#303134]':'border-[#3c4043] bg-[#202124]'}`}><button onClick={()=>onSelectMethod(m.id)} className="w-full px-2 py-2 text-left"><div className="flex items-center"><span className="text-[9px] font-black">{m.label??m.kind}</span><span className="ml-auto rounded bg-[#3c4043] px-1.5 py-0.5 text-[7px] uppercase text-[#9aa0a6]">{m.channels.join('+')}</span></div><div className="mt-1 text-[8px] text-[#80868b]">{m.kind==='histogram'?`${m.histogram_bins} bins`:m.kind==='statistics'?m.measures.join(' · '):`${m.sampling_mode==='count'?`${m.sample_count} samples/path`:m.sampling_mode==='step'?`${m.sample_step}px step`:'full density'} · ${m.measures.join(' · ')}`}</div></button><div className="flex justify-end gap-1 border-t border-[#3c4043] p-1"><button disabled={i===0} onClick={()=>onMoveMethod(m.id,-1)} className="p-1 disabled:opacity-30"><ChevronUp size={11}/></button><button disabled={i===methods.length-1} onClick={()=>onMoveMethod(m.id,1)} className="p-1 disabled:opacity-30"><ChevronDown size={11}/></button><button onClick={()=>onRemoveMethod(m.id)} className="p-1 text-[#f28b82]"><Trash2 size={11}/></button></div></div>):<div className="rounded border border-dashed border-[#5f6368] p-3 text-center text-[8px] leading-4 text-[#80868b]">Select a method from the left library. It will appear here as {domain==='global'?'a Global block':'a child of the Patch Grid'}.</div>}</div>
   {selected?<SamplingMethodEditor method={selected} onChange={(patch)=>onMethodChange(selected.id,patch)} onHelp={onHelp} onChannelPreview={onChannelPreview}/>:null}
  </div>
  <div className="border-t border-[#3c4043] p-2"><button onClick={onOpenShape} className="w-full rounded border border-[#81c995] bg-[#1e3828] px-3 py-2 text-[9px] font-black text-[#81c995]">Open Output Formulation Workspace</button></div>
 </aside>;
};
