import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, FlaskConical, Loader2, Play, Share2 } from 'lucide-react';
import { SourceBoard } from '../components/VisionLabs/SamplingGeometry/SourceBoard';
import { SamplingMethodLibrary } from '../components/VisionLabs/SamplingProgram/SamplingMethodLibrary';
import { SamplingProgramCanvas } from '../components/VisionLabs/SamplingProgram/SamplingProgramCanvas';
import { SamplingStructurePanel } from '../components/VisionLabs/SamplingProgram/SamplingStructurePanel';
import { SamplingOutputShapeDesigner } from '../components/VisionLabs/SamplingProgram/SamplingOutputShapeDesigner';
import { SamplingConceptHelpModal } from '../components/VisionLabs/SamplingProgram/SamplingConceptHelpModal';
import { useSamplingProgramController } from '../components/VisionLabs/SamplingProgram/useSamplingProgramController';

export const SamplingGeometryLabPage=()=>{
 const navigate=useNavigate();const c=useSamplingProgramController();const [shapeOpen,setShapeOpen]=useState(false);const [help,setHelp]=useState<{topic:string;url?:string|null}|null>(null);
 const closeHelp=()=>{if(help?.url?.startsWith('blob:'))URL.revokeObjectURL(help.url);setHelp(null);};
 const showChannel=async(channel:string)=>{const url=await c.channelPreview(channel);if(url)setHelp({topic:'channels',url});};
 const exposed=[c.program.output_shape.include_global,c.program.output_shape.include_local,c.program.output_shape.include_combined].filter(Boolean).length;
 return <div className="flex h-screen w-screen flex-col overflow-hidden bg-[#202124] text-[#e8eaed]">
  <header className="shrink-0 border-b border-[#3c4043] bg-[#292a2d]"><div className="flex h-14 items-center gap-3 px-3"><button onClick={()=>navigate('/labs')} className="flex h-8 w-8 items-center justify-center rounded border border-[#5f6368] bg-[#35363a]"><ArrowLeft size={15}/></button><FlaskConical size={18} className="text-[#8ab4f8]"/><div><div className="text-xs font-black tracking-[.16em]">SAMPLING LAB</div><div className="text-[8px] text-[#80868b]">Global / Local sampling · image → domains → channels/measures → Vector / 2-D Matrix formulation</div></div><div className="ml-auto flex items-center gap-2"><div className="flex rounded border border-[#5f6368] p-0.5"><button onClick={()=>c.setExecutionMode('live')} className={`px-2 py-1 text-[8px] ${c.executionMode==='live'?'bg-[#174ea6]':''}`}>LIVE</button><button onClick={()=>c.setExecutionMode('manual')} className={`px-2 py-1 text-[8px] ${c.executionMode==='manual'?'bg-[#3c4043]':''}`}>MANUAL</button></div><button onClick={()=>void c.runNow()} disabled={!c.sourceBoard||c.busy} className="flex items-center gap-1 rounded border border-[#8ab4f8] bg-[#174ea6] px-3 py-1.5 text-[9px] font-black disabled:opacity-40">{c.busy?<Loader2 size={11} className="animate-spin"/>:<Play size={11}/>}Run Program</button></div></div>
   <SourceBoard file={c.inputFile} onFile={c.setInputFile} config={c.sourceBoardConfig} onConfig={c.setSourceBoardConfig} services={c.imageServices} manifest={c.sourceBoard} busy={c.busy} onBuild={()=>void c.buildBoard()} onInspect={(name)=>void c.inspectSource(name)}/>
   <div className="flex h-10 items-center gap-2 border-t border-[#3c4043] px-3"><Share2 size={11} className="text-[#81c995]"/><span className="text-[8px] font-black uppercase text-[#80868b]">Deploy Sampling Program</span><input value={c.serviceName} onChange={(e)=>c.setServiceName(e.target.value)} className="w-[240px] rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[9px]"/><span className="text-[8px] text-[#80868b]">{exposed} composed output(s)</span>{c.run?<span className="text-[8px] text-[#fdd663]">Global D={c.run.manifest.global_feature_count} · Local [{c.run.manifest.local_shape.join('×')}]</span>:null}<button onClick={()=>void c.deploy(false)} disabled={!exposed||c.busy} className="ml-auto rounded border border-[#81c995] bg-[#1e3828] px-2 py-1 text-[8px] font-black text-[#81c995] disabled:opacity-40">{c.editingService?'Update Service':'Deploy Service'}</button>{c.editingService?<button onClick={()=>void c.deploy(true)} className="rounded border border-[#5f6368] px-2 py-1 text-[8px]">Save As New</button>:null}</div>
  </header>
  {c.error?<div className="shrink-0 border-b border-[#f28b82]/40 bg-[#5f2120] px-3 py-1 text-[9px] text-[#f28b82]">{c.error}<button onClick={()=>c.setError('')} className="ml-3 font-black">dismiss</button></div>:null}
  <main className="flex min-h-0 flex-1"><SamplingMethodLibrary domain={c.activeDomain} catalog={c.catalog} onAdd={c.addMethod}/><div className="min-w-0 flex-1"><SamplingProgramCanvas sourceUrl={c.sourceUrl} domain={c.activeDomain} program={c.program} selectedMethod={c.selectedMethod}/></div><SamplingStructurePanel domain={c.activeDomain} onDomain={c.setActiveDomain} program={c.program} selectedMethodId={c.selectedMethodId} onSelectMethod={c.setSelectedMethodId} onRemoveMethod={c.removeMethod} onMoveMethod={c.moveMethod} onMethodChange={c.updateMethod} onGridChange={c.setLocalGrid} onOpenShape={()=>setShapeOpen(true)} onHelp={(topic)=>setHelp({topic})} onChannelPreview={(channel)=>void showChannel(channel)}/></main>
  <div className="flex h-7 shrink-0 items-center gap-3 border-t border-[#3c4043] bg-[#242528] px-3 text-[8px] text-[#80868b]"><span>Program v6</span><span>Global methods: {c.program.global_domain.methods.length}</span><span>Local: {c.program.local_domain.grid.rows}×{c.program.local_domain.grid.cols} patches · {c.program.local_domain.methods.length} method(s)</span>{c.run?<><span className="text-[#81c995]">Features / patch={c.run.manifest.features_per_patch??'?'}</span><span>Local [{c.run.manifest.local_shape.join('×')}]</span><span>Combined D={c.run.manifest.combined_feature_count}</span></>:<span className="text-[#5f6368]">Run once to sample; use Formulate to reshape cached Data Blocks</span>}</div>
  {shapeOpen?<SamplingOutputShapeDesigner program={c.program} run={c.run} onChange={c.setOutputShape} onFormulate={()=>void c.formulateNow()} formulating={c.formulating} dirty={c.formulationDirty} onClose={()=>setShapeOpen(false)}/>:null}
  {help?<SamplingConceptHelpModal topic={help.topic} channelPreviewUrl={help.url} onClose={closeHelp}/>:null}
 </div>;
};
