import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Box, Camera, ChevronLeft, ChevronRight, Cpu, Image as ImageIcon, Loader2, Play, Save, Sparkles, Trash2, Upload, Wifi } from 'lucide-react';
import { LabServiceAPI, type LabServiceDefinition } from '../api/labServiceApi';
import { VisionAppAPI, type BenchmarkStep, type ControlPrimitiveAction, type DebugImageRef, type LocatedRoi, type MasterRoi, type NormalizedRect, type TriggerRunnerStatus, type VisionProgramDefinition, type VisionRunResult } from '../api/visionAppApi';
import { VisionViewport } from '../components/ComputerVision/VisionViewport';
import { IotModulePanel } from '../components/ComputerVision/IotModulePanel';
import { CameraModulePanel } from '../components/ComputerVision/CameraModulePanel';
import { MasterSamplePanel } from '../components/ComputerVision/MasterSamplePanel';
import { WorkingModulePanel } from '../components/ComputerVision/WorkingModulePanel';
import { DebugWorkspace } from '../components/ComputerVision/DebugWorkspace';
import { IotIdePlaceholder } from '../components/ComputerVision/IotIdePlaceholder';
import '../components/ComputerVision/ComputerVision.css';

type ModuleKey='iot'|'camera'|'master'|'working';
const roiDefault=(rect:NormalizedRect,index:number):MasterRoi=>({roi_id:`roi_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,name:`Station ${index+1}`,rect,enabled:true});

export const ComputerVisionPage=()=>{
 const navigate=useNavigate();const [module,setModule]=useState<ModuleKey>('master');const [programs,setPrograms]=useState<(VisionProgramDefinition&{master_exists?:boolean})[]>([]);const [program,setProgram]=useState<VisionProgramDefinition|null>(null);const [services,setServices]=useState<LabServiceDefinition[]>([]);const [masterUrl,setMasterUrl]=useState<string|null>(null);const [masterBlurUrl,setMasterBlurUrl]=useState<string|null>(null);const [testBlob,setTestBlob]=useState<Blob|null>(null);const [testName,setTestName]=useState('');const [testUrl,setTestUrl]=useState<string|null>(null);const [located,setLocated]=useState<LocatedRoi[]>([]);const [run,setRun]=useState<VisionRunResult|null>(null);const [selectedRoi,setSelectedRoi]=useState<string|null>(null);const [drawMode,setDrawMode]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [triggerState,setTriggerState]=useState<boolean|null>(null);const [runner,setRunner]=useState<TriggerRunnerStatus|null>(null);const [leftOpen,setLeftOpen]=useState(true);const [rightOpen,setRightOpen]=useState(true);const [masterView,setMasterView]=useState<'original'|'blur'>('original');const [cameraUrl,setCameraUrl]=useState<string|null>(null);const [cameraLive,setCameraLive]=useState(false);const [debugOpen,setDebugOpen]=useState(false);const [debugSession,setDebugSession]=useState<{runId:string|null;items:DebugImageRef[];benchmarks:BenchmarkStep[];runResult:VisionRunResult|null;title:string}>({runId:null,items:[],benchmarks:[],runResult:null,title:'Working Debug Stack'});
 const setBlobAsTest=(blob:Blob,name:string)=>{setTestBlob(blob);setTestName(name);setLocated([]);setRun(null);setTestUrl(old=>{if(old)URL.revokeObjectURL(old);return URL.createObjectURL(blob);});};
 const loadProgram=async(id:string)=>{const loaded=await VisionAppAPI.getProgram(id);setProgram(loaded.program);setLocated([]);setRun(null);setSelectedRoi(null);setDebugOpen(false);setDebugSession({runId:null,items:[],benchmarks:[],runResult:null,title:'Working Debug Stack'});setRunner(await VisionAppAPI.runnerStatus(id));setMasterBlurUrl(old=>{if(old)URL.revokeObjectURL(old);return null;});setMasterView('original');if(loaded.master_exists){const blob=await VisionAppAPI.masterPreview(id);const url=URL.createObjectURL(blob);setMasterUrl(old=>{if(old)URL.revokeObjectURL(old);return url;});}else setMasterUrl(old=>{if(old)URL.revokeObjectURL(old);return null;});};
 const refreshList=async(selectId?:string)=>{const list=await VisionAppAPI.listPrograms();setPrograms(list);const id=selectId??program?.program_id??list[0]?.program_id;if(id)await loadProgram(id);};
 useEffect(()=>{void(async()=>{try{setBusy(true);const [list,svc]=await Promise.all([VisionAppAPI.listPrograms(),LabServiceAPI.list()]);setServices(svc);if(list.length){setPrograms(list);await loadProgram(list[0].program_id);}else{const created=await VisionAppAPI.newProgram('Vision Program');setPrograms([{...created.program,master_exists:false}]);setProgram(created.program);}}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Computer Vision init failed');}finally{setBusy(false);}})();},[]);
 useEffect(()=>{if(!program||!runner?.armed)return;const id=window.setInterval(()=>void VisionAppAPI.runnerStatus(program.program_id).then(setRunner).catch(()=>{}),1000);return()=>window.clearInterval(id);},[program?.program_id,runner?.armed]);
 const patch=(next:VisionProgramDefinition)=>setProgram(next);
 const save=async()=>{if(!program)return;try{setBusy(true);const saved=await VisionAppAPI.saveProgram(program);setProgram(saved);await refreshList(saved.program_id);}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Save failed');}finally{setBusy(false);}};
 const create=async()=>{const name=window.prompt('New Vision Program name','Vision Program');if(!name)return;try{setBusy(true);const created=await VisionAppAPI.newProgram(name);await refreshList(created.program.program_id);}catch(e:any){setError(e?.message||'Create failed');}finally{setBusy(false);}};
 const removeProgram=async()=>{if(!program)return;if(!window.confirm(`Remove Vision Program "${program.name}"? This deletes its saved program and Master Sample.`))return;try{setBusy(true);await VisionAppAPI.removeProgram(program.program_id);const list=await VisionAppAPI.listPrograms();if(list.length){setPrograms(list);await loadProgram(list[0].program_id);}else{const created=await VisionAppAPI.newProgram('Vision Program');setPrograms([{...created.program,master_exists:false}]);setProgram(created.program);setMasterUrl(null);}}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Remove failed');}finally{setBusy(false);}};
 const switchProgram=async(id:string)=>{try{setBusy(true);await loadProgram(id);}catch(e:any){setError(e?.message||'Load failed');}finally{setBusy(false);}};
 const uploadMaster=async(file:File)=>{if(!program)return;try{setBusy(true);await VisionAppAPI.uploadMaster(program.program_id,file);await loadProgram(program.program_id);}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Master upload failed');}finally{setBusy(false);}};
 const previewBlur=async()=>{if(!program)return;try{setBusy(true);const blob=await VisionAppAPI.masterBlurPreview(program.program_id,program.master.locator.blur_kernel);setMasterBlurUrl(old=>{if(old)URL.revokeObjectURL(old);return URL.createObjectURL(blob);});setMasterView('blur');}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Blur preview failed');}finally{setBusy(false);}};
 const addRoi=(rect:NormalizedRect)=>{if(!program)return;const roi=roiDefault(rect,program.master.rois.length);patch({...program,master:{...program.master,rois:[...program.master.rois,roi]}});setSelectedRoi(roi.roi_id);setDrawMode(false);};
 const updateRoi=(roi:MasterRoi)=>{if(!program)return;patch({...program,master:{...program.master,rois:program.master.rois.map(r=>r.roi_id===roi.roi_id?roi:r)}});};
 const removeRoi=(id:string)=>{if(!program)return;const scopes={...program.working.station_scopes};delete scopes[id];patch({...program,master:{...program.master,rois:program.master.rois.filter(r=>r.roi_id!==id)},working:{...program.working,station_scopes:scopes}});if(selectedRoi===id)setSelectedRoi(null);};
 const locate=async()=>{if(!program||!testBlob)return;try{setBusy(true);await VisionAppAPI.saveProgram(program);setLocated(await VisionAppAPI.locateRois(program.program_id,testBlob));}catch(e:any){setError(e?.response?.data?.detail||e?.message||'ROI locate failed');}finally{setBusy(false);}};
 const runTest=async()=>{if(!program||!testBlob)return;try{setBusy(true);await VisionAppAPI.saveProgram(program);const result=await VisionAppAPI.runTest(program.program_id,testBlob);setRun(result);setLocated(result.located_rois);}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Working test failed');}finally{setBusy(false);}};
 const loadDebug=async(runId:string,key:string)=>{const blob=await VisionAppAPI.debugImage(runId,key);return URL.createObjectURL(blob);};
 const openRunDebug=()=>{if(!run)return;setDebugSession({runId:run.run_id,items:run.debug_images,benchmarks:run.benchmarks,runResult:run,title:'Inspection Debug Stack'});setDebugOpen(true);};
 const previewScopeDebug=async(scopeId:string)=>{if(!program||!testBlob){setError('Choose/capture a test image before debugging a Filter stack');return;}try{setBusy(true);await VisionAppAPI.saveProgram(program);const preview=await VisionAppAPI.previewScope(program.program_id,scopeId,testBlob);setDebugSession({runId:preview.run_id,items:preview.debug_images,benchmarks:preview.benchmarks??[],runResult:null,title:`${scopeId==='global'?'Global':(program.master.rois.find(r=>r.roi_id===scopeId)?.name??scopeId)} · Filter Preview`});setDebugOpen(true);}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Filter debug preview failed');}finally{setBusy(false);}};
 const capture=async()=>{if(!program)return;try{setBusy(true);await VisionAppAPI.saveProgram(program);const blob=await VisionAppAPI.captureCamera(program.program_id);setBlobAsTest(blob,`camera-${Date.now()}.jpg`);setCameraUrl(old=>{if(old)URL.revokeObjectURL(old);return URL.createObjectURL(blob);});}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Camera capture failed');}finally{setBusy(false);}};
 const readTrigger=async()=>{if(!program)return;try{setBusy(true);setTriggerState(await VisionAppAPI.readTrigger(program.program_id));}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Trigger read failed');}finally{setBusy(false);}};
 const pulse=async(result:'ok'|'ng')=>{if(!program)return;try{setBusy(true);await VisionAppAPI.pulse(program.program_id,result,program.io.pulse_seconds);}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Output pulse failed');}finally{setBusy(false);}};
 const toggleRunner=async()=>{if(!program)return;try{await VisionAppAPI.saveProgram(program);setRunner(runner?.armed?await VisionAppAPI.runnerStop(program.program_id):await VisionAppAPI.runnerStart(program.program_id));}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Runner action failed');}};
 const clearWorking=()=>{setRun(null);setLocated([]);setTestBlob(null);setTestName('');setTestUrl(old=>{if(old)URL.revokeObjectURL(old);return null;});setDebugOpen(false);setDebugSession({runId:null,items:[],benchmarks:[],runResult:null,title:'Working Debug Stack'});};
 const executeAction=async(action:ControlPrimitiveAction)=>{if(action==='trigger_camera'){await capture();return;}if(action==='run_inspection'){if(!testBlob&&program.camera.driver!=='manual')await capture();if(testBlob)await runTest();return;}if(action==='out_ok'){await pulse('ok');return;}if(action==='out_ng'){await pulse('ng');return;}if(action==='clear_working_screen'){clearWorking();}};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(!program)return;const hit=program.control.bindings.filter(b=>b.enabled&&b.source==='keyboard'&&b.key.toLowerCase()===e.key.toLowerCase());if(hit.length){e.preventDefault();void Promise.all(hit.map(b=>executeAction(b.action)));}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[program,testBlob]);
 useEffect(()=>{if(!cameraLive||module!=='camera'||!program||program.camera.driver==='manual')return;let stopped=false;const tick=async()=>{try{const blob=await VisionAppAPI.captureCamera(program.program_id);if(stopped)return;setCameraUrl(old=>{if(old)URL.revokeObjectURL(old);return URL.createObjectURL(blob);});}catch{} };void tick();const id=window.setInterval(()=>void tick(),700);return()=>{stopped=true;window.clearInterval(id);};},[cameraLive,module,program?.program_id,program?.camera.driver]);
 useEffect(()=>{if(module!=='working')setDebugOpen(false);if(module!=='master')setMasterView('original');},[module]);
 const viewportUrl=module==='master'?(masterView==='blur'?(masterBlurUrl??masterUrl):masterUrl):module==='camera'?(cameraUrl??testUrl):module==='working'?(testUrl??masterUrl):null;const viewportRois=module==='master'&&masterView==='original'?(program?.master.rois??[]):[];const locatedForView=module==='working'?located:[];
 if(!program)return <div className="flex h-screen items-center justify-center bg-[#202124] text-[#e8eaed]">{busy?<Loader2 className="animate-spin"/>:'No program'}</div>;
 return <div className="flex h-screen w-screen flex-col overflow-hidden bg-[#202124] text-[#e8eaed]">
  <header className="flex h-14 shrink-0 items-center gap-2 border-b border-[#3c4043] bg-[#292a2d] px-3"><button onClick={()=>navigate('/')} className="cv-btn"><ArrowLeft size={12}/></button><Sparkles size={16} className="text-[#c58af9]"/><div><div className="text-xs font-black tracking-[.15em]">COMPUTER VISION</div><div className="text-[7px] text-[#80868b]">Control Mapper → Camera → Global Filter/Logic → ROI locator → Station Filter/Logic → future IDE Decision</div></div><select value={program.program_id} onChange={e=>void switchProgram(e.target.value)} className="ml-2 w-[190px] rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[9px]">{programs.map(p=><option key={p.program_id} value={p.program_id}>{p.name}</option>)}</select><button onClick={()=>void create()} className="cv-btn">New</button><button onClick={()=>void removeProgram()} className="cv-btn border-[#f28b82] text-[#f28b82]"><Trash2 size={11}/>Remove</button><input value={program.name} onChange={e=>patch({...program,name:e.target.value})} className="w-[170px] rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[9px]"/><button onClick={()=>void save()} className="cv-btn border-[#81c995] text-[#81c995]"><Save size={11}/>Save</button><button className={`cv-btn ${runner?.armed?'border-[#fdd663] text-[#fdd663]':''}`} onClick={()=>void toggleRunner()}><Wifi size={11}/>{runner?.armed?'Disarm Trigger':'Arm Trigger'}</button><div className="ml-auto flex items-center gap-1"><button className="cv-icon" title="Toggle modules" onClick={()=>setLeftOpen(v=>!v)}>{leftOpen?<ChevronLeft size={12}/>:<ChevronRight size={12}/>}</button><button className="cv-icon" title="Toggle operation panel" onClick={()=>setRightOpen(v=>!v)}>{rightOpen?<ChevronRight size={12}/>:<ChevronLeft size={12}/>}</button><label className="cv-btn cursor-pointer"><Upload size={11}/>{testName||'Test image'}<input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)setBlobAsTest(f,f.name);}}/></label><button disabled={!testBlob||busy} onClick={()=>void locate()} className="cv-btn">Locate ROIs</button><button disabled={!testBlob||busy} onClick={()=>void runTest()} className="cv-btn border-[#8ab4f8] bg-[#174ea6]"><Play size={11}/>{busy?'Working…':'Run Test'}</button></div></header>
  {error?<div className="shrink-0 bg-[#5f2120] px-3 py-1 text-[9px] text-[#f28b82]">{error}<button onClick={()=>setError('')} className="ml-3 font-black">dismiss</button></div>:null}
  <main className="flex min-h-0 flex-1">{leftOpen?<aside className="w-[145px] shrink-0 border-r border-[#3c4043] bg-[#292a2d] p-2"><div className="mb-2 text-[8px] font-black text-[#80868b]">PROGRAM MODULES</div>{([{key:'iot',label:'IOT',icon:Cpu},{key:'camera',label:'Camera',icon:Camera},{key:'master',label:'Master Sample',icon:ImageIcon},{key:'working',label:'Working',icon:Box}] as any[]).map(item=>{const Icon=item.icon;return <button key={item.key} onClick={()=>setModule(item.key)} className={`mb-2 flex w-full flex-col items-center gap-2 rounded-lg border px-2 py-3 text-[8px] font-black ${module===item.key?'border-[#c58af9] bg-[#3b3150] text-white':'border-[#3c4043] bg-[#242528] text-[#9aa0a6]'}`}><Icon size={17}/>{item.label}</button>;})}</aside>:null}
   <section className="relative min-w-0 flex-1">{module==='iot'?<IotIdePlaceholder/>:<VisionViewport imageUrl={viewportUrl} rois={viewportRois} located={locatedForView} selectedId={selectedRoi} drawMode={module==='master'&&masterView==='original'&&drawMode} onSelect={setSelectedRoi} onDraw={addRoi}/>} {module==='master'&&program.master.locator.method==='blur_template'?<div className="absolute left-3 top-3 z-20 flex gap-1 rounded border border-[#3c4043] bg-[#202124]/95 p-1"><button className={`cv-debug-tab ${masterView==='original'?'active':''}`} onClick={()=>setMasterView('original')}>Original Master</button><button className={`cv-debug-tab ${masterView==='blur'?'active':''}`} onClick={()=>void previewBlur()}>Blur Preview</button></div>:null}{module==='working'&&run?<div className={`absolute bottom-5 right-5 min-w-[150px] rounded-xl border-2 px-5 py-4 text-center shadow-2xl ${run.overall_ok?'border-[#81c995] bg-[#153d24]/95 text-[#81c995]':'border-[#f28b82] bg-[#5f2120]/95 text-[#f28b82]'}`}><div className="text-[8px] font-black tracking-[.2em]">INSPECTION RESULT</div><div className="mt-1 text-3xl font-black">{run.overall_ok?'OK':'NG'}</div><div className="mt-1 text-[8px]">{run.total_ms.toFixed(1)} ms · {run.stations.length} station(s)</div></div>:null}</section>
   {rightOpen?<aside className="w-[470px] shrink-0 overflow-hidden border-l border-[#3c4043] bg-[#292a2d]"><div className="border-b border-[#3c4043] px-3 py-2 text-[9px] font-black uppercase text-[#c58af9]">{module==='iot'?'IOT / Trigger & Result':module==='camera'?'Camera / Acquisition':module==='master'?'Master Sample / ROI Locator':'Working / Operation & Benchmark'}</div><div className="h-[calc(100%-32px)] overflow-y-auto">{module==='iot'?<IotModulePanel config={program.io} control={program.control} onChange={io=>patch({...program,io})} onControl={control=>patch({...program,control})} onRead={()=>void readTrigger()} onPulse={result=>void pulse(result)} triggerState={triggerState} busy={busy}/>:module==='camera'?<CameraModulePanel config={program.camera} onChange={camera=>patch({...program,camera})} onCapture={()=>void capture()} live={cameraLive} onLive={setCameraLive} onFocus={p=>void VisionAppAPI.focusCamera(program.program_id,p).catch((e:any)=>setError(e?.response?.data?.detail||e?.message))} onScan={async()=>{const r=await VisionAppAPI.scanBasler();if(!r.success)setError(r.error||'Basler scan failed');return r.devices;}} busy={busy}/>:module==='master'?<MasterSamplePanel rois={program.master.rois} locator={program.master.locator} selectedId={selectedRoi} drawMode={drawMode} onDrawMode={setDrawMode} onSelect={setSelectedRoi} onChange={updateRoi} onRemove={removeRoi} onLocator={locator=>patch({...program,master:{...program.master,locator}})} onUpload={file=>void uploadMaster(file)} onBlurPreview={()=>void previewBlur()} onShowOriginal={()=>setMasterView('original')}/>:<WorkingModulePanel services={services} rois={program.master.rois} globalScope={program.working.global_scope} stationScopes={program.working.station_scopes} stationExecution={program.working.station_execution} benchmarks={run?.benchmarks??[]} debugCount={run?.debug_images.length??0} onGlobal={global_scope=>patch({...program,working:{...program.working,global_scope}})} onStations={station_scopes=>patch({...program,working:{...program.working,station_scopes}})} onExecution={station_execution=>patch({...program,working:{...program.working,station_execution}})} onSelectStation={setSelectedRoi} onPreviewDebug={previewScopeDebug} onOpenDebug={openRunDebug}/>}</div></aside>:null}
  </main><footer className="flex h-7 shrink-0 items-center gap-4 border-t border-[#3c4043] bg-[#242528] px-3 text-[8px] text-[#80868b]"><span>Vision App v0.10</span><span>Master ROIs: {program.master.rois.length}</span><span>Locator: {program.master.locator.method}</span><span>Station mode: {program.working.station_execution}</span>{runner?<span>Runner: <b className={runner.armed?'text-[#fdd663]':'text-[#80868b]'}>{runner.armed?'ARMED':'idle'}</b>{runner.last_result?` · last ${runner.last_result}`:''}</span>:null}<span className="ml-auto">Program ID: {program.program_id}</span></footer><DebugWorkspace open={debugOpen} runId={debugSession.runId} items={debugSession.items} benchmarks={debugSession.benchmarks} runResult={debugSession.runResult} title={debugSession.title} onClose={()=>setDebugOpen(false)} load={loadDebug}/>
 </div>;
};
