import { Crosshair, Plus, Trash2, Upload } from 'lucide-react';
import type { MasterRoi } from '../../api/visionAppApi';

type Props={rois:MasterRoi[];selectedId:string|null;drawMode:boolean;onDrawMode:(v:boolean)=>void;onSelect:(id:string)=>void;onChange:(roi:MasterRoi)=>void;onRemove:(id:string)=>void;onUpload:(file:File)=>void};
export const MasterSamplePanel=({rois,selectedId,drawMode,onDrawMode,onSelect,onChange,onRemove,onUpload}:Props)=>{
 const selected=rois.find(r=>r.roi_id===selectedId)??null;
 const patch=(p:Partial<MasterRoi>)=>selected&&onChange({...selected,...p});
 const patchSearch=(p:any)=>selected&&onChange({...selected,search:{...selected.search,...p}});
 const patchGeo=(p:any)=>selected&&onChange({...selected,search:{...selected.search,geometry:{...selected.search.geometry,...p}}});
 return <div className="space-y-3 p-3 text-[9px]">
  <label className="cv-btn cursor-pointer"><Upload size={11}/>Upload / Replace Master<input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(f);}}/></label>
  <button onClick={()=>onDrawMode(!drawMode)} className={`btn w-full ${drawMode?'border-[#8ab4f8] bg-[#174ea6]':''}`}><Crosshair size={11}/>{drawMode?'Draw ROI on image…':'Add ROI by drawing'}</button>
  <div className="rounded-lg border border-[#3c4043] bg-[#242528]"><div className="border-b border-[#3c4043] px-2 py-1.5 text-[8px] font-black">MASTER ROIs / STATIONS</div>{rois.length===0?<div className="p-4 text-center text-[#80868b]">Draw ROIs on the Master Sample.</div>:rois.map(r=><button key={r.roi_id} onClick={()=>onSelect(r.roi_id)} className={`flex w-full items-center gap-2 border-b border-[#3c4043] px-2 py-2 text-left ${selectedId===r.roi_id?'bg-[#3c4043]':''}`}><span className="h-2 w-2 rounded-full bg-[#81c995]"/><span className="flex-1 truncate">{r.name}</span><span className="text-[7px] uppercase text-[#8ab4f8]">{r.search.method}</span></button>)}</div>
  {selected?<div className="space-y-2 rounded-lg border border-[#5f6368] bg-[#242528] p-3"><div className="flex items-center gap-2"><b className="flex-1">ROI SETTINGS</b><button onClick={()=>onRemove(selected.roi_id)} className="text-[#f28b82]"><Trash2 size={12}/></button></div><label>Name<input value={selected.name} onChange={e=>patch({name:e.target.value})} className="cv-field"/></label><label>Search method<select value={selected.search.method} onChange={e=>patchSearch({method:e.target.value})} className="cv-field"><option value="manual">Manual coordinates</option><option value="blur_template">Blur + Template Matching</option><option value="fourier">Fourier Phase Search</option></select></label>{selected.search.method==='blur_template'?<><label>Blur kernel<input type="number" value={selected.search.blur_kernel} onChange={e=>patchSearch({blur_kernel:Number(e.target.value)})} className="cv-field"/></label><label>Match threshold<input type="number" step="0.01" value={selected.search.template_threshold} onChange={e=>patchSearch({template_threshold:Number(e.target.value)})} className="cv-field"/></label></>:null}<div className="border-t border-[#3c4043] pt-2"><label className="flex items-center gap-2"><input type="checkbox" checked={selected.search.geometry.enabled} onChange={e=>patchGeo({enabled:e.target.checked})}/>Geometry constraint</label><div className="mt-1 grid grid-cols-2 gap-2"><label>Search margin px<input type="number" value={selected.search.geometry.search_margin_px} onChange={e=>patchGeo({search_margin_px:Number(e.target.value)})} className="cv-field"/></label><label>Max shift px<input type="number" value={selected.search.geometry.max_shift_px} onChange={e=>patchGeo({max_shift_px:Number(e.target.value)})} className="cv-field"/></label></div></div><div className="text-[7px] leading-4 text-[#80868b]">Manual uses the identical ROI coordinates. Blur+Template searches a locally constrained image region. Fourier v1 uses phase correlation for translation; scale/rotation and multi-ROI geometry graphs are reserved for later versions.</div></div>:null}
 </div>;
};
