import { useEffect, useMemo, useState } from 'react';
import { Braces, CheckCircle2, CirclePlay, CircleStop, FileCode2, FlaskConical, Play, Save, Search, Trash2, WandSparkles, XCircle } from 'lucide-react';
import { VisionAppAPI, type AutomationEndpoint, type AutomationExecutionResult, type AutomationServiceDefinition, type AutomationSystemState, type AutomationTraceEntry, type AutomationValidationIssue, type VisionProgramDefinition } from '../../api/visionAppApi';
import { AutomationCodeEditor } from './AutomationCodeEditor';
import { EndpointObjectTree } from './EndpointObjectTree';

type Props={program:VisionProgramDefinition;onProgram:(next:VisionProgramDefinition)=>void;onSave:()=>Promise<void>|void;onError:(message:string)=>void};
const defaultScript=(mode:AutomationServiceDefinition['mode'])=>mode==='loop'?"if device.modbus_1.X1 == ON:\n    system.run_inspection()\n":mode==='event'?"if event.result == OK:\n    device.modbus_1.Y1.pulse(1.0)\nelse:\n    device.modbus_1.Y2.pulse(1.0)\n":"camera.main.capture()\n";
const serviceTemplate=(mode:AutomationServiceDefinition['mode'],index:number):AutomationServiceDefinition=>({service_id:`auto_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,name:mode==='loop'?`Loop Service ${index}`:mode==='event'?`Event Service ${index}`:`One-shot Service ${index}`,enabled:true,mode,interval_ms:250,event:'system.run_finish',script:defaultScript(mode),timeout_ms:1500,concurrency:'skip'});
const modeColor=(mode:string)=>mode==='loop'?'#81c995':mode==='event'?'#c58af9':'#65d1ff';

export const AutomationIdeWorkspace=({program,onProgram,onSave,onError}:Props)=>{
 const [selectedId,setSelectedId]=useState<string|null>(program.automation.services[0]?.service_id??null);const [endpoints,setEndpoints]=useState<AutomationEndpoint[]>([]);const [trace,setTrace]=useState<AutomationTraceEntry[]>([]);const [state,setState]=useState<AutomationSystemState|null>(null);const [issues,setIssues]=useState<AutomationValidationIssue[]>([]);const [execution,setExecution]=useState<AutomationExecutionResult|null>(null);const [query,setQuery]=useState('');const [bottom,setBottom]=useState<'problems'|'trace'|'variables'>('problems');const [busy,setBusy]=useState(false);const [insertCommand,setInsertCommand]=useState<{id:number;path:string;callable:boolean}|null>(null);
 const service=program.automation.services.find(item=>item.service_id===selectedId)??program.automation.services[0]??null;
 const refresh=async()=>{try{const [ep,tr,st]=await Promise.all([VisionAppAPI.automationEndpointsPreview(program),VisionAppAPI.automationTrace(program.program_id),VisionAppAPI.automationState(program.program_id)]);setEndpoints(ep);setTrace(tr);setState(st);}catch(e:any){onError(e?.response?.data?.detail||e?.message||'Automation IDE refresh failed');}};
 useEffect(()=>{setSelectedId(program.automation.services[0]?.service_id??null);void refresh();},[program.program_id]);
 useEffect(()=>{const id=window.setTimeout(()=>void VisionAppAPI.automationEndpointsPreview(program).then(setEndpoints).catch(()=>{}),180);return()=>window.clearTimeout(id);},[program.iot,program.master.rois,program.working.global_scope.logic_services,program.working.station_scopes]);
 useEffect(()=>{const id=window.setInterval(()=>void VisionAppAPI.automationState(program.program_id).then(setState).catch(()=>{}),700);return()=>window.clearInterval(id);},[program.program_id]);
 useEffect(()=>{if(!state?.scheduler_running)return;const id=window.setInterval(()=>void VisionAppAPI.automationTrace(program.program_id).then(setTrace).catch(()=>{}),700);return()=>window.clearInterval(id);},[program.program_id,state?.scheduler_running]);
 const patchService=(patch:Partial<AutomationServiceDefinition>)=>{if(!service)return;onProgram({...program,automation:{...program.automation,services:program.automation.services.map(item=>item.service_id===service.service_id?{...item,...patch}:item)}});};
 const add=(mode:AutomationServiceDefinition['mode'])=>{const next=serviceTemplate(mode,program.automation.services.length+1);onProgram({...program,automation:{...program.automation,services:[...program.automation.services,next]}});setSelectedId(next.service_id);};
 const remove=()=>{if(!service)return;const services=program.automation.services.filter(item=>item.service_id!==service.service_id);onProgram({...program,automation:{...program.automation,services}});setSelectedId(services[0]?.service_id??null);};
 const validate=async()=>{if(!service)return;try{setBusy(true);const x=await VisionAppAPI.automationValidate(program.program_id,service.script);setIssues(x);setBottom('problems');}catch(e:any){onError(e?.response?.data?.detail||e?.message||'Validate failed');}finally{setBusy(false);}};
 const run=async(dry:boolean)=>{if(!service)return;try{setBusy(true);await onSave();const result=await VisionAppAPI.automationRunService(program.program_id,service.service_id,dry);setExecution(result);setIssues(result.issues);setTrace(await VisionAppAPI.automationTrace(program.program_id));setState(await VisionAppAPI.automationState(program.program_id));setEndpoints(await VisionAppAPI.automationEndpointsPreview(program));setBottom(result.issues.length?'problems':'trace');}catch(e:any){onError(e?.response?.data?.detail||e?.message||'Automation execution failed');}finally{setBusy(false);}};
 const toggleScheduler=async()=>{try{setBusy(true);await onSave();setState(state?.scheduler_running?await VisionAppAPI.automationStop(program.program_id):await VisionAppAPI.automationStart(program.program_id));}catch(e:any){onError(e?.response?.data?.detail||e?.message||'Automation scheduler action failed');}finally{setBusy(false);}};
 const requestInsert=(endpoint:AutomationEndpoint)=>setInsertCommand({id:Date.now()+Math.random(),path:endpoint.path,callable:endpoint.callable});
 const objectCounts=useMemo(()=>({devices:program.iot.devices.filter(d=>d.enabled).length,rois:program.master.rois.filter(r=>r.enabled).length,endpoints:endpoints.length}),[program.iot.devices,program.master.rois,endpoints]);
 return <div className="cv-ide h-full min-h-0 bg-[#15171b] text-[#e8eaed]">
  <div className="flex h-11 items-center gap-2 border-b border-[#343941] bg-gradient-to-r from-[#252735] via-[#22252b] to-[#1f282b] px-3 text-[9px]"><div className="rounded-md bg-[#c58af91a] p-1.5"><Braces size={14} className="text-[#c58af9]"/></div><div><b className="tracking-[.14em]">AUTOMATION IDE</b><div className="text-[6px] text-[#87909a]">Live Object Graph · Safe DSL · Endpoint Registry</div></div><div className="ml-3 flex gap-1 text-[6px]"><span className="rounded bg-[#fdd66318] px-2 py-1 text-[#fdd663]">{objectCounts.devices} device</span><span className="rounded bg-[#ff8ab418] px-2 py-1 text-[#ff8ab4]">{objectCounts.rois} ROI</span><span className="rounded bg-[#65d1ff18] px-2 py-1 text-[#65d1ff]">{objectCounts.endpoints} endpoints</span></div><div className="ml-auto flex items-center gap-1"><button className="cv-btn" onClick={()=>void validate()} disabled={!service||busy}><CheckCircle2 size={10}/>Validate</button><button className="cv-btn border-[#fdd663] text-[#fdd663]" onClick={()=>void run(true)} disabled={!service||busy}><FlaskConical size={10}/>Dry Run</button><button className="cv-btn border-[#65d1ff] text-[#65d1ff]" onClick={()=>void run(false)} disabled={!service||busy}><Play size={10}/>Run Service</button><button className={`cv-btn ${state?.scheduler_running?'border-[#f28b82] text-[#f28b82]':'border-[#81c995] text-[#81c995]'}`} onClick={()=>void toggleScheduler()} disabled={busy}>{state?.scheduler_running?<CircleStop size={10}/>:<CirclePlay size={10}/>} {state?.scheduler_running?'Stop Scheduler':'Start Scheduler'}</button><button className="cv-btn" onClick={()=>void onSave()}><Save size={10}/>Save</button></div></div>
  <div className="grid h-[calc(100%-44px)] min-h-0 grid-cols-[250px_minmax(0,1fr)_300px] grid-rows-[minmax(0,1fr)_190px]">
   <aside className="row-span-2 overflow-y-auto border-r border-[#343941] bg-[#1b1e23]"><div className="border-b border-[#343941] p-2"><div className="mb-2 text-[8px] font-black text-[#8f99a4]">AUTOMATION SERVICES</div><div className="grid grid-cols-3 gap-1"><button className="cv-mini border-[#81c99555] text-[#81c995]" onClick={()=>add('loop')}>+ Loop</button><button className="cv-mini border-[#c58af955] text-[#c58af9]" onClick={()=>add('event')}>+ Event</button><button className="cv-mini border-[#65d1ff55] text-[#65d1ff]" onClick={()=>add('oneshot')}>+ One-shot</button></div></div><div className="p-1">{program.automation.services.length?program.automation.services.map(s=>{const c=modeColor(s.mode);return <button key={s.service_id} onClick={()=>setSelectedId(s.service_id)} className={`mb-1 w-full rounded-lg border p-2 text-left transition ${s.service_id===service?.service_id?'bg-[#252e38] shadow-[inset_3px_0_0_var(--mode)]':'border-[#30353c] bg-[#202329] hover:bg-[#262a31]'}`} style={{['--mode' as any]:c,borderColor:s.service_id===service?.service_id?c:'#30353c'}}><div className="flex items-center gap-2"><FileCode2 size={11} style={{color:c}}/><b className="truncate text-[9px]">{s.name}</b><span className="ml-auto rounded px-1.5 py-0.5 text-[6px] font-black" style={{background:`${c}18`,color:c}}>{s.mode}</span></div><div className="mt-1 truncate text-[7px] text-[#74808b]">{s.mode==='loop'?`every ${s.interval_ms} ms`:s.mode==='event'?s.event:'manual / callable'}</div></button>}):<div className="p-5 text-center text-[8px] text-[#6f7882]">No Automation service yet.<br/>Add Loop, Event or One-shot.</div>}</div></aside>
   <section className="min-w-0 overflow-hidden bg-[#111317]">{service?<><div className="flex h-12 items-center gap-2 border-b border-[#343941] bg-[#202329] px-2"><input className="cv-field !mt-0 min-w-[190px]" value={service.name} onChange={e=>patchService({name:e.target.value})}/><select className="cv-field !mt-0 w-[90px]" value={service.mode} onChange={e=>patchService({mode:e.target.value as any,script:service.script.trim()?service.script:defaultScript(e.target.value as any)})}><option value="loop">Loop</option><option value="event">Event</option><option value="oneshot">One-shot</option></select>{service.mode==='loop'?<><span className="text-[7px] text-[#80868b]">every</span><input type="number" className="cv-field !mt-0 w-[80px]" value={service.interval_ms} onChange={e=>patchService({interval_ms:Number(e.target.value)})}/><span className="text-[7px] text-[#80868b]">ms</span></>:service.mode==='event'?<select className="cv-field !mt-0 min-w-[190px]" value={service.event} onChange={e=>patchService({event:e.target.value})}>{endpoints.filter(e=>e.kind==='event').map(e=><option key={e.path}>{e.path}</option>)}</select>:null}<label className="ml-auto flex items-center gap-1 text-[8px]"><input type="checkbox" checked={service.enabled} onChange={e=>patchService({enabled:e.target.checked})}/>Enabled</label><button className="cv-icon text-[#f28b82]" onClick={remove}><Trash2 size={11}/></button></div><div className="h-[calc(100%-48px)]"><AutomationCodeEditor value={service.script} onChange={script=>patchService({script})} endpoints={endpoints} insertCommand={insertCommand}/></div></>:<div className="flex h-full items-center justify-center"><div className="max-w-[520px] text-center"><WandSparkles size={30} className="mx-auto mb-3 text-[#c58af9]"/><div className="text-sm font-black">Create an Automation Service</div><div className="mt-2 text-[8px] leading-5 text-[#9aa0a6]">Declared devices, ROIs and Logic aliases appear automatically as real typed objects.</div></div></div>}</section>
   <aside className="row-span-2 overflow-y-auto border-l border-[#343941] bg-[#1b1e23]"><div className="sticky top-0 z-10 border-b border-[#343941] bg-[#1b1e23]/95 p-2 backdrop-blur"><div className="flex items-center gap-2 text-[8px] font-black text-[#9aa0a6]"><Search size={10}/>OBJECT / ENDPOINT EXPLORER</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search device / ROI / output..." className="cv-field"/><div className="mt-1 text-[6px] text-[#626c76]">Click a leaf to insert it into the editor. Objects exist from declarations; runtime values enrich them after inspection.</div></div><EndpointObjectTree endpoints={endpoints} query={query} onInsert={requestInsert}/></aside>
   <div className="col-start-2 row-start-2 min-w-0 border-t border-[#343941] bg-[#171a1f]"><div className="flex h-8 items-center gap-1 border-b border-[#2d3239] px-2">{(['problems','trace','variables'] as const).map(t=><button key={t} onClick={()=>setBottom(t)} className={`cv-debug-tab ${bottom===t?'active':''}`}>{t==='problems'?`PROBLEMS ${issues.length?`(${issues.length})`:''}`:t==='trace'?`EXECUTION TRACE (${trace.length})`:'VARIABLES'}</button>)}<button className="ml-auto cv-mini" onClick={()=>void refresh()}>Refresh objects</button>{bottom==='trace'?<button className="cv-mini" onClick={()=>void VisionAppAPI.automationClearTrace(program.program_id).then(()=>setTrace([]))}>Clear</button>:null}</div><div className="h-[calc(100%-32px)] overflow-auto p-2 font-mono text-[8px]">{bottom==='problems'?(issues.length?issues.map((x,i)=><div key={i} className="mb-1 flex gap-2 text-[#f28b82]"><XCircle size={9}/><span>L{x.line}:{x.column} {x.message}</span></div>):<div className="text-[#81c995]">No validation problems.</div>):bottom==='trace'?(trace.length?trace.slice().reverse().map((x,i)=><div key={i} className={`mb-1 grid grid-cols-[145px_120px_1fr] gap-2 ${x.level==='error'?'text-[#f28b82]':x.dry_run?'text-[#fdd663]':'text-[#9aa0a6]'}`}><span>{x.timestamp.slice(11,23)}</span><span>{x.service_name||x.service_id||'system'}</span><span>{x.message}{x.endpoint?` · ${x.endpoint}`:''}{x.value!=null?` · ${JSON.stringify(x.value)}`:''}</span></div>):<div className="text-[#80868b]">No execution trace yet.</div>):<div className="grid grid-cols-2 gap-2 text-[8px]"><div className="rounded border border-[#343941] bg-[#202329] p-2"><b>system.run_state</b><div className="mt-1 text-[#65d1ff]">{state?.run_state??'IDLE'}</div></div><div className="rounded border border-[#343941] bg-[#202329] p-2"><b>system.result</b><div className={`mt-1 ${state?.result==='OK'?'text-[#81c995]':state?.result==='NG'?'text-[#f28b82]':'text-[#9aa0a6]'}`}>{state?.result??'NONE'}</div></div><div className="rounded border border-[#343941] bg-[#202329] p-2"><b>system.run_id</b><div className="mt-1 truncate text-[#9aa0a6]">{state?.run_id||'—'}</div></div><div className="rounded border border-[#343941] bg-[#202329] p-2"><b>last event</b><div className="mt-1 text-[#c58af9]">{state?.last_event||'—'}</div></div>{execution?<div className="col-span-2 rounded border border-[#343941] bg-[#202329] p-2"><b>Last manual execution</b><div className={execution.ok?'text-[#81c995]':'text-[#f28b82]'}>{execution.ok?'OK':'FAILED'}{execution.dry_run?' · DRY RUN':''}</div></div>:null}</div>}</div></div>
  </div>
 </div>;
};
