import { Activity, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Box, Braces, Camera, ChevronLeft, ChevronRight, Cpu, CirclePlay, CircleStop, Image as ImageIcon, Loader2, Play, Save, Sparkles, Trash2, Upload } from 'lucide-react';
import { LabServiceAPI, type LabServiceDefinition } from '../api/labServiceApi';
import { VisionAppAPI, type AutomationSystemState, type BenchmarkStep, type DebugImageRef, type LocatedRoi, type MasterRoi, type NormalizedRect, type VisionProgramDefinition, type VisionRunResult, type WorkspaceDefinition } from '../api/visionAppApi';
import { VisionViewport } from '../components/ComputerVision/VisionViewport';
import { MasterSamplePanel } from '../components/ComputerVision/MasterSamplePanel';
import { WorkingModulePanel } from '../components/ComputerVision/WorkingModulePanel';
import { DebugWorkspace } from '../components/ComputerVision/DebugWorkspace';
import { AutomationIdeWorkspace } from '../components/ComputerVision/AutomationIdeWorkspace';
import { IotDeclarationWorkspace } from '../components/ComputerVision/IotDeclarationWorkspace';
import { CameraDeclarationWorkspace } from '../components/ComputerVision/CameraDeclarationWorkspace';
import { StreamingWorkspace } from '../components/ComputerVision/StreamingWorkspace';
import { WorkspaceTabs } from '../components/ComputerVision/WorkspaceTabs';
import '../components/ComputerVision/ComputerVision.css';

type ModuleKey='iot'|'camera'|'streaming'|'master'|'working'|'ide';
const safe=(v:string)=>v.trim().replace(/[^A-Za-z0-9_]+/g,'_').replace(/^([0-9])/,'_$1')||'workspace';
const roiDefault=(rect:NormalizedRect,index:number):MasterRoi=>({roi_id:`roi_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,name:`Station ${index+1}`,alias:`ROI${index+1}`,rect,enabled:true});
const freshWorkspace=(index:number):WorkspaceDefinition=>({
 workspace_id:`workspace_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,
 name:`Workspace ${index}`,
 alias:`workspace_${index}`,
 enabled:true,
 iot:{devices:[]},
 cameras:{devices:[]},
 camera_id:'',
 input_binding:'',
 master:{rois:[],master_shape:[],locator:{method:'manual',blur_kernel:9,template_threshold:.65,geometry:{enabled:true,search_margin_px:80,max_shift_px:120}}},
 working:{global_scope:{enable_filter:true,filter_services:[],enable_logic:true,logic_services:[],enable_decision:false,decision:{script:''}},station_scopes:{},station_execution:'sequential',global_services:[],station_services:{}},
 soft_trigger:{enabled:false,roi:null,threshold_mode:'bright',pixel_threshold:80,trigger_pixel_count:100,reset_pixel_count:20,frame_stride:1,cooldown_ms:500,snapshot_to_image_slot:true,run_inspection:true},
});

export const ComputerVisionPage=()=>{
 const navigate=useNavigate();const [module,setModule]=useState<ModuleKey>('working');const [programs,setPrograms]=useState<(VisionProgramDefinition&{master_exists?:boolean})[]>([]);const [program,setProgram]=useState<VisionProgramDefinition|null>(null);const [activeId,setActiveId]=useState('workspace_1');const [services,setServices]=useState<LabServiceDefinition[]>([]);const [masterUrl,setMasterUrl]=useState<string|null>(null);const [masterBlurUrl,setMasterBlurUrl]=useState<string|null>(null);const [testBlob,setTestBlob]=useState<Blob|null>(null);const [testName,setTestName]=useState('');const [testUrl,setTestUrl]=useState<string|null>(null);const [located,setLocated]=useState<LocatedRoi[]>([]);const [run,setRun]=useState<VisionRunResult|null>(null);const [selectedRoi,setSelectedRoi]=useState<string|null>(null);const [drawMode,setDrawMode]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [leftOpen,setLeftOpen]=useState(true);const [rightOpen,setRightOpen]=useState(true);const [masterView,setMasterView]=useState<'original'|'blur'>('original');const [automationState,setAutomationState]=useState<AutomationSystemState|null>(null);const automationFrameSeq=useRef(0);const automationClearSeq=useRef(0);const workspaceActivationSeq=useRef(0);const masterLoadSeq=useRef(0);const keyboardActive=useRef<Set<string>>(new Set());const [debugOpen,setDebugOpen]=useState(false);const [debugSession,setDebugSession]=useState<{runId:string|null;items:DebugImageRef[];benchmarks:BenchmarkStep[];runResult:VisionRunResult|null;title:string}>({runId:null,items:[],benchmarks:[],runResult:null,title:'Working Debug Stack'});
 const activeWorkspace=useMemo(()=>program?.workspaces.find(w=>w.workspace_id===activeId)??program?.workspaces[0]??null,[program,activeId]);const wsAlias=activeWorkspace?safe(activeWorkspace.alias):'workspace_1';
 const enabledCameras=useMemo(()=>activeWorkspace?.cameras.devices.filter(c=>c.enabled)??[],[activeWorkspace?.workspace_id,activeWorkspace?.cameras.devices]);
 const activeCamera=useMemo(()=>activeWorkspace?activeWorkspace.cameras.devices.find(c=>c.declaration_id===activeWorkspace.camera_id)??null:null,[activeWorkspace?.workspace_id,activeWorkspace?.cameras.devices,activeWorkspace?.camera_id]);
 const patch=(next:VisionProgramDefinition)=>setProgram(next);
 const resetWorkspaceUi=()=>{masterLoadSeq.current+=1;setMasterUrl(old=>{if(old)URL.revokeObjectURL(old);return null;});setMasterBlurUrl(old=>{if(old)URL.revokeObjectURL(old);return null;});setTestBlob(null);setTestName('');setTestUrl(old=>{if(old)URL.revokeObjectURL(old);return null;});setLocated([]);setRun(null);setSelectedRoi(null);setDrawMode(false);setMasterView('original');setDebugOpen(false);};
 const patchWorkspace=(fn:(w:WorkspaceDefinition)=>WorkspaceDefinition)=>{if(!program||!activeWorkspace)return;const workspaces=program.workspaces.map(w=>w.workspace_id===activeWorkspace.workspace_id?fn(w):w);setProgram({...program,active_workspace_id:activeWorkspace.workspace_id,workspaces});};
 const setBlobAsTest=(blob:Blob,name:string)=>{setTestBlob(blob);setTestName(name);setLocated([]);setRun(null);setTestUrl(old=>{if(old)URL.revokeObjectURL(old);return URL.createObjectURL(blob);});if(program&&activeWorkspace)void VisionAppAPI.automationSetLatestFrame(program.program_id,blob,wsAlias).catch(()=>{});};
 const loadMaster=async(id:string,workspaceId:string)=>{const seq=++masterLoadSeq.current;try{const blob=await VisionAppAPI.masterPreview(id,workspaceId);if(seq!==masterLoadSeq.current)return;setMasterUrl(old=>{if(old)URL.revokeObjectURL(old);return URL.createObjectURL(blob);});}catch{if(seq!==masterLoadSeq.current)return;setMasterUrl(old=>{if(old)URL.revokeObjectURL(old);return null;});}};
 const loadProgram=async(id:string)=>{const loaded=await VisionAppAPI.getProgram(id);setProgram(loaded.program);const ws=loaded.program.workspaces.find(w=>w.workspace_id===loaded.program.active_workspace_id)??loaded.program.workspaces[0];setActiveId(ws?.workspace_id??'workspace_1');setLocated([]);setRun(null);setSelectedRoi(null);setDebugOpen(false);setTestBlob(null);setTestUrl(null);setMasterBlurUrl(null);setMasterView('original');const ast=await VisionAppAPI.automationState(id);setAutomationState(ast);automationFrameSeq.current=ast.frame_sequence;automationClearSeq.current=ast.clear_sequence;workspaceActivationSeq.current=ast.workspace_activation_sequence??0;if(ws)await loadMaster(id,ws.workspace_id);};
 const refreshList=async(selectId?:string)=>{const list=await VisionAppAPI.listPrograms();setPrograms(list);const id=selectId??program?.program_id??list[0]?.program_id;if(id)await loadProgram(id);};
 useEffect(()=>{void(async()=>{try{setBusy(true);const [list,svc]=await Promise.all([VisionAppAPI.listPrograms(),LabServiceAPI.list()]);setServices(svc);if(list.length){setPrograms(list);await loadProgram(list[0].program_id);}else{const created=await VisionAppAPI.newProgram('Vision Program');setProgram(created.program);setPrograms([created.program]);}}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Computer Vision init failed');}finally{setBusy(false);}})();},[]);
 useEffect(()=>{if(!program)return;let stopped=false;const sync=async()=>{try{const st=await VisionAppAPI.automationState(program.program_id);if(stopped)return;setAutomationState(st);if((st.workspace_activation_sequence??0)>workspaceActivationSeq.current){workspaceActivationSeq.current=st.workspace_activation_sequence??0;const requested=program.workspaces.find(w=>safe(w.alias)===st.active_workspace);if(requested&&requested.workspace_id!==activeId){setActiveId(requested.workspace_id);setProgram(prev=>prev?{...prev,active_workspace_id:requested.workspace_id}:prev);}}if(st.clear_sequence>automationClearSeq.current){automationClearSeq.current=st.clear_sequence;clearWorking();}if(st.frame_sequence>automationFrameSeq.current){automationFrameSeq.current=st.frame_sequence;try{const blob=await VisionAppAPI.automationLatestFrame(program.program_id,wsAlias);if(!stopped)setBlobAsTest(blob,`automation-frame-${st.frame_sequence}.jpg`);}catch{}}}catch{}};const id=window.setInterval(()=>void sync(),700);return()=>{stopped=true;window.clearInterval(id);};},[program?.program_id,activeId]);
 useEffect(()=>{resetWorkspaceUi();if(program&&activeWorkspace)void loadMaster(program.program_id,activeWorkspace.workspace_id);},[activeId]);
 useEffect(()=>{if(!program)return;const keyName=(key:string)=>{const k=key.toLowerCase();return k===' '?'space':k==='arrowup'?'arrow_up':k==='arrowdown'?'arrow_down':k==='arrowleft'?'arrow_left':k==='arrowright'?'arrow_right':k;};const editable=(target:EventTarget|null)=>{const el=target as HTMLElement|null;return !!el&&(el.tagName==='INPUT'||el.tagName==='TEXTAREA'||el.tagName==='SELECT'||el.isContentEditable);};const down=(e:KeyboardEvent)=>{if(editable(e.target)||e.repeat)return;const key=keyName(e.key);keyboardActive.current.add(key);void VisionAppAPI.automationKeyboard(program.program_id,key,true).then(setAutomationState).catch(()=>{});};const up=(e:KeyboardEvent)=>{const key=keyName(e.key);if(!keyboardActive.current.has(key))return;keyboardActive.current.delete(key);void VisionAppAPI.automationKeyboard(program.program_id,key,false).then(setAutomationState).catch(()=>{});};window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);keyboardActive.current.clear();};},[program?.program_id]);
 const activateWorkspaceTab=async(id:string)=>{if(!program)return;const target=program.workspaces.find(w=>w.workspace_id===id);if(!target)return;resetWorkspaceUi();setActiveId(id);setProgram(prev=>prev?{...prev,active_workspace_id:id}:prev);try{const st=await VisionAppAPI.activateWorkspace(program.program_id,safe(target.alias));workspaceActivationSeq.current=st.workspace_activation_sequence??workspaceActivationSeq.current;setAutomationState(st);}catch{/* Local workspace remains selected; next Save persists it. */}};
 const addWorkspace=async()=>{if(!program)return;const workspace=freshWorkspace(program.workspaces.length+1);const next={...program,workspaces:[...program.workspaces,workspace],active_workspace_id:workspace.workspace_id};resetWorkspaceUi();setProgram(next);setActiveId(workspace.workspace_id);try{setBusy(true);const saved=await VisionAppAPI.saveProgram(next);setProgram(saved);setPrograms(await VisionAppAPI.listPrograms());const st=await VisionAppAPI.activateWorkspace(saved.program_id,safe(workspace.alias));workspaceActivationSeq.current=st.workspace_activation_sequence??workspaceActivationSeq.current;setAutomationState(st);await loadMaster(saved.program_id,workspace.workspace_id);}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Workspace creation failed');}finally{setBusy(false);}};
 const removeWorkspace=async(id:string)=>{if(!program||program.workspaces.length<=1)return;const remaining=program.workspaces.filter(w=>w.workspace_id!==id);const nextId=activeId===id?(remaining[0]?.workspace_id??'workspace_1'):activeId;const next={...program,workspaces:remaining,active_workspace_id:nextId};resetWorkspaceUi();setProgram(next);setActiveId(nextId);try{setBusy(true);const saved=await VisionAppAPI.saveProgram(next);setProgram(saved);setPrograms(await VisionAppAPI.listPrograms());const target=saved.workspaces.find(w=>w.workspace_id===nextId)??saved.workspaces[0];if(target){const st=await VisionAppAPI.activateWorkspace(saved.program_id,safe(target.alias));workspaceActivationSeq.current=st.workspace_activation_sequence??workspaceActivationSeq.current;setAutomationState(st);await loadMaster(saved.program_id,target.workspace_id);}}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Workspace removal failed');}finally{setBusy(false);}};
 const save=async()=>{if(!program)return;try{setBusy(true);const saved=await VisionAppAPI.saveProgram({...program,active_workspace_id:activeId});setProgram(saved);setPrograms(await VisionAppAPI.listPrograms());}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Save failed');}finally{setBusy(false);}};
 const create=async()=>{const name=window.prompt('New Vision Program name','Vision Program');if(!name)return;try{const created=await VisionAppAPI.newProgram(name);await refreshList(created.program.program_id);}catch(e:any){setError(e?.message||'Create failed');}};
 const removeProgram=async()=>{if(!program||!window.confirm(`Remove Vision Program "${program.name}"?`))return;try{await VisionAppAPI.removeProgram(program.program_id);const list=await VisionAppAPI.listPrograms();if(list.length){setPrograms(list);await loadProgram(list[0].program_id);}else{const c=await VisionAppAPI.newProgram('Vision Program');setProgram(c.program);setPrograms([c.program]);}}catch(e:any){setError(e?.message||'Remove failed');}};
 const uploadMaster=async(file:File)=>{if(!program||!activeWorkspace)return;try{setBusy(true);await VisionAppAPI.uploadMaster(program.program_id,file,activeWorkspace.workspace_id);await loadMaster(program.program_id,activeWorkspace.workspace_id);}catch(e:any){setError(e?.message||'Master upload failed');}finally{setBusy(false);}};
 const previewBlur=async()=>{if(!program||!activeWorkspace)return;try{const blob=await VisionAppAPI.masterBlurPreview(program.program_id,activeWorkspace.master.locator.blur_kernel,activeWorkspace.workspace_id);setMasterBlurUrl(old=>{if(old)URL.revokeObjectURL(old);return URL.createObjectURL(blob);});setMasterView('blur');}catch(e:any){setError(e?.message||'Blur preview failed');}};
 const addRoi=(rect:NormalizedRect)=>{if(!activeWorkspace)return;const roi=roiDefault(rect,activeWorkspace.master.rois.length);patchWorkspace(w=>({...w,master:{...w.master,rois:[...w.master.rois,roi]}}));setSelectedRoi(roi.roi_id);setDrawMode(false);};
 const updateRoi=(roi:MasterRoi)=>patchWorkspace(w=>({...w,master:{...w.master,rois:w.master.rois.map(r=>r.roi_id===roi.roi_id?roi:r)}}));
 const removeRoi=(id:string)=>{patchWorkspace(w=>{const scopes={...w.working.station_scopes};delete scopes[id];return {...w,master:{...w.master,rois:w.master.rois.filter(r=>r.roi_id!==id)},working:{...w.working,station_scopes:scopes}};});if(selectedRoi===id)setSelectedRoi(null);};
 const locate=async()=>{if(!program||!activeWorkspace||!testBlob)return;try{setBusy(true);await VisionAppAPI.saveProgram({...program,active_workspace_id:activeId});setLocated(await VisionAppAPI.locateRois(program.program_id,testBlob,activeWorkspace.workspace_id));}catch(e:any){setError(e?.message||'ROI locate failed');}finally{setBusy(false);}};
 const runTest=async()=>{if(!program||!activeWorkspace)return;try{setBusy(true);await VisionAppAPI.saveProgram({...program,active_workspace_id:activeId});const result=testBlob?await VisionAppAPI.runTest(program.program_id,testBlob,activeWorkspace.workspace_id):await VisionAppAPI.runWorkspaceBound(program.program_id,wsAlias);setRun(result);setLocated(result.located_rois);if(!testBlob){try{const blob=await VisionAppAPI.automationLatestFrame(program.program_id,wsAlias);setBlobAsTest(blob,`${wsAlias}-bound-frame.jpg`);}catch{}}}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Workspace inspection failed');}finally{setBusy(false);}};
 const previewScopeDebug=async(scopeId:string)=>{if(!program||!activeWorkspace)return;try{setBusy(true);await VisionAppAPI.saveProgram(program);const preview=await VisionAppAPI.previewScope(program.program_id,scopeId,testBlob,activeWorkspace.workspace_id);setDebugSession({runId:preview.run_id,items:preview.debug_images,benchmarks:preview.benchmarks,runResult:null,title:`${activeWorkspace.name} · ${scopeId} Filter Preview`});setDebugOpen(true);}catch(e:any){setError(e?.message||'Debug preview failed');}finally{setBusy(false);}};
 const openRunDebug=()=>{if(run){setDebugSession({runId:run.run_id,items:run.debug_images,benchmarks:run.benchmarks,runResult:run,title:`${activeWorkspace?.name??''} · Inspection Debug`});setDebugOpen(true);}};const loadDebug=async(runId:string,key:string)=>URL.createObjectURL(await VisionAppAPI.debugImage(runId,key));
 const clearWorking=()=>{setRun(null);setLocated([]);setTestBlob(null);setTestName('');setTestUrl(old=>{if(old)URL.revokeObjectURL(old);return null;});setDebugOpen(false);};
 const toggleOnline=async()=>{if(!program)return;try{setBusy(true);await save();setAutomationState(automationState?.online?await VisionAppAPI.programOffline(program.program_id):await VisionAppAPI.programOnline(program.program_id));}catch(e:any){setError(e?.message||'Online action failed');}finally{setBusy(false);}};
 const viewportUrl=module==='master'?(masterView==='blur'?(masterBlurUrl??masterUrl):masterUrl):module==='working'?(testUrl??masterUrl):null;const result=automationState?.workspace_results?.[wsAlias]??(run?(run.overall_ok?'OK':'NG'):'NONE');
 if(!program||!activeWorkspace)return <div className="flex h-screen items-center justify-center bg-[#202124] text-[#e8eaed]">{busy?<Loader2 className="animate-spin"/>:'No program/workspace'}</div>;
 return <div className="flex h-screen w-screen flex-col overflow-hidden bg-[#202124] text-[#e8eaed]">
  <header className="flex h-14 shrink-0 items-center gap-2 border-b border-[#3c4043] bg-[#292a2d] px-3"><button onClick={()=>navigate('/')} className="cv-btn"><ArrowLeft size={12}/></button><Sparkles size={16} className="text-[#c58af9]"/><div><div className="text-xs font-black tracking-[.15em]">COMPUTER VISION</div><div className="text-[7px] text-[#80868b]">Resources → Workspaces → Automation Glue</div></div><select value={program.program_id} onChange={e=>void loadProgram(e.target.value)} className="ml-2 w-[170px] rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[9px]">{programs.map(p=><option key={p.program_id} value={p.program_id}>{p.name}</option>)}</select><button onClick={()=>void create()} className="cv-btn">New</button><button onClick={()=>void removeProgram()} className="cv-btn border-[#f28b82] text-[#f28b82]"><Trash2 size={11}/>Remove</button><input value={program.name} onChange={e=>patch({...program,name:e.target.value})} className="w-[150px] rounded border border-[#5f6368] bg-[#202124] px-2 py-1 text-[9px]"/><button onClick={()=>void save()} className="cv-btn border-[#81c995] text-[#81c995]"><Save size={11}/>Save</button><button onClick={()=>void toggleOnline()} className={`cv-btn ml-2 font-black ${automationState?.online?'border-[#81c995] bg-[#1f6b38] text-white shadow-[0_0_12px_rgba(129,201,149,.35)]':'border-[#f28b82] bg-[#5f2120] text-[#ffb4ab] shadow-[0_0_10px_rgba(242,139,130,.18)]'}`}>{automationState?.online?<CircleStop size={11}/>:<CirclePlay size={11}/>} {automationState?.online?'ONLINE':'OFFLINE'}</button><div className="ml-auto flex items-center gap-1"><button className="cv-icon" onClick={()=>setLeftOpen(v=>!v)}>{leftOpen?<ChevronLeft size={12}/>:<ChevronRight size={12}/>}</button><button className="cv-icon" onClick={()=>setRightOpen(v=>!v)}>{rightOpen?<ChevronRight size={12}/>:<ChevronLeft size={12}/>}</button>{module==='working'?<><label className="cv-btn cursor-pointer"><Upload size={11}/>{testName||'Manual test'}<input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)setBlobAsTest(f,f.name);}}/></label><button disabled={!testBlob||busy} onClick={()=>void locate()} className="cv-btn">Locate ROIs</button><button disabled={busy} onClick={()=>void runTest()} className="cv-btn border-[#8ab4f8] bg-[#174ea6]"><Play size={11}/>{testBlob?'Run Test':'Run Bound Input'}</button></>:null}</div></header>
  <WorkspaceTabs workspaces={program.workspaces} activeId={activeWorkspace.workspace_id} onActive={id=>{void activateWorkspaceTab(id);}} onAdd={()=>{void addWorkspace();}} onRemove={id=>{void removeWorkspace(id);}}/>
  <div className="flex h-9 shrink-0 items-center gap-2 border-b border-[#34363a] bg-[#24272b] px-3 text-[7px]"><b className="text-[#ffb86c]">ACTIVE WORKSPACE</b><input className="cv-field !mt-0 w-[150px]" value={activeWorkspace.name} onChange={e=>patchWorkspace(w=>({...w,name:e.target.value}))}/><span>alias</span><input className="cv-field !mt-0 w-[130px] font-mono" value={activeWorkspace.alias} onChange={e=>patchWorkspace(w=>({...w,alias:e.target.value}))}/><span>assigned camera</span><select className="cv-field !mt-0 min-w-[220px]" value={activeWorkspace.camera_id||''} onChange={e=>{const camera=activeWorkspace.cameras.devices.find(c=>c.declaration_id===e.target.value);patchWorkspace(w=>({...w,camera_id:e.target.value,input_binding:camera?`camera.${safe(camera.alias)}.${camera.image_slot}`:''}));}}><option value="">No camera assigned</option>{enabledCameras.map(c=><option key={c.declaration_id} value={c.declaration_id}>{c.alias} · {c.driver}</option>)}</select><span className="font-mono text-[#81c995]">{activeWorkspace.input_binding||'No bound image slot'}</span><span className="ml-auto font-mono text-[#65d1ff]">workspace.{wsAlias}</span></div>
  {error?<div className="shrink-0 bg-[#5f2120] px-3 py-1 text-[9px] text-[#f28b82]">{error}<button onClick={()=>setError('')} className="ml-3 font-black">dismiss</button></div>:null}
  <main className="flex min-h-0 flex-1">{leftOpen?<aside className="w-[145px] shrink-0 border-r border-[#3c4043] bg-[#292a2d] p-2"><div className="mb-2 text-[8px] font-black text-[#80868b]">PROGRAM MODULES</div>{([{key:'iot',label:'IOT Declare',icon:Cpu},{key:'camera',label:'Camera Declare',icon:Camera},{key:'streaming',label:'Streaming',icon:Activity},{key:'master',label:'Master Sample',icon:ImageIcon},{key:'working',label:'Working',icon:Box},{key:'ide',label:'Automation IDE',icon:Braces}] as any[]).map(item=>{const Icon=item.icon;return <button key={item.key} onClick={()=>setModule(item.key)} className={`mb-2 flex w-full flex-col items-center gap-2 rounded-lg border px-2 py-3 text-[8px] font-black ${module===item.key?'border-[#c58af9] bg-[#3b3150] text-white':'border-[#3c4043] bg-[#242528] text-[#9aa0a6]'}`}><Icon size={17}/>{item.label}</button>;})}</aside>:null}
   <section className="relative min-w-0 flex-1">{module==='ide'?<AutomationIdeWorkspace program={program} onProgram={patch} onSave={save} onError={setError}/>:module==='iot'?<IotDeclarationWorkspace key={`iot-${activeWorkspace.workspace_id}`} config={activeWorkspace.iot} onChange={iot=>patchWorkspace(w=>({...w,iot}))}/>:module==='camera'?<CameraDeclarationWorkspace key={`camera-${activeWorkspace.workspace_id}`} programId={program.program_id} config={activeWorkspace.cameras} onChange={cameras=>patchWorkspace(w=>({...w,cameras,camera_id:cameras.devices.some(c=>c.declaration_id===w.camera_id)?w.camera_id:'',input_binding:cameras.devices.some(c=>c.declaration_id===w.camera_id)?w.input_binding:''}))} onCapture={alias=>VisionAppAPI.captureDeclaredCamera(program.program_id,alias)} onStreamFrame={alias=>VisionAppAPI.declaredStreamFrame(program.program_id,alias)} onScan={async()=>{const r=await VisionAppAPI.scanBasler();if(!r.success)setError(r.error||'Basler scan failed');return r.devices;}}/>:module==='streaming'?<StreamingWorkspace key={`streaming-${activeWorkspace.workspace_id}`} programId={program.program_id} workspace={activeWorkspace} camera={activeCamera} onWorkspace={next=>patchWorkspace(()=>next)} onError={setError}/>:<VisionViewport key={`viewport-${activeWorkspace.workspace_id}-${module}`} imageUrl={viewportUrl} rois={module==='master'&&masterView==='original'?activeWorkspace.master.rois:[]} located={module==='working'?located:[]} selectedId={selectedRoi} drawMode={module==='master'&&masterView==='original'&&drawMode} onSelect={setSelectedRoi} onDraw={addRoi}/>} {module==='master'&&activeWorkspace.master.locator.method==='blur_template'?<div className="absolute left-3 top-3 z-20 flex gap-1 rounded border border-[#3c4043] bg-[#202124]/95 p-1"><button className={`cv-debug-tab ${masterView==='original'?'active':''}`} onClick={()=>setMasterView('original')}>Original Master</button><button className={`cv-debug-tab ${masterView==='blur'?'active':''}`} onClick={()=>void previewBlur()}>Blur Preview</button></div>:null}{module==='working'&&result!=='NONE'?<div className={`absolute bottom-5 right-5 min-w-[150px] rounded-xl border-2 px-5 py-4 text-center shadow-2xl ${result==='OK'?'border-[#81c995] bg-[#153d24]/95 text-[#81c995]':'border-[#f28b82] bg-[#5f2120]/95 text-[#f28b82]'}`}><div className="text-[7px] font-black tracking-[.18em]">{activeWorkspace.name.toUpperCase()} RESULT</div><div className="mt-1 text-3xl font-black">{result}</div><div className="mt-1 text-[7px]">{run?`${run.total_ms.toFixed(1)} ms`:'Automation runtime'}</div></div>:null}</section>
   {rightOpen&&(module==='master'||module==='working')?<aside className="w-[470px] shrink-0 overflow-hidden border-l border-[#3c4043] bg-[#292a2d]"><div className="border-b border-[#3c4043] px-3 py-2 text-[9px] font-black uppercase text-[#c58af9]">{module==='master'?'Master Sample / ROI Locator':'Working / Operation & Benchmark'}</div><div className="h-[calc(100%-32px)] overflow-y-auto">{module==='master'?<MasterSamplePanel key={`master-panel-${activeWorkspace.workspace_id}`} rois={activeWorkspace.master.rois} locator={activeWorkspace.master.locator} selectedId={selectedRoi} drawMode={drawMode} onDrawMode={setDrawMode} onSelect={setSelectedRoi} onChange={updateRoi} onRemove={removeRoi} onLocator={locator=>patchWorkspace(w=>({...w,master:{...w.master,locator}}))} onUpload={file=>void uploadMaster(file)} onBlurPreview={()=>void previewBlur()} onShowOriginal={()=>setMasterView('original')}/>:<WorkingModulePanel key={`working-panel-${activeWorkspace.workspace_id}`} services={services} rois={activeWorkspace.master.rois} globalScope={activeWorkspace.working.global_scope} stationScopes={activeWorkspace.working.station_scopes} stationExecution={activeWorkspace.working.station_execution} benchmarks={run?.benchmarks??[]} debugCount={run?.debug_images.length??0} onGlobal={global_scope=>patchWorkspace(w=>({...w,working:{...w.working,global_scope}}))} onStations={station_scopes=>patchWorkspace(w=>({...w,working:{...w.working,station_scopes}}))} onExecution={station_execution=>patchWorkspace(w=>({...w,working:{...w.working,station_execution}}))} onSelectStation={setSelectedRoi} onPreviewDebug={previewScopeDebug} onOpenDebug={openRunDebug}/>}</div></aside>:null}</main>
  <footer className="flex h-7 shrink-0 items-center gap-4 border-t border-[#3c4043] bg-[#242528] px-3 text-[8px] text-[#80868b]"><span>Vision App v0.14.1</span><span>Program: <b className={automationState?.online?'text-[#81c995]':'text-[#80868b]'}>{automationState?.online?'ONLINE':'OFFLINE'}</b></span><span>Workspace: {activeWorkspace.name}</span><span>Camera: <span className="font-mono">{activeWorkspace.cameras.devices.find(c=>c.declaration_id===activeWorkspace.camera_id)?.alias||'unassigned'}</span></span><span className="ml-auto">{program.workspaces.length} workspace(s) · {activeWorkspace.cameras.devices.length} camera(s) in active workspace</span></footer>
  <DebugWorkspace open={debugOpen} runId={debugSession.runId} items={debugSession.items} benchmarks={debugSession.benchmarks} runResult={debugSession.runResult} title={debugSession.title} onClose={()=>setDebugOpen(false)} load={loadDebug}/>
 </div>;
};
