import { Activity, Bug, Edit3, Layers3 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import type { LabServiceDefinition } from '../../api/labServiceApi';
import type { BenchmarkStep, DebugImageRef, MasterRoi, ScopePipelineConfig } from '../../api/visionAppApi';
import { ScopeEditorModal } from './ScopeEditorModal';

type Props={services:LabServiceDefinition[];rois:MasterRoi[];globalScope:ScopePipelineConfig;stationScopes:Record<string,ScopePipelineConfig>;stationExecution:'sequential'|'parallel';benchmarks:BenchmarkStep[];debugImages:DebugImageRef[];onGlobal:(s:ScopePipelineConfig)=>void;onStations:(s:Record<string,ScopePipelineConfig>)=>void;onExecution:(v:'sequential'|'parallel')=>void;onSelectStation?:(id:string)=>void;onPreview:(scopeId:string)=>Promise<{run_id:string;debug_images:DebugImageRef[]}>;loadDebug:(runId:string,key:string)=>Promise<string>;onOpenDebug:()=>void};
const empty=():ScopePipelineConfig=>({enable_filter:false,filter_services:[],enable_logic:false,logic_services:[],enable_decision:false,decision:{script:"if logic_ok:\n    result = 'OK'\nelse:\n    result = 'NG'\n"}});
export const WorkingModulePanel=({services,rois,globalScope,stationScopes,stationExecution,benchmarks,debugImages,onGlobal,onStations,onExecution,onSelectStation,onPreview,loadDebug,onOpenDebug}:Props)=>{
 const [tab,setTab]=useState<'operation'|'benchmark'>('operation'); const [scopeId,setScopeId]=useState('global'); const [editor,setEditor]=useState<{phase:'filter'|'logic';scopeName:string}|null>(null);
 useEffect(()=>{if(scopeId!=='global'&&!rois.some(r=>r.roi_id===scopeId))setScopeId('global');},[rois,scopeId]);
 const roi=rois.find(r=>r.roi_id===scopeId); const scope=scopeId==='global'?globalScope:(stationScopes[scopeId]??empty()); const scopeName=scopeId==='global'?'Global Scope':(roi?.name??'ROI Scope');
 const update=(next:ScopePipelineConfig)=>scopeId==='global'?onGlobal({...next,enable_decision:false}):onStations({...stationScopes,[scopeId]:{...next,enable_decision:false}});
 const filterCount=scope.filter_services.filter(x=>x.enabled).length, logicCount=scope.logic_services.filter(x=>x.enabled).length;
 return <div className="flex h-full flex-col text-[9px]"><div className="grid grid-cols-2 border-b border-[#3c4043]"><button className={`py-2 font-black ${tab==='operation'?'bg-[#3c4043] text-[#8ab4f8]':'text-[#80868b]'}`} onClick={()=>setTab('operation')}>OPERATION</button><button className={`py-2 font-black ${tab==='benchmark'?'bg-[#3c4043] text-[#fdd663]':'text-[#80868b]'}`} onClick={()=>setTab('benchmark')}>BENCHMARK</button></div>{tab==='operation'?<div className="min-h-0 flex-1 overflow-y-auto p-3">
  <div className="mb-3 rounded-lg border border-[#5f6368] bg-[#242528] p-3"><div className="mb-2 flex items-center gap-2 font-black text-[#c58af9]"><Layers3 size={12}/>SCOPE INSPECTOR</div><label>Scope<select className="cv-field" value={scopeId} onChange={e=>{setScopeId(e.target.value);if(e.target.value!=='global')onSelectStation?.(e.target.value)}}><option value="global">Global Scope · runs first</option>{rois.map(r=><option key={r.roi_id} value={r.roi_id}>{r.name} · ROI scope</option>)}</select></label><div className="mt-2 text-[7px] leading-4 text-[#80868b]">Global Filter produces the image used by ROI location and all Local stations. Decision is intentionally reserved for the future IDE/sandbox layer.</div></div>
  {scopeId==='global'?<div className="mb-3 flex items-center justify-between rounded border border-[#3c4043] bg-[#242528] p-2"><span>ROI station execution</span><select className="cv-field !mt-0 !w-[140px]" value={stationExecution} onChange={e=>onExecution(e.target.value as any)}><option value="sequential">Sequential</option><option value="parallel">Parallel</option></select></div>:null}
  <div className="space-y-3 rounded-xl border border-[#3c4043] bg-[#242528] p-3"><div><div className="text-[11px] font-black">{scopeName}</div><div className="mt-1 text-[7px] text-[#80868b]">{scopeId==='global'?'Whole image orchestration':'Station crop orchestration after ROI location'}</div></div>
   <div className="rounded-lg border border-[#3c4043] bg-[#202124] p-3"><div className="flex items-center gap-2"><input type="checkbox" checked={scope.enable_filter} onChange={e=>update({...scope,enable_filter:e.target.checked})}/><b className="flex-1">Filter & Processing</b><span className="rounded bg-[#3c4043] px-2 py-1 text-[7px]">{filterCount} service(s)</span><button className="cv-btn" onClick={()=>setEditor({phase:'filter',scopeName})}><Edit3 size={10}/>Edit</button></div><div className="mt-2 text-[7px] leading-4 text-[#80868b]">Image Processing services run in order. Their real image outputs can be inspected lazily in Debug Workspace.</div></div>
   <div className="rounded-lg border border-[#3c4043] bg-[#202124] p-3"><div className="flex items-center gap-2"><input type="checkbox" checked={scope.enable_logic} onChange={e=>update({...scope,enable_logic:e.target.checked})}/><b className="flex-1">Logic Services</b><span className="rounded bg-[#3c4043] px-2 py-1 text-[7px]">{logicCount} service(s)</span><button className="cv-btn" onClick={()=>setEditor({phase:'logic',scopeName})}><Edit3 size={10}/>Edit</button></div><div className="mt-2 text-[7px] leading-4 text-[#80868b]">Contour, Sampling and future AI services extract information. Their exposed outputs will later be consumed by the IDE decision/glue system.</div></div>
   <div className="rounded-lg border border-dashed border-[#5f6368] bg-[#202124] p-3"><b>Decision / Glue</b><div className="mt-2 text-[7px] leading-4 text-[#80868b]">Reserved for the future IDE / sandbox. This scope currently reports temporary OK when enabled Filter and Logic stages execute successfully.</div></div>
  </div>
  <button disabled={!debugImages.length} onClick={onOpenDebug} className="cv-btn mt-3 w-full border-[#c58af9] text-[#c58af9]"><Bug size={11}/>Open Debug Workspace · {debugImages.length} image(s)</button>
 </div>:<div className="min-h-0 flex-1 overflow-y-auto p-3"><div className="mb-3 rounded border border-[#3c4043] bg-[#242528] p-2 text-[8px] text-[#9aa0a6]"><Activity size={11} className="mr-1 inline"/>Runtime per filter, locator, logic and total cycle. Decision timing is legacy-only until the IDE exists.</div>{benchmarks.length?benchmarks.map((b,i)=><div key={`${b.scope}-${b.phase}-${i}`} className="mb-2 rounded border border-[#3c4043] bg-[#242528] p-2"><div className="flex"><b className="flex-1">{b.scope} · {b.name}</b><span className="text-[#fdd663]">{b.elapsed_ms.toFixed(2)} ms</span></div><div className="mt-1 text-[7px] text-[#80868b]">{b.phase} · {b.detail}</div></div>):<div className="p-6 text-center text-[#80868b]">Run Test to collect benchmark data.</div>}</div>}{editor?<ScopeEditorModal open phase={editor.phase} scopeName={editor.scopeName} scope={scope} services={services} onChange={update} onClose={()=>setEditor(null)} onPreview={()=>onPreview(scopeId)} loadDebug={loadDebug}/>:null}</div>;
};
