import { Camera, ChevronLeft, ChevronRight, FolderOpen, Image as ImageIcon, Loader2, Plus, RefreshCw, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { VisionAppAPI, type MasterRoi, type NormalizedRect, type UtilityBatchResult, type UtilityGatherPlan, type UtilityGatherResult, type WorkspaceDefinition } from '../../api/visionAppApi';
import { VisionViewport } from './VisionViewport';

type Props={
  programId:string;
  workspace:WorkspaceDefinition;
  workspaceAlias:string;
  onSaveProgram:()=>Promise<void>;
  onError:(message:string)=>void;
};

type SourceMode='camera'|'folder';
type RouteState={enabled:boolean;destination:string};
const FULL='__full__';
const safeFolder=(value:string)=>value.trim().replace(/[^A-Za-z0-9_.-]+/g,'_').replace(/^[_\.-]+|[_\.-]+$/g,'')||'roi';
const absolutePath=(value:string)=>/^(?:[A-Za-z]:[\\/]|\\\\|\/)/.test(value.trim());
const manualRoi=(rect:NormalizedRect,index:number):MasterRoi=>({roi_id:`utility_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,name:`Utility ROI ${index+1}`,alias:`UTILITY_${index+1}`,rect,enabled:true});

export const UtilitiesWorkspace=({programId,workspace,workspaceAlias,onSaveProgram,onError}:Props)=>{
 const [mode,setMode]=useState<SourceMode>('camera');const [baseDir,setBaseDir]=useState('');const [sourceDir,setSourceDir]=useState('');const [folderCount,setFolderCount]=useState(0);const [folderIndex,setFolderIndex]=useState(0);const [folderName,setFolderName]=useState('');const [previewUrl,setPreviewUrl]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [status,setStatus]=useState('Ready');const [lastResult,setLastResult]=useState<UtilityGatherResult|UtilityBatchResult|null>(null);const [useMaster,setUseMaster]=useState(true);const [manual,setManual]=useState<MasterRoi[]>([]);const [drawMode,setDrawMode]=useState(false);const [selectedId,setSelectedId]=useState<string|null>(null);const [routes,setRoutes]=useState<Record<string,RouteState>>({[FULL]:{enabled:true,destination:'full'}});
 const allRois=useMemo(()=>[...(useMaster?workspace.master.rois:[]),...manual],[useMaster,workspace.master.rois,manual]);
 const camera=workspace.cameras.devices.find(item=>item.declaration_id===workspace.camera_id)??null;
 const outputRows=useMemo(()=>[{id:FULL,name:'Full Frame',kind:'frame'},...allRois.map(roi=>({id:roi.roi_id,name:roi.name,kind:roi.roi_id.startsWith('utility_')?'manual':'master'}))],[allRois]);
 useEffect(()=>{setRoutes(current=>{const next={...current};for(const row of outputRows){if(!next[row.id])next[row.id]={enabled:true,destination:row.id===FULL?'full':safeFolder(row.name)};}for(const id of Object.keys(next)){if(!outputRows.some(row=>row.id===id))delete next[id];}return next;});},[outputRows]);
 useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);},[previewUrl]);
 const showBlob=(blob:Blob,name:string)=>{setFolderName(name);setPreviewUrl(old=>{if(old)URL.revokeObjectURL(old);return URL.createObjectURL(blob);});};
 const plan=():UtilityGatherPlan=>({base_dir:baseDir,routes:outputRows.map(row=>({output_id:row.id,enabled:routes[row.id]?.enabled??true,destination:routes[row.id]?.destination??''})),rois:allRois.map(roi=>({roi_id:roi.roi_id,name:roi.name,rect:roi.rect})),image_format:'jpg',jpeg_quality:94});
 const validate=()=>{const active=outputRows.filter(row=>routes[row.id]?.enabled!==false);if(!active.length)throw new Error('Enable at least one output.');for(const row of active){if(!(routes[row.id]?.destination??'').trim())throw new Error(`${row.name} has no destination folder.`);}if(active.some(row=>!absolutePath(routes[row.id]?.destination??''))&&!baseDir.trim())throw new Error('Set a base output folder when using relative destinations.');};
 const loadFolder=async(index=0)=>{if(!sourceDir.trim())return;try{setBusy(true);const info=await VisionAppAPI.utilityFolderInfo(programId,workspaceAlias,sourceDir.trim());setFolderCount(info.count);if(!info.count){setPreviewUrl(old=>{if(old)URL.revokeObjectURL(old);return null;});setFolderName('');setStatus('No supported images in folder');return;}const target=Math.max(0,Math.min(index,info.count-1));const preview=await VisionAppAPI.utilityFolderPreview(programId,workspaceAlias,sourceDir.trim(),target);setFolderIndex(preview.index);showBlob(preview.blob,preview.name);setStatus(`${preview.index+1} / ${preview.count}`);}catch(e:any){onError(e?.response?.data?.detail||e?.message||'Folder preview failed');}finally{setBusy(false);}};
 const capture=async()=>{try{validate();if(!camera)throw new Error('Assign an enabled camera to this Workspace first.');setBusy(true);setStatus('Capturing and saving...');await onSaveProgram();const result=await VisionAppAPI.utilityGatherCapture(programId,workspaceAlias,plan());setLastResult(result);const blob=await VisionAppAPI.automationLatestFrame(programId,workspaceAlias);showBlob(blob,result.stem+'.jpg');setStatus(`Saved ${result.saved_count} output(s)${result.failed_count?` · ${result.failed_count} failed`:''}`);}catch(e:any){onError(e?.response?.data?.detail||e?.message||'Utility capture failed');setStatus('Capture failed');}finally{setBusy(false);}};
 const runBatch=async()=>{try{validate();if(!sourceDir.trim())throw new Error('Set an image source folder.');setBusy(true);setStatus('Running folder batch...');const result=await VisionAppAPI.utilityGatherBatch(programId,workspaceAlias,{...plan(),source_dir:sourceDir.trim()});setLastResult(result);setStatus(`Processed ${result.processed_count}/${result.source_count} image(s) · saved ${result.saved_count}`);}catch(e:any){onError(e?.response?.data?.detail||e?.message||'Utility folder batch failed');setStatus('Batch failed');}finally{setBusy(false);}};
 const addManual=(rect:NormalizedRect)=>{const roi=manualRoi(rect,manual.length);setManual(items=>[...items,roi]);setSelectedId(roi.roi_id);setDrawMode(false);};
 const removeManual=(id:string)=>{setManual(items=>items.filter(item=>item.roi_id!==id));if(selectedId===id)setSelectedId(null);};
 const updateManualName=(id:string,name:string)=>setManual(items=>items.map(item=>item.roi_id===id?{...item,name,alias:safeFolder(name).toUpperCase()}:item));
 return <div className="flex h-full min-h-0 bg-[#202124]">
  <section className="relative min-w-0 flex-1"><VisionViewport imageUrl={previewUrl} rois={allRois} selectedId={selectedId} drawMode={drawMode} onSelect={setSelectedId} onDraw={addManual}/><div className="absolute left-3 top-3 z-20 rounded border border-[#3c4043] bg-[#202124]/95 px-2 py-1 text-[8px] text-[#9aa0a6]">{mode==='camera'?(camera?`Camera: ${camera.alias}`:'No camera assigned'):(folderName||'Folder source')}</div></section>
  <aside className="w-[500px] shrink-0 overflow-y-auto border-l border-[#3c4043] bg-[#292a2d] p-3 text-[8px]">
   <div className="mb-3"><div className="text-[10px] font-black text-[#c58af9]">UTILITIES · DATA GATHERING</div><div className="mt-1 leading-4 text-[#9aa0a6]">Harvest full frames and ROI crops. Routing is filesystem-only; no AI/dataset semantics are imposed here.</div></div>
   <div className="mb-3 grid grid-cols-2 gap-2"><button onClick={()=>setMode('camera')} className={`cv-btn justify-center ${mode==='camera'?'border-[#8ab4f8] bg-[#174ea6]':''}`}><Camera size={11}/>Camera Collection</button><button onClick={()=>setMode('folder')} className={`cv-btn justify-center ${mode==='folder'?'border-[#8ab4f8] bg-[#174ea6]':''}`}><FolderOpen size={11}/>Offline Folder</button></div>
   {mode==='folder'?<div className="mb-3 rounded-lg border border-[#3c4043] bg-[#242528] p-2"><div className="mb-1 font-black">SOURCE FOLDER</div><div className="flex gap-1"><input value={sourceDir} onChange={e=>setSourceDir(e.target.value)} placeholder="/path/to/raw_images" className="cv-field !mt-0 flex-1 font-mono"/><button disabled={busy||!sourceDir.trim()} onClick={()=>void loadFolder(0)} className="cv-icon"><RefreshCw size={11}/></button></div><div className="mt-2 flex items-center gap-1"><button disabled={busy||folderIndex<=0} onClick={()=>void loadFolder(folderIndex-1)} className="cv-icon"><ChevronLeft size={11}/></button><button disabled={busy||!folderCount||folderIndex>=folderCount-1} onClick={()=>void loadFolder(folderIndex+1)} className="cv-icon"><ChevronRight size={11}/></button><span className="font-mono text-[#9aa0a6]">{folderCount?`${folderIndex+1}/${folderCount}`:'0 images'}</span><span className="ml-auto truncate font-mono text-[#65d1ff]">{folderName}</span></div></div>:<div className="mb-3 rounded-lg border border-[#3c4043] bg-[#242528] p-2"><div className="font-black">WORKSPACE CAMERA</div><div className="mt-1 font-mono text-[#65d1ff]">{camera?`${camera.alias} · ${camera.driver}`:'No camera assigned'}</div><div className="mt-1 text-[#80868b]">Capture saves the full frame and every enabled output route in one transaction.</div></div>}
   <div className="mb-3 rounded-lg border border-[#3c4043] bg-[#242528] p-2"><div className="flex items-center gap-2"><b className="flex-1">EXTRACTION ROI</b><label className="flex items-center gap-1"><input type="checkbox" checked={useMaster} onChange={e=>setUseMaster(e.target.checked)}/>Master ROIs ({workspace.master.rois.length})</label><button disabled={!previewUrl} onClick={()=>setDrawMode(v=>!v)} className={`cv-btn ${drawMode?'border-[#81c995] text-[#81c995]':''}`}><Plus size={10}/>Draw ROI</button></div>{manual.length?<div className="mt-2 space-y-1">{manual.map(roi=><div key={roi.roi_id} className="flex items-center gap-1"><input className="cv-field !mt-0 flex-1" value={roi.name} onChange={e=>updateManualName(roi.roi_id,e.target.value)} onFocus={()=>setSelectedId(roi.roi_id)}/><button onClick={()=>removeManual(roi.roi_id)} className="cv-icon text-[#f28b82]"><Trash2 size={10}/></button></div>)}</div>:null}</div>
   <div className="mb-2 rounded-lg border border-[#3c4043] bg-[#242528] p-2"><div className="mb-1 flex items-center gap-2"><b className="flex-1">OUTPUT ROUTING</b><span className="text-[#80868b]">relative paths use Base folder</span></div><input value={baseDir} onChange={e=>setBaseDir(e.target.value)} placeholder="Base output folder, e.g. /data/vision_collection" className="cv-field !mt-0 w-full font-mono"/></div>
   <div className="space-y-1">{outputRows.map(row=>{const route=routes[row.id]??{enabled:true,destination:''};return <div key={row.id} className={`rounded border p-2 ${selectedId===row.id?'border-[#fdd663] bg-[#3a3524]':'border-[#3c4043] bg-[#242528]'}`} onClick={()=>row.id!==FULL&&setSelectedId(row.id)}><div className="flex items-center gap-2"><input type="checkbox" checked={route.enabled} onChange={e=>setRoutes(s=>({...s,[row.id]:{...route,enabled:e.target.checked}}))}/><ImageIcon size={10} className={row.kind==='frame'?'text-[#8ab4f8]':row.kind==='master'?'text-[#81c995]':'text-[#fdd663]'}/><b className="w-[120px] truncate">{row.name}</b><input value={route.destination} onChange={e=>setRoutes(s=>({...s,[row.id]:{...route,destination:e.target.value}}))} onClick={e=>e.stopPropagation()} className="cv-field !mt-0 flex-1 font-mono" placeholder="destination folder"/></div></div>;})}</div>
   <div className="mt-3 flex items-center gap-2 border-t border-[#3c4043] pt-3">{mode==='camera'?<button disabled={busy||!camera} onClick={()=>void capture()} className="cv-btn border-[#81c995] bg-[#1f6b38] text-white"><Camera size={11}/>{busy?<Loader2 size={11} className="animate-spin"/>:'Capture + Save'}</button>:<button disabled={busy||!sourceDir.trim()} onClick={()=>void runBatch()} className="cv-btn border-[#81c995] bg-[#1f6b38] text-white"><FolderOpen size={11}/>{busy?<Loader2 size={11} className="animate-spin"/>:'Run Folder Batch'}</button>}<span className="flex-1 truncate text-[#9aa0a6]">{status}</span></div>
   {lastResult?<div className="mt-2 rounded border border-[#3c4043] bg-[#202124] p-2 font-mono text-[7px] text-[#9aa0a6]">{'processed_count' in lastResult?<>source={lastResult.source_count} processed={lastResult.processed_count} saved={lastResult.saved_count} failed={lastResult.failed_count}</>:<>stem={lastResult.stem} saved={lastResult.saved_count} failed={lastResult.failed_count}</>}</div>:null}
  </aside>
 </div>;
};
