import { useEffect, useMemo, useRef, useState } from 'react';
import { Braces, CheckCircle2, CirclePlay, CircleStop, Code2, Cpu, Database, Event, FileCode2, FlaskConical, Play, Plus, Save, Search, Trash2, WandSparkles, XCircle } from 'lucide-react';
import { VisionAppAPI, type AutomationEndpoint, type AutomationExecutionResult, type AutomationServiceDefinition, type AutomationSystemState, type AutomationTraceEntry, type AutomationValidationIssue, type VisionProgramDefinition } from '../../api/visionAppApi';

type Props={
 program:VisionProgramDefinition;
 onProgram:(next:VisionProgramDefinition)=>void;
 onSave:()=>Promise<void>|void;
 onError:(message:string)=>void;
};

const defaultScript=(mode:AutomationServiceDefinition['mode'])=>mode==='loop'
 ? "if device.modbus_1.X1 == ON:\n    system.run_inspection()\n"
 : mode==='event'
 ? "if event.result == OK:\n    device.modbus_1.Y1.pulse(1.0)\nelse:\n    device.modbus_1.Y2.pulse(1.0)\n"
 : "camera.main.capture()\n";

const serviceTemplate=(mode:AutomationServiceDefinition['mode'],index:number):AutomationServiceDefinition=>({
 service_id:`auto_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,
 name:mode==='loop'?`Loop Service ${index}`:mode==='event'?`Event Service ${index}`:`One-shot Service ${index}`,
 enabled:true, mode, interval_ms:250, event:'system.run_finish', script:defaultScript(mode), timeout_ms:1500, concurrency:'skip',
});

const kindIcon=(kind:string)=>kind==='event'?Event:kind==='action'?CirclePlay:kind==='data'?Database:Cpu;

export const AutomationIdeWorkspace=({program,onProgram,onSave,onError}:Props)=>{
 const [selectedId,setSelectedId]=useState<string|null>(program.automation.services[0]?.service_id??null);
 const [endpoints,setEndpoints]=useState<AutomationEndpoint[]>([]);
 const [trace,setTrace]=useState<AutomationTraceEntry[]>([]);
 const [state,setState]=useState<AutomationSystemState|null>(null);
 const [issues,setIssues]=useState<AutomationValidationIssue[]>([]);
 const [execution,setExecution]=useState<AutomationExecutionResult|null>(null);
 const [query,setQuery]=useState('');
 const [bottom,setBottom]=useState<'problems'|'trace'|'variables'>('problems');
 const [busy,setBusy]=useState(false);
 const [suggestOpen,setSuggestOpen]=useState(false);
 const editorRef=useRef<HTMLTextAreaElement|null>(null);
 const service=program.automation.services.find(item=>item.service_id===selectedId)??program.automation.services[0]??null;

 const refresh=async()=>{
  try{
   const [ep,tr,st]=await Promise.all([VisionAppAPI.automationEndpoints(program.program_id),VisionAppAPI.automationTrace(program.program_id),VisionAppAPI.automationState(program.program_id)]);
   setEndpoints(ep);setTrace(tr);setState(st);
  }catch(e:any){onError(e?.response?.data?.detail||e?.message||'Automation IDE refresh failed');}
 };
 useEffect(()=>{setSelectedId(program.automation.services[0]?.service_id??null);void refresh();},[program.program_id]);
 useEffect(()=>{const id=window.setInterval(()=>void VisionAppAPI.automationState(program.program_id).then(setState).catch(()=>{}),700);return()=>window.clearInterval(id);},[program.program_id]);
 useEffect(()=>{if(!state?.scheduler_running)return;const id=window.setInterval(()=>void VisionAppAPI.automationTrace(program.program_id).then(setTrace).catch(()=>{}),700);return()=>window.clearInterval(id);},[program.program_id,state?.scheduler_running]);

 const patchService=(patch:Partial<AutomationServiceDefinition>)=>{
  if(!service)return;
  onProgram({...program,automation:{...program.automation,services:program.automation.services.map(item=>item.service_id===service.service_id?{...item,...patch}:item)}});
 };
 const add=(mode:AutomationServiceDefinition['mode'])=>{const next=serviceTemplate(mode,program.automation.services.length+1);onProgram({...program,automation:{...program.automation,services:[...program.automation.services,next]}});setSelectedId(next.service_id);};
 const remove=()=>{if(!service)return;const services=program.automation.services.filter(item=>item.service_id!==service.service_id);onProgram({...program,automation:{...program.automation,services}});setSelectedId(services[0]?.service_id??null);};
 const validate=async()=>{if(!service)return;try{setBusy(true);const x=await VisionAppAPI.automationValidate(program.program_id,service.script);setIssues(x);setBottom('problems');}catch(e:any){onError(e?.response?.data?.detail||e?.message||'Validate failed');}finally{setBusy(false);}};
 const run=async(dry:boolean)=>{if(!service)return;try{setBusy(true);await onSave();const result=await VisionAppAPI.automationRunService(program.program_id,service.service_id,dry);setExecution(result);setIssues(result.issues);setTrace(await VisionAppAPI.automationTrace(program.program_id));setState(await VisionAppAPI.automationState(program.program_id));setBottom(result.issues.length?'problems':'trace');}catch(e:any){onError(e?.response?.data?.detail||e?.message||'Automation execution failed');}finally{setBusy(false);}};
 const toggleScheduler=async()=>{try{setBusy(true);await onSave();setState(state?.scheduler_running?await VisionAppAPI.automationStop(program.program_id):await VisionAppAPI.automationStart(program.program_id));}catch(e:any){onError(e?.response?.data?.detail||e?.message||'Automation scheduler action failed');}finally{setBusy(false);}};

 const currentPrefix=()=>{const el=editorRef.current;if(!el||!service)return '';const before=service.script.slice(0,el.selectionStart);return before.match(/[A-Za-z_][A-Za-z0-9_.]*$/)?.[0]??'';};
 const prefix=currentPrefix();
 const suggestions=useMemo(()=>{const q=(suggestOpen?prefix:query).toLowerCase();return endpoints.filter(e=>!q||e.path.toLowerCase().includes(q)).slice(0,60);},[endpoints,query,suggestOpen,prefix]);
 const insertSuggestion=(path:string)=>{if(!service||!editorRef.current)return;const el=editorRef.current;const start=el.selectionStart;const end=el.selectionEnd;const before=service.script.slice(0,start);const match=before.match(/[A-Za-z_][A-Za-z0-9_.]*$/);const from=match?start-match[0].length:start;const suffix=end<service.script.length?service.script.slice(end):'';const call=endpoints.find(e=>e.path===path)?.callable?'()':'';const next=service.script.slice(0,from)+path+call+suffix;patchService({script:next});setSuggestOpen(false);window.setTimeout(()=>{el.focus();const pos=from+path.length+(call?1:0);el.setSelectionRange(pos,pos);},0);};

 const grouped=useMemo(()=>({system:endpoints.filter(e=>e.source==='system'),camera:endpoints.filter(e=>e.source==='camera'),modbus:endpoints.filter(e=>e.source==='modbus'),vision:endpoints.filter(e=>e.source.startsWith('vision')),event:endpoints.filter(e=>e.source==='event')}),[endpoints]);
 const editorLines=(service?.script??'').split('\n').length;

 return <div className="cv-ide h-full min-h-0 bg-[#1e1f22] text-[#e8eaed]">
  <div className="flex h-10 items-center gap-2 border-b border-[#3c4043] bg-[#292a2d] px-3 text-[9px]"><Braces size={14} className="text-[#c58af9]"/><b className="tracking-[.14em]">AUTOMATION IDE</b><span className="text-[#80868b]">Endpoint Registry · Safe DSL · Loop / Event / One-shot</span><div className="ml-auto flex items-center gap-1"><button className="cv-btn" onClick={()=>void validate()} disabled={!service||busy}><CheckCircle2 size={10}/>Validate</button><button className="cv-btn border-[#fdd663] text-[#fdd663]" onClick={()=>void run(true)} disabled={!service||busy}><FlaskConical size={10}/>Dry Run</button><button className="cv-btn border-[#8ab4f8] text-[#8ab4f8]" onClick={()=>void run(false)} disabled={!service||busy}><Play size={10}/>Run Service</button><button className={`cv-btn ${state?.scheduler_running?'border-[#f28b82] text-[#f28b82]':'border-[#81c995] text-[#81c995]'}`} onClick={()=>void toggleScheduler()} disabled={busy}>{state?.scheduler_running?<CircleStop size={10}/>:<CirclePlay size={10}/>} {state?.scheduler_running?'Stop Scheduler':'Start Scheduler'}</button><button className="cv-btn" onClick={()=>void onSave()}><Save size={10}/>Save</button></div></div>
  <div className="grid h-[calc(100%-40px)] min-h-0 grid-cols-[250px_minmax(0,1fr)_280px] grid-rows-[minmax(0,1fr)_190px]">
   <aside className="row-span-2 overflow-y-auto border-r border-[#3c4043] bg-[#252629]">
    <div className="border-b border-[#3c4043] p-2"><div className="mb-2 text-[8px] font-black text-[#9aa0a6]">AUTOMATION SERVICES</div><div className="grid grid-cols-3 gap-1"><button className="cv-mini" onClick={()=>add('loop')}>+ Loop</button><button className="cv-mini" onClick={()=>add('event')}>+ Event</button><button className="cv-mini" onClick={()=>add('oneshot')}>+ One-shot</button></div></div>
    <div className="p-1">{program.automation.services.length?program.automation.services.map(s=><button key={s.service_id} onClick={()=>setSelectedId(s.service_id)} className={`mb-1 w-full rounded border p-2 text-left ${s.service_id===service?.service_id?'border-[#8ab4f8] bg-[#26354f]':'border-[#3c4043] bg-[#202124]'}`}><div className="flex items-center gap-2"><FileCode2 size={11} className={s.mode==='loop'?'text-[#81c995]':s.mode==='event'?'text-[#c58af9]':'text-[#8ab4f8]'}/><b className="truncate text-[9px]">{s.name}</b><span className="ml-auto text-[7px] text-[#80868b]">{s.mode}</span></div><div className="mt-1 truncate text-[7px] text-[#80868b]">{s.mode==='loop'?`every ${s.interval_ms} ms`:s.mode==='event'?s.event:'manual / callable'}</div></button>):<div className="p-5 text-center text-[8px] text-[#80868b]">No Automation service yet.<br/>Add Loop, Event or One-shot.</div>}</div>
   </aside>
   <section className="min-w-0 overflow-hidden bg-[#1e1f22]">
    {service?<><div className="flex h-12 items-center gap-2 border-b border-[#3c4043] bg-[#252629] px-2"><input className="cv-field !mt-0 min-w-[190px]" value={service.name} onChange={e=>patchService({name:e.target.value})}/><select className="cv-field !mt-0 w-[90px]" value={service.mode} onChange={e=>patchService({mode:e.target.value as any,script:service.script.trim()?service.script:defaultScript(e.target.value as any)})}><option value="loop">Loop</option><option value="event">Event</option><option value="oneshot">One-shot</option></select>{service.mode==='loop'?<><span className="text-[7px] text-[#80868b]">every</span><input type="number" className="cv-field !mt-0 w-[80px]" value={service.interval_ms} onChange={e=>patchService({interval_ms:Number(e.target.value)})}/><span className="text-[7px] text-[#80868b]">ms</span></>:service.mode==='event'?<select className="cv-field !mt-0 min-w-[180px]" value={service.event} onChange={e=>patchService({event:e.target.value})}>{endpoints.filter(e=>e.kind==='event').map(e=><option key={e.path}>{e.path}</option>)}</select>:null}<label className="ml-auto flex items-center gap-1 text-[8px]"><input type="checkbox" checked={service.enabled} onChange={e=>patchService({enabled:e.target.checked})}/>Enabled</label><button className="cv-icon text-[#f28b82]" onClick={remove}><Trash2 size={11}/></button></div>
     <div className="relative h-[calc(100%-48px)] overflow-hidden"><div className="absolute left-0 top-0 z-10 select-none border-r border-[#34363a] bg-[#18191b] px-2 py-3 text-right font-mono text-[11px] leading-[20px] text-[#5f6368]">{Array.from({length:Math.max(1,editorLines)},(_,i)=><div key={i}>{i+1}</div>)}</div><textarea ref={editorRef} spellCheck={false} value={service.script} onChange={e=>patchService({script:e.target.value})} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.code==='Space'){e.preventDefault();setSuggestOpen(true);}if(e.key==='Escape')setSuggestOpen(false);}} className="h-full w-full resize-none bg-[#1e1f22] py-3 pl-12 pr-4 font-mono text-[12px] leading-[20px] text-[#e8eaed] outline-none" placeholder="if device.modbus_1.X1 == ON:\n    system.run_inspection()"/>{suggestOpen?<div className="absolute left-12 top-10 z-30 max-h-[260px] w-[440px] overflow-y-auto rounded border border-[#5f6368] bg-[#292a2d] shadow-2xl">{suggestions.slice(0,20).map(e=><button key={e.path} className="flex w-full items-start gap-2 border-b border-[#34363a] px-2 py-2 text-left hover:bg-[#3c4043]" onMouseDown={ev=>{ev.preventDefault();insertSuggestion(e.path);}}><Code2 size={10} className="mt-0.5 text-[#8ab4f8]"/><span><b className="font-mono text-[9px]">{e.path}{e.callable?'()':''}</b><span className="ml-2 text-[7px] text-[#80868b]">{e.kind} · {e.data_type}</span><div className="mt-0.5 text-[7px] text-[#9aa0a6]">{e.description}</div></span></button>)}</div>:null}<div className="absolute bottom-2 right-3 text-[7px] text-[#5f6368]">Ctrl+Space · registry-backed completion · safe DSL</div></div></>:<div className="flex h-full items-center justify-center"><div className="max-w-[520px] text-center"><WandSparkles size={30} className="mx-auto mb-3 text-[#c58af9]"/><div className="text-sm font-black">Create an Automation Service</div><div className="mt-2 text-[8px] leading-5 text-[#9aa0a6]">Loop polls states continuously, Event reacts to system/vision lifecycle events, and One-shot is a reusable procedure. All three use the same safe endpoint namespace.</div></div></div>}
   </section>
   <aside className="row-span-2 overflow-y-auto border-l border-[#3c4043] bg-[#252629]"><div className="sticky top-0 z-10 border-b border-[#3c4043] bg-[#252629] p-2"><div className="flex items-center gap-2 text-[8px] font-black text-[#9aa0a6]"><Search size={10}/>ENDPOINT EXPLORER</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search system / device / ROI..." className="cv-field"/></div>{Object.entries(grouped).map(([group,items])=><div key={group} className="border-b border-[#34363a]"><div className="bg-[#202124] px-2 py-1 text-[7px] font-black uppercase tracking-[.12em] text-[#80868b]">{group}</div>{items.filter(e=>!query||e.path.toLowerCase().includes(query.toLowerCase())).slice(0,80).map(e=>{const Icon=kindIcon(e.kind);return <button key={e.path} onClick={()=>insertSuggestion(e.path)} className="block w-full border-t border-[#2d2f32] px-2 py-1.5 text-left hover:bg-[#303134]"><div className="flex items-center gap-1.5"><Icon size={9} className={e.kind==='event'?'text-[#c58af9]':e.kind==='action'?'text-[#81c995]':e.kind==='data'?'text-[#fdd663]':'text-[#8ab4f8]'}/><span className="truncate font-mono text-[8px]">{e.path}</span></div><div className="mt-0.5 truncate pl-4 text-[6px] text-[#80868b]">{e.description}</div></button>})}</div>)}</aside>
   <div className="col-start-2 row-start-2 min-w-0 border-t border-[#3c4043] bg-[#202124]"><div className="flex h-8 items-center gap-1 border-b border-[#34363a] px-2">{(['problems','trace','variables'] as const).map(t=><button key={t} onClick={()=>setBottom(t)} className={`cv-debug-tab ${bottom===t?'active':''}`}>{t==='problems'?`PROBLEMS ${issues.length?`(${issues.length})`:''}`:t==='trace'?`EXECUTION TRACE (${trace.length})`:'VARIABLES'}</button>)}<button className="ml-auto cv-mini" onClick={()=>void refresh()}>Refresh</button>{bottom==='trace'?<button className="cv-mini" onClick={()=>void VisionAppAPI.automationClearTrace(program.program_id).then(()=>setTrace([]))}>Clear</button>:null}</div><div className="h-[calc(100%-32px)] overflow-auto p-2 font-mono text-[8px]">{bottom==='problems'?(issues.length?issues.map((x,i)=><div key={i} className="mb-1 flex gap-2 text-[#f28b82]"><XCircle size={9}/><span>L{x.line}:{x.column} {x.message}</span></div>):<div className="text-[#81c995]">No validation problems.</div>):bottom==='trace'?(trace.length?trace.slice().reverse().map((x,i)=><div key={i} className={`mb-1 grid grid-cols-[145px_120px_1fr] gap-2 ${x.level==='error'?'text-[#f28b82]':x.dry_run?'text-[#fdd663]':'text-[#9aa0a6]'}`}><span>{x.timestamp.slice(11,23)}</span><span>{x.service_name||x.service_id||'system'}</span><span>{x.message}{x.endpoint?` · ${x.endpoint}`:''}{x.value!=null?` · ${JSON.stringify(x.value)}`:''}</span></div>):<div className="text-[#80868b]">No execution trace yet.</div>):<div className="grid grid-cols-2 gap-2 text-[8px]"><div className="rounded border border-[#3c4043] p-2"><b>system.run_state</b><div className="mt-1 text-[#8ab4f8]">{state?.run_state??'IDLE'}</div></div><div className="rounded border border-[#3c4043] p-2"><b>system.result</b><div className={`mt-1 ${state?.result==='OK'?'text-[#81c995]':state?.result==='NG'?'text-[#f28b82]':'text-[#9aa0a6]'}`}>{state?.result??'NONE'}</div></div><div className="rounded border border-[#3c4043] p-2"><b>system.run_id</b><div className="mt-1 truncate text-[#9aa0a6]">{state?.run_id||'—'}</div></div><div className="rounded border border-[#3c4043] p-2"><b>last event</b><div className="mt-1 text-[#c58af9]">{state?.last_event||'—'}</div></div>{execution?<div className="col-span-2 rounded border border-[#3c4043] p-2"><b>Last manual execution</b><div className={execution.ok?'text-[#81c995]':'text-[#f28b82]'}>{execution.ok?'OK':'FAILED'}{execution.dry_run?' · DRY RUN':''}</div></div>:null}</div>}</div></div>
  </div>
 </div>;
};
