import { Camera, Focus, RefreshCcw } from 'lucide-react';
import { useState } from 'react';
import type { BaslerDevice, CameraConfig } from '../../api/visionAppApi';

type Props={config:CameraConfig;onChange:(c:CameraConfig)=>void;onCapture:()=>void;onFocus:(p:{x:number;y:number;w:number;h:number;focal_length?:number|null})=>void;onScan:()=>Promise<BaslerDevice[]>;busy:boolean};
export const CameraModulePanel=({config,onChange,onCapture,onFocus,onScan,busy}:Props)=>{const [devices,setDevices]=useState<BaslerDevice[]>([]);const patch=(p:Partial<CameraConfig>)=>onChange({...config,...p});return <div className="space-y-3 p-3 text-[9px]">
 <div className="rounded-lg border border-[#3c4043] bg-[#242528] p-3"><div className="flex items-center gap-2 text-[10px] font-black"><Camera size={13} className="text-[#8ab4f8]"/>CAMERA SOURCE</div><div className="mt-1 text-[8px] leading-4 text-[#9aa0a6]">Manual upload remains available for engineering. Production trigger cycles capture from Basler or the configured HTTP URL before the inspection runtime starts.</div></div>
 <label className="flex items-center gap-2"><input type="checkbox" checked={config.enabled} onChange={e=>patch({enabled:e.target.checked})}/>Enable Camera</label>
 <label>Driver<select className="cv-field" value={config.driver} onChange={e=>patch({driver:e.target.value as any})}><option value="manual">Manual upload</option><option value="basler">Basler / pypylon</option><option value="url">Generic image URL / Raspberry Pi</option></select></label>
 {config.driver==='basler'?<div className="space-y-2 rounded border border-[#3c4043] bg-[#242528] p-2"><button className="cv-btn w-full" onClick={async()=>setDevices(await onScan())}><RefreshCcw size={11}/>Scan Basler</button><label>Device IP / Serial<select className="cv-field" value={config.basler_device_id} onChange={e=>patch({basler_device_id:e.target.value})}><option value="">Select / type below…</option>{devices.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select><input className="cv-field" value={config.basler_device_id} onChange={e=>patch({basler_device_id:e.target.value})} placeholder="192.168.1.x or serial"/></label><label>Exposure μs<input className="cv-field" type="number" value={config.exposure_us} onChange={e=>patch({exposure_us:Number(e.target.value)})}/></label><label>Grab timeout ms<input className="cv-field" type="number" value={config.grab_timeout_ms} onChange={e=>patch({grab_timeout_ms:Number(e.target.value)})}/></label></div>:null}
 {config.driver==='url'?<div className="space-y-2 rounded border border-[#3c4043] bg-[#242528] p-2"><label>Capture URL<input className="cv-field" value={config.capture_url} onChange={e=>patch({capture_url:e.target.value})}/></label><label>Focus URL template<textarea className="cv-field min-h-[60px]" value={config.focus_url_template} onChange={e=>patch({focus_url_template:e.target.value})}/></label><div className="text-[7px] leading-4 text-[#80868b]">Supported placeholders: {'{x} {y} {w} {h} {focal_length}'}. Example: /focus?x={'{x}'}&y={'{y}'}&w={'{w}'}&h={'{h}'}</div><label>HTTP timeout s<input className="cv-field" type="number" step="0.5" value={config.http_timeout_s} onChange={e=>patch({http_timeout_s:Number(e.target.value)})}/></label><button className="cv-btn w-full" disabled={busy} onClick={()=>onFocus({x:.5,y:.5,w:1,h:1})}><Focus size={11}/>Focus center / full image</button></div>:null}
 <button disabled={busy||config.driver==='manual'} onClick={onCapture} className="cv-btn w-full border-[#8ab4f8] text-[#8ab4f8]"><Camera size={11}/>Capture Test Image</button>
 </div>};
