import { Activity, Edit3 } from 'lucide-react';
import { useState } from 'react';
import type { LabServiceDefinition } from '../../api/labServiceApi';
import type { BenchmarkStep, DebugImageRef, MasterRoi, ScopePipelineConfig } from '../../api/visionAppApi';
import { ScopeEditorModal } from './ScopeEditorModal';

type Props={services:LabServiceDefinition[];rois:MasterRoi[];globalScope:ScopePipelineConfig;stationScopes:Record<string,ScopePipelineConfig>;stationExecution:'sequential'|'parallel';benchmarks:BenchmarkStep[];onGlobal:(s:ScopePipelineConfig)=>void;onStations:(s:Record<string,ScopePipelineConfig>)=>void;onExecution:(v:'sequential'|'parallel')=>void;onSelectStation?:(id:string)=>void;onPreview:(scopeId:string)=>Promise<{run_id:string;debug_images:DebugImageRef[]}>;loadDebug:(runId:string,key:string)=>Promise<string>};
const empty=():ScopePipelineConfig=>({enable_filter:false,filter_services:[],enable_logic:false,logic_services:[],enable_decision:false,decision:{script:"if logic_ok:\n    result = 'OK'\nelse:\n    result = 'NG'\n"}});
const ScopeBlock=({title,scope,onPatch,onEdit,onClick}:{title:string;scope:ScopePipelineConfig;onPatch:(s:ScopePipelineConfig)=>void;onEdit:(phase:'filter'|'logic'|'decision')=>void;onClick?:()=>void})=><div onClick={onClick} className="rounded-xl border border-[#3c4043] bg-[#242528] p-3"><div className="mb-2 text-[10px] font-black text-[#e8eaed]">[{title}]</div>{([['filter','Enable filter','Filters'],['logic','Enable logic','Logics'],['decision','Enable decision','Decision']] as const).map(([key,label,edit])=>{const prop=`enable_${key}` as keyof ScopePipelineConfig;return <div key={key} className="mb-2 flex items-center gap-2 rounded border border-[#35363a] bg-[#202124] p-2"><input type="checkbox" checked={Boolean(scope[prop])} onChange={e=>onPatch({...scope,[prop]:e.target.checked})}/><span className="flex-1 text-[8px]">{label}</span><button className="cv-btn py-1" onClick={e=>{e.stopPropagation();onEdit(key)}}><Edit3 size={10}/>{edit}: Edit</button></div>})}</div>;
export const WorkingModulePanel=({services,rois,globalScope,stationScopes,stationExecution,benchmarks,onGlobal,onStations,onExecution,onSelectStation,onPreview,loadDebug}:Props)=>{const [tab,setTab]=useState<'operation'|'benchmark'>('operation');const [editor,setEditor]=useState<{scopeId:string;scopeName:string;phase:'filter'|'logic'|'decision'}|null>(null);const scopeFor=(id:string)=>id==='global'?globalScope:(stationScopes[id]??empty());const update=(id:string,next:ScopePipelineConfig)=>id==='global'?onGlobal(next):onStations({...stationScopes,[id]:next});return <div className="flex h-full flex-col text-[9px]"><div className="grid grid-cols-2 border-b border-[#3c4043]"><button className={`py-2 font-black ${tab==='operation'?'bg-[#3c4043] text-[#8ab4f8]':'text-[#80868b]'}`} onClick={()=>setTab('operation')}>OPERATION</button><button className={`py-2 font-black ${tab==='benchmark'?'bg-[#3c4043] text-[#fdd663]':'text-[#80868b]'}`} onClick={()=>setTab('benchmark')}>BENCHMARK</button></div>{tab==='operation'?<div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-3"><div className="flex items-center justify-between rounded border border-[#3c4043] bg-[#242528] p-2"><span>ROI station execution</span><select className="cv-field !mt-0 !w-[140px]" value={stationExecution} onChange={e=>onExecution(e.target.value as any)}><option value="sequential">Sequential</option><option value="parallel">Parallel</option></select></div><ScopeBlock title="Global Scope" scope={globalScope} onPatch={onGlobal} onEdit={phase=>setEditor({scopeId:'global',scopeName:'Global Scope',phase})}/>{rois.map(r=><ScopeBlock key={r.roi_id} title={`${r.name} Scope`} scope={scopeFor(r.roi_id)} onClick={()=>onSelectStation?.(r.roi_id)} onPatch={s=>update(r.roi_id,s)} onEdit={phase=>setEditor({scopeId:r.roi_id,scopeName:r.name,phase})}/>)}</div>:<div className="min-h-0 flex-1 overflow-y-auto p-3"><div className="mb-3 rounded border border-[#3c4043] bg-[#242528] p-2 text-[8px] text-[#9aa0a6]"><Activity size={11} className="mr-1 inline"/>Measured runtime per filter, locator, logic, decision and total program cycle.</div>{benchmarks.length?benchmarks.map((b,i)=><div key={`${b.scope}-${b.phase}-${i}`} className="mb-2 rounded border border-[#3c4043] bg-[#242528] p-2"><div className="flex"><b className="flex-1">{b.scope} · {b.name}</b><span className="text-[#fdd663]">{b.elapsed_ms.toFixed(2)} ms</span></div><div className="mt-1 text-[7px] text-[#80868b]">{b.phase} · {b.detail}</div></div>):<div className="p-6 text-center text-[#80868b]">Run Test to collect benchmark data.</div>}</div>}{editor?<ScopeEditorModal open phase={editor.phase} scopeName={editor.scopeName} scope={scopeFor(editor.scopeId)} services={services} onChange={s=>update(editor.scopeId,s)} onClose={()=>setEditor(null)} onPreview={()=>onPreview(editor.scopeId)} loadDebug={loadDebug}/>:null}</div>;
};
