import { useMemo, useState } from 'react';
import { Boxes, Grid3X3, Rows3, X } from 'lucide-react';
import type { SamplingProgramDefinition, SamplingProgramRun } from './types';

const dim=(shape:number[])=>shape.reduce((a,b)=>a*b,1);
const groupBlocks=(blocks:any[])=>{const map=new Map<string,{label:string;d:number;blocks:any[]}>();for(const b of blocks??[]){const key=String(b.block_id??'').split('.')[0]||b.kind;const current=map.get(key)??{label:key,d:0,blocks:[]};current.d+=dim(b.shape??[]);current.blocks.push(b);map.set(key,current);}return [...map.values()];};

export const SamplingOutputShapeDesigner=({program,run,onChange,onClose}:{program:SamplingProgramDefinition;run:SamplingProgramRun|null;onChange:(patch:Partial<SamplingProgramDefinition['output_shape']>)=>void;onClose:()=>void;})=>{
 const [tab,setTab]=useState<'global'|'local'>('global');const [patchIndex,setPatchIndex]=useState(0);
 const globalGroups=useMemo(()=>groupBlocks(run?.global_blocks.blocks??[]),[run]);const patch=run?.local.patches?.[patchIndex]??null;const patchGroups=useMemo(()=>groupBlocks(patch?.blocks??[]),[patch]);
 const rows=program.local_domain.grid.rows,cols=program.local_domain.grid.cols,patchCount=rows*cols;const localShape=run?.local_data.shape??[];
 return <div className="fixed inset-0 z-[80] flex flex-col bg-[#18191b] text-[#e8eaed]"><header className="flex h-14 shrink-0 items-center border-b border-[#3c4043] bg-[#242528] px-4"><Boxes size={17} className="mr-2 text-[#81c995]"/><div><div className="text-xs font-black tracking-[.13em]">OUTPUT SHAPE DESIGNER</div><div className="text-[8px] text-[#80868b]">See how image measurements become the numerical shape consumed later by Rule/AI systems.</div></div><button onClick={onClose} className="ml-auto rounded border border-[#5f6368] p-2"><X size={15}/></button></header>
  <div className="flex min-h-0 flex-1">
   <aside className="w-[300px] shrink-0 border-r border-[#3c4043] bg-[#202124] p-3"><div className="mb-3 grid grid-cols-2 gap-1"><button onClick={()=>setTab('global')} className={`rounded px-2 py-2 text-[9px] font-black ${tab==='global'?'bg-[#174ea6]':'bg-[#303134]'}`}>GLOBAL</button><button onClick={()=>setTab('local')} className={`rounded px-2 py-2 text-[9px] font-black ${tab==='local'?'bg-[#174ea6]':'bg-[#303134]'}`}>LOCAL</button></div>{tab==='local'?<><div className="mb-2 text-[8px] font-black uppercase text-[#9aa0a6]">Local output shape</div><div className="space-y-1">{([['flatten','Flatten vector',Rows3],['patch_matrix','Patch matrix',Grid3X3],['spatial_tensor','Spatial tensor',Boxes]] as const).map(([mode,label,Icon])=><button key={mode} onClick={()=>onChange({local_layout:mode})} className={`flex w-full items-center gap-2 rounded border p-2 text-left text-[9px] ${program.output_shape.local_layout===mode?'border-[#81c995] bg-[#1e3828]':'border-[#3c4043]'}`}><Icon size={13}/><span>{label}</span></button>)}</div><div className="mb-2 mt-4 text-[8px] font-black uppercase text-[#9aa0a6]">Axis order</div><div className="grid grid-cols-2 gap-1"><button onClick={()=>onChange({local_order:'patch_major'})} className={`rounded border px-2 py-2 text-[8px] ${program.output_shape.local_order==='patch_major'?'border-[#8ab4f8] bg-[#174ea6]':'border-[#5f6368]'}`}>Patch first</button><button onClick={()=>onChange({local_order:'feature_major'})} className={`rounded border px-2 py-2 text-[8px] ${program.output_shape.local_order==='feature_major'?'border-[#8ab4f8] bg-[#174ea6]':'border-[#5f6368]'}`}>Feature-depth first</button></div><div className="mt-4 rounded border border-[#3c4043] bg-[#111] p-3"><div className="text-[8px] text-[#80868b]">Grid</div><div className="text-lg font-black text-[#81c995]">{rows} × {cols}</div><div className="mt-2 text-[8px] text-[#80868b]">Materialized output</div><div className="font-mono text-sm text-[#fdd663]">{run?`[${localShape.join(' × ')}]`:'Run to calculate exact D'}</div>{run?<div className="mt-1 text-[8px] text-[#80868b]">feature depth / patch: {run.local_data.metadata?.feature_depth??'?'}</div>:null}</div></>:<div className="rounded border border-[#3c4043] bg-[#111] p-3"><div className="text-[8px] text-[#80868b]">Global output</div><div className="mt-1 font-mono text-lg font-black text-[#fdd663]">{run?`[${run.global_data.shape.join(' × ')}]`:'Run to calculate D'}</div><div className="mt-2 text-[8px] leading-4 text-[#80868b]">Global methods concatenate into one interpretable feature vector in method order.</div></div>}</aside>
   <main className="min-w-0 flex-1 overflow-y-auto p-5">{tab==='global'?<><div className="mb-3 text-[9px] font-black uppercase tracking-[.12em] text-[#8ab4f8]">Global vector composition</div>{run?<div className="flex min-h-[100px] overflow-hidden rounded border border-[#5f6368] bg-[#111]">{globalGroups.map((g,i)=><div key={i} className="flex min-w-[110px] flex-1 flex-col justify-center border-r border-[#3c4043] p-3" style={{flexGrow:Math.max(1,Math.sqrt(g.d))}}><div className="truncate text-[9px] font-black">{g.label}</div><div className="font-mono text-sm text-[#81c995]">D={g.d}</div><div className="text-[7px] text-[#80868b]">{g.blocks.length} data block(s)</div></div>)}</div>:<Empty/>}</>:<><div className="mb-3 text-[9px] font-black uppercase tracking-[.12em] text-[#8ab4f8]">Patch hierarchy</div>{run?<><div className="grid gap-1" style={{gridTemplateColumns:`repeat(${cols},minmax(70px,1fr))`}}>{Array.from({length:patchCount},(_,i)=><button key={i} onClick={()=>setPatchIndex(i)} className={`rounded border p-2 text-left ${i===patchIndex?'border-[#fdd663] bg-[#3c3520]':'border-[#3c4043] bg-[#202124]'}`}><div className="text-[8px] font-black">PATCH {i+1}</div><div className="font-mono text-[10px] text-[#81c995]">D={run.local.patches[i]?.blocks.reduce((n,b)=>n+dim(b.shape),0)??0}</div></button>)}</div><div className="mt-5 rounded border border-[#3c4043] bg-[#111] p-3"><div className="mb-2 text-[8px] font-black uppercase text-[#9aa0a6]">Patch {patchIndex+1} internal feature composition</div><div className="flex min-h-[88px] overflow-hidden rounded border border-[#3c4043]">{patchGroups.map((g,i)=><div key={i} className="flex min-w-[100px] flex-1 flex-col justify-center border-r border-[#3c4043] p-2" style={{flexGrow:Math.max(1,Math.sqrt(g.d))}}><div className="truncate text-[8px] font-black">{g.label}</div><div className="font-mono text-[11px] text-[#8ab4f8]">D={g.d}</div></div>)}</div></div></>:<Empty/>}</>}</main>
   <aside className="w-[280px] shrink-0 border-l border-[#3c4043] bg-[#202124] p-3"><div className="text-[9px] font-black">SERVICE OUTPUTS</div><div className="mt-1 text-[8px] leading-4 text-[#80868b]">Choose which composed shapes become typed service outputs.</div>{([['include_global','Global data'],['include_local','Local data'],['include_combined','Combined flat vector']] as const).map(([key,label])=><label key={key} className="mt-3 flex items-center gap-2 rounded border border-[#3c4043] p-2 text-[9px]"><input type="checkbox" checked={program.output_shape[key]} onChange={(e)=>onChange({[key]:e.target.checked} as any)}/><span>{label}</span></label>)}<div className="mt-4 rounded border border-[#3c4043] bg-[#111] p-3 text-[8px] leading-4 text-[#80868b]"><b className="text-[#bdc1c6]">Mental model</b><br/>Global: [Histogram D][Rays D][Stats D]…<br/><br/>Local: [Patch 1 D][Patch 2 D]… Each Patch D expands into its child methods/channels/measures.</div></aside>
  </div>
 </div>;
};
const Empty=()=> <div className="flex h-[220px] items-center justify-center rounded border border-dashed border-[#5f6368] text-[9px] text-[#80868b]">Run the Sampling Program to materialize exact block dimensions and tensor shape.</div>;
